# Random Forest Classification

In [1]:
import random
import numpy as np
import pandas as pd
import seaborn as sn
from numpy import std
from numpy import mean
import matplotlib.pyplot as plt
from sklearn.datasets import make_classification
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.model_selection import RepeatedStratifiedKFold
from sklearn.metrics import confusion_matrix, accuracy_score
%matplotlib inline

## All CpG

In [2]:
%cd Z:\PPMI_Data\Excels\NonMotors\The251\Male\GeneCpG\Apathy
df = pd.read_csv('ApathyCateg_Methylome_Male.csv')
print(df.shape)
df.head(3)

Z:\PPMI_Data\Excels\NonMotors\The251\Male\GeneCpG\Apathy
(308, 3572)

,Sentrix,PATNO,Gender,APPRDX,HYS,Age,AgeCate,MDS_Apathy_Category,cg19958696,cg05962325,...,cg19795267,cg16922840,cg19628277,cg26480988,cg01673347,cg12994818,cg09008531,cg16463148,cg04021430,cg04863888
0,200991620021_R01C01,3001,1,1,2,65.1,4,0,0.014601,0.068728,...,0.630319,0.851560,0.521620,0.495925,0.830013,0.076462,0.728590,0.246918,0.039718,0.024071
1,200989060135_R07C01,3004,1,2,0,59.4,3,0,0.013334,0.038642,...,0.655485,0.867540,0.546537,0.511772,0.802469,0.033789,0.634950,0.193630,0.023717,0.023474
2,200973410167_R04C01,3007,1,1,2,64.5,3,0,0.015753,0.079013,...,0.719083,0.901237,0.545145,0.540302,0.669380,0.036798,0.766937,0.148859,0.020356,0.023666

In [3]:
df1 = df.drop(['Sentrix','PATNO','HYS','Gender','MDS_Apathy_Category','Age','AgeCate'], axis=1)
df1.head(2)

,APPRDX,cg19958696,cg05962325,cg15093662,cg04873221,cg05903298,cg19020436,cg14994056,cg05973813,cg18337422,...,cg19795267,cg16922840,cg19628277,cg26480988,cg01673347,cg12994818,cg09008531,cg16463148,cg04021430,cg04863888
0,1,0.014601,0.068728,0.019329,0.021747,0.012923,0.017399,0.033939,0.020282,0.017160,...,0.630319,0.85156,0.521620,0.495925,0.830013,0.076462,0.72859,0.246918,0.039718,0.024071
1,2,0.013334,0.038642,0.017604,0.021562,0.012244,0.016683,0.036065,0.021018,0.013908,...,0.655485,0.86754,0.546537,0.511772,0.802469,0.033789,0.63495,0.193630,0.023717,0.023474

In [4]:
np.random.seed (1)
dframe1 = pd.DataFrame(columns=['Accuracy', 'Std_Dev'])

for i in range(1, 101):
    print(i)
    df2 = df1.groupby('APPRDX').apply(lambda x: x.sample(80))
    X = df2.drop('APPRDX', axis = 1)
    y = df2['APPRDX']
    random_forest_model = RandomForestClassifier(n_estimators = 100, max_depth = 5, criterion = 'gini')
    scores = cross_val_score(random_forest_model, X, y, cv = 10, n_jobs = -1)
    mean_score = scores.mean()
    print(f'Mean accuracy: {mean_score}')
    new_row = {'Accuracy': mean_score, 'Std_Dev': std(scores)}
    dframe1 = pd.concat([dframe1, pd.DataFrame(new_row, index=[0])], ignore_index=True)

1
Mean accuracy: 0.375
2
Mean accuracy: 0.4375
3
Mean accuracy: 0.5125
4
Mean accuracy: 0.51875
5
Mean accuracy: 0.51875
6
Mean accuracy: 0.4625
7
Mean accuracy: 0.5375
8
Mean accuracy: 0.4875
9
Mean accuracy: 0.4625
10
Mean accuracy: 0.55625
11
Mean accuracy: 0.5125
12
Mean accuracy: 0.575
13
Mean accuracy: 0.40625
14
Mean accuracy: 0.5
15
Mean accuracy: 0.44375
16
Mean accuracy: 0.44375
17
Mean accuracy: 0.425
18
Mean accuracy: 0.54375
19
Mean accuracy: 0.49375
20
Mean accuracy: 0.525
21
Mean accuracy: 0.50625
22
Mean accuracy: 0.46875
23
Mean accuracy: 0.5125
24
Mean accuracy: 0.525
25
Mean accuracy: 0.51875
26
Mean accuracy: 0.45625
27
Mean accuracy: 0.51875
28
Mean accuracy: 0.45
29
Mean accuracy: 0.46875
30
Mean accuracy: 0.53125
31
Mean accuracy: 0.5
32
Mean accuracy: 0.54375
33
Mean accuracy: 0.5375
34
Mean accuracy: 0.54375
35
Mean accuracy: 0.50625
36
Mean accuracy: 0.4625
37
Mean accuracy: 0.48125
38
Mean accuracy: 0.55
39
Mean accuracy: 0.5375
40
Mean accuracy: 0.46875
41
Mean accuracy: 0.4625
42
Mean accuracy: 0.50625
43
Mean accuracy: 0.5125
44
Mean accuracy: 0.525
45
Mean accuracy: 0.53125
46
Mean accuracy: 0.53125
47
Mean accuracy: 0.49375
48
Mean accuracy: 0.5125
49
Mean accuracy: 0.4875
50
Mean accuracy: 0.5375
51
Mean accuracy: 0.50625
52
Mean accuracy: 0.45625
53
Mean accuracy: 0.5625
54
Mean accuracy: 0.4875
55
Mean accuracy: 0.54375
56
Mean accuracy: 0.475
57
Mean accuracy: 0.46875
58
Mean accuracy: 0.4125
59
Mean accuracy: 0.51875
60
Mean accuracy: 0.51875
61
Mean accuracy: 0.5125
62
Mean accuracy: 0.41875
63
Mean accuracy: 0.525
64
Mean accuracy: 0.5125
65
Mean accuracy: 0.60625
66
Mean accuracy: 0.525
67
Mean accuracy: 0.49375
68
Mean accuracy: 0.4625
69
Mean accuracy: 0.4875
70
Mean accuracy: 0.475
71
Mean accuracy: 0.45
72
Mean accuracy: 0.49375
73
Mean accuracy: 0.54375
74
Mean accuracy: 0.5
75
Mean accuracy: 0.475
76
Mean accuracy: 0.5125
77
Mean accuracy: 0.525
78
Mean accuracy: 0.55
79
Mean accuracy: 0.45625
80
Mean accuracy: 0.45
81
Mean accuracy: 0.44375
82
Mean accuracy: 0.5
83
Mean accuracy: 0.4625
84
Mean accuracy: 0.475
85
Mean accuracy: 0.45
86
Mean accuracy: 0.5125
87
Mean accuracy: 0.5625
88
Mean accuracy: 0.525
89
Mean accuracy: 0.4875
90
Mean accuracy: 0.50625
91
Mean accuracy: 0.50625
92
Mean accuracy: 0.43125
93
Mean accuracy: 0.46875
94
Mean accuracy: 0.44375
95
Mean accuracy: 0.5375
96
Mean accuracy: 0.49375
97
Mean accuracy: 0.44375
98
Mean accuracy: 0.46875
99
Mean accuracy: 0.475
100
Mean accuracy: 0.48125

In [5]:
print(mean(dframe1['Accuracy']))
dframe1.to_csv ("Apathy_AllCpG_Male_100RF.csv", index = False)

0.49525000000000013

## RanFor 100 times. Samples = 50

In [6]:
df2 = df1.drop (['APPRDX'], axis=1)

In [7]:
np.random.seed (1)
dframe1 = pd.DataFrame(columns=['Accuracy', 'Std_Dev'])
for i in range (1,101) :
        print(i)
        df3 = df2.sample(50, axis=1)
        df3 = df3.reindex(['APPRDX', *df3.columns], axis=1).assign(APPRDX=df1['APPRDX'])
        dataset = df3.groupby('APPRDX').apply(lambda x: x.sample(80))
        X = dataset.iloc[:, 1:].values
        y = dataset.iloc[:, 0].values
        random_forest_model = RandomForestClassifier(n_estimators = 100, max_depth = 5, criterion = 'gini')
        scores = cross_val_score(random_forest_model, X, y, cv = 10, n_jobs = -1)
        mean_score = scores.mean()
        print(f'Mean accuracy: {mean_score}')
        new_row = {'Accuracy': mean_score, 'Std_Dev': std(scores)}
        dframe1 = pd.concat([dframe1, pd.DataFrame(new_row, index=[0])], ignore_index=True)

1
Mean accuracy: 0.43125
2
Mean accuracy: 0.5125
3
Mean accuracy: 0.4375
4
Mean accuracy: 0.50625
5
Mean accuracy: 0.51875
6
Mean accuracy: 0.53125
7
Mean accuracy: 0.525
8
Mean accuracy: 0.45
9
Mean accuracy: 0.425
10
Mean accuracy: 0.54375
11
Mean accuracy: 0.48125
12
Mean accuracy: 0.43125
13
Mean accuracy: 0.46875
14
Mean accuracy: 0.5625
15
Mean accuracy: 0.56875
16
Mean accuracy: 0.5625
17
Mean accuracy: 0.5
18
Mean accuracy: 0.475
19
Mean accuracy: 0.53125
20
Mean accuracy: 0.525
21
Mean accuracy: 0.49375
22
Mean accuracy: 0.45
23
Mean accuracy: 0.475
24
Mean accuracy: 0.56875
25
Mean accuracy: 0.4875
26
Mean accuracy: 0.49375
27
Mean accuracy: 0.5
28
Mean accuracy: 0.59375
29
Mean accuracy: 0.5125
30
Mean accuracy: 0.5375
31
Mean accuracy: 0.4875
32
Mean accuracy: 0.525
33
Mean accuracy: 0.50625
34
Mean accuracy: 0.53125
35
Mean accuracy: 0.45625
36
Mean accuracy: 0.53125
37
Mean accuracy: 0.54375
38
Mean accuracy: 0.41875
39
Mean accuracy: 0.53125
40
Mean accuracy: 0.5375
41
Mean accuracy: 0.54375
42
Mean accuracy: 0.525
43
Mean accuracy: 0.51875
44
Mean accuracy: 0.50625
45
Mean accuracy: 0.4375
46
Mean accuracy: 0.50625
47
Mean accuracy: 0.46875
48
Mean accuracy: 0.46875
49
Mean accuracy: 0.44375
50
Mean accuracy: 0.5
51
Mean accuracy: 0.525
52
Mean accuracy: 0.575
53
Mean accuracy: 0.55625
54
Mean accuracy: 0.4125
55
Mean accuracy: 0.48125
56
Mean accuracy: 0.51875
57
Mean accuracy: 0.50625
58
Mean accuracy: 0.4875
59
Mean accuracy: 0.45625
60
Mean accuracy: 0.54375
61
Mean accuracy: 0.5625
62
Mean accuracy: 0.34375
63
Mean accuracy: 0.4375
64
Mean accuracy: 0.49375
65
Mean accuracy: 0.3875
66
Mean accuracy: 0.54375
67
Mean accuracy: 0.49375
68
Mean accuracy: 0.475
69
Mean accuracy: 0.575
70
Mean accuracy: 0.4625
71
Mean accuracy: 0.475
72
Mean accuracy: 0.5125
73
Mean accuracy: 0.4625
74
Mean accuracy: 0.45
75
Mean accuracy: 0.425
76
Mean accuracy: 0.4875
77
Mean accuracy: 0.5375
78
Mean accuracy: 0.50625
79
Mean accuracy: 0.5
80
Mean accuracy: 0.54375
81
Mean accuracy: 0.45625
82
Mean accuracy: 0.475
83
Mean accuracy: 0.4625
84
Mean accuracy: 0.46875
85
Mean accuracy: 0.56875
86
Mean accuracy: 0.4625
87
Mean accuracy: 0.475
88
Mean accuracy: 0.5625
89
Mean accuracy: 0.55625
90
Mean accuracy: 0.4875
91
Mean accuracy: 0.50625
92
Mean accuracy: 0.5
93
Mean accuracy: 0.4625
94
Mean accuracy: 0.525
95
Mean accuracy: 0.48125
96
Mean accuracy: 0.45
97
Mean accuracy: 0.59375
98
Mean accuracy: 0.5375
99
Mean accuracy: 0.50625
100
Mean accuracy: 0.50625

In [8]:
print(mean(dframe1['Accuracy']))
dframe1.to_csv ("Apathy_Rand50CpG_Male_100RF.csv", index = False)

0.4986875000000002

## RanFor 100 times. Samples = 89

In [9]:
np.random.seed (1)
dframe1 = pd.DataFrame(columns=['Accuracy', 'Std_Dev'])
for i in range (1,101) :
        print(i)
        df3 = df2.sample(89, axis=1)
        df3 = df3.reindex(['APPRDX', *df3.columns], axis=1).assign(APPRDX=df1['APPRDX'])
        dataset = df3.groupby('APPRDX').apply(lambda x: x.sample(80))
        X = dataset.iloc[:, 1:].values
        y = dataset.iloc[:, 0].values
        random_forest_model = RandomForestClassifier(n_estimators = 100, max_depth = 5, criterion = 'gini')
        scores = cross_val_score(random_forest_model, X, y, cv = 10, n_jobs = -1)
        mean_score = scores.mean()
        print(f'Mean accuracy: {mean_score}')
        new_row = {'Accuracy': mean_score, 'Std_Dev': std(scores)}
        dframe1 = pd.concat([dframe1, pd.DataFrame(new_row, index=[0])], ignore_index=True)

1
Mean accuracy: 0.50625
2
Mean accuracy: 0.49375
3
Mean accuracy: 0.46875
4
Mean accuracy: 0.48125
5
Mean accuracy: 0.51875
6
Mean accuracy: 0.5125
7
Mean accuracy: 0.55
8
Mean accuracy: 0.39375
9
Mean accuracy: 0.4125
10
Mean accuracy: 0.51875
11
Mean accuracy: 0.425
12
Mean accuracy: 0.425
13
Mean accuracy: 0.4125
14
Mean accuracy: 0.55625
15
Mean accuracy: 0.50625
16
Mean accuracy: 0.525
17
Mean accuracy: 0.48125
18
Mean accuracy: 0.45
19
Mean accuracy: 0.49375
20
Mean accuracy: 0.55625
21
Mean accuracy: 0.55625
22
Mean accuracy: 0.475
23
Mean accuracy: 0.58125
24
Mean accuracy: 0.59375
25
Mean accuracy: 0.59375
26
Mean accuracy: 0.4875
27
Mean accuracy: 0.48125
28
Mean accuracy: 0.5625
29
Mean accuracy: 0.51875
30
Mean accuracy: 0.5375
31
Mean accuracy: 0.4625
32
Mean accuracy: 0.5375
33
Mean accuracy: 0.48125
34
Mean accuracy: 0.49375
35
Mean accuracy: 0.45625
36
Mean accuracy: 0.6
37
Mean accuracy: 0.53125
38
Mean accuracy: 0.4375
39
Mean accuracy: 0.4375
40
Mean accuracy: 0.5625
41
Mean accuracy: 0.525
42
Mean accuracy: 0.51875
43
Mean accuracy: 0.51875
44
Mean accuracy: 0.55
45
Mean accuracy: 0.45625
46
Mean accuracy: 0.4125
47
Mean accuracy: 0.4875
48
Mean accuracy: 0.5
49
Mean accuracy: 0.4625
50
Mean accuracy: 0.55
51
Mean accuracy: 0.4875
52
Mean accuracy: 0.525
53
Mean accuracy: 0.49375
54
Mean accuracy: 0.45
55
Mean accuracy: 0.4375
56
Mean accuracy: 0.6125
57
Mean accuracy: 0.53125
58
Mean accuracy: 0.49375
59
Mean accuracy: 0.475
60
Mean accuracy: 0.54375
61
Mean accuracy: 0.58125
62
Mean accuracy: 0.4125
63
Mean accuracy: 0.525
64
Mean accuracy: 0.54375
65
Mean accuracy: 0.4375
66
Mean accuracy: 0.5125
67
Mean accuracy: 0.4875
68
Mean accuracy: 0.46875
69
Mean accuracy: 0.4875
70
Mean accuracy: 0.44375
71
Mean accuracy: 0.4875
72
Mean accuracy: 0.55
73
Mean accuracy: 0.48125
74
Mean accuracy: 0.425
75
Mean accuracy: 0.45625
76
Mean accuracy: 0.49375
77
Mean accuracy: 0.50625
78
Mean accuracy: 0.61875
79
Mean accuracy: 0.50625
80
Mean accuracy: 0.54375
81
Mean accuracy: 0.4875
82
Mean accuracy: 0.48125
83
Mean accuracy: 0.48125
84
Mean accuracy: 0.45
85
Mean accuracy: 0.55
86
Mean accuracy: 0.5
87
Mean accuracy: 0.46875
88
Mean accuracy: 0.525
89
Mean accuracy: 0.45625
90
Mean accuracy: 0.5
91
Mean accuracy: 0.5
92
Mean accuracy: 0.525
93
Mean accuracy: 0.50625
94
Mean accuracy: 0.51875
95
Mean accuracy: 0.58125
96
Mean accuracy: 0.4
97
Mean accuracy: 0.475
98
Mean accuracy: 0.54375
99
Mean accuracy: 0.55625
100
Mean accuracy: 0.55

In [10]:
print(mean(dframe1['Accuracy']))
dframe1.to_csv ("Apathy_Rand89CpG_Male_100RF.csv", index = False)

0.5013124999999998

## RanFor Top 50 Boruta 100 times. Samples = 50

In [11]:
df1 = pd.read_csv('Apathy_Boruta_Top50_Data_Male.csv')
print(df1.shape)
df1.head(2)

(308, 51)

,APPRDX,cg07584368,cg02699673,cg10957063,cg08955609,cg10400309,cg03984780,cg11865360,cg08409074,cg08702946,...,cg19125584,cg25361663,cg25288762,cg23362473,cg16643803,cg01447828,cg26126367,cg07897734,cg06552618,cg13959611
0,1,0.868743,0.621165,0.630408,0.046059,0.013044,0.065929,0.279839,0.036602,0.922071,...,0.791878,0.911043,0.85890,0.917361,0.029913,0.441146,0.825690,0.842938,0.035788,0.044262
1,2,0.864397,0.576635,0.632613,0.026931,0.010265,0.066287,0.098743,0.020570,0.922684,...,0.832648,0.929506,0.85435,0.900393,0.033853,0.559728,0.852642,0.894486,0.031247,0.048167

In [12]:
np.random.seed (1)
dframe1 = pd.DataFrame(columns=['Accuracy', 'Std_Dev'])

for i in range(1, 101):
    print(i)
    df2 = df1.groupby('APPRDX').apply(lambda x: x.sample(80))
    X = df2.drop('APPRDX', axis = 1)
    y = df2['APPRDX']
    random_forest_model = RandomForestClassifier(n_estimators = 100, max_depth = 5, criterion = 'gini')
    scores = cross_val_score(random_forest_model, X, y, cv = 10, n_jobs = -1)
    mean_score = scores.mean()
    print(f'Mean accuracy: {mean_score}')
    new_row = {'Accuracy': mean_score, 'Std_Dev': std(scores)}
    dframe1 = pd.concat([dframe1, pd.DataFrame(new_row, index=[0])], ignore_index=True)

1
Mean accuracy: 0.575
2
Mean accuracy: 0.54375
3
Mean accuracy: 0.6375
4
Mean accuracy: 0.65
5
Mean accuracy: 0.625
6
Mean accuracy: 0.66875
7
Mean accuracy: 0.6125
8
Mean accuracy: 0.61875
9
Mean accuracy: 0.6125
10
Mean accuracy: 0.5875
11
Mean accuracy: 0.63125
12
Mean accuracy: 0.64375
13
Mean accuracy: 0.65625
14
Mean accuracy: 0.68125
15
Mean accuracy: 0.5875
16
Mean accuracy: 0.64375
17
Mean accuracy: 0.6125
18
Mean accuracy: 0.63125
19
Mean accuracy: 0.625
20
Mean accuracy: 0.6375
21
Mean accuracy: 0.5875
22
Mean accuracy: 0.63125
23
Mean accuracy: 0.64375
24
Mean accuracy: 0.7
25
Mean accuracy: 0.64375
26
Mean accuracy: 0.63125
27
Mean accuracy: 0.6375
28
Mean accuracy: 0.59375
29
Mean accuracy: 0.625
30
Mean accuracy: 0.575
31
Mean accuracy: 0.6625
32
Mean accuracy: 0.6625
33
Mean accuracy: 0.59375
34
Mean accuracy: 0.64375
35
Mean accuracy: 0.71875
36
Mean accuracy: 0.68125
37
Mean accuracy: 0.65625
38
Mean accuracy: 0.625
39
Mean accuracy: 0.725
40
Mean accuracy: 0.59375
41
Mean accuracy: 0.60625
42
Mean accuracy: 0.6375
43
Mean accuracy: 0.69375
44
Mean accuracy: 0.68125
45
Mean accuracy: 0.6125
46
Mean accuracy: 0.63125
47
Mean accuracy: 0.5875
48
Mean accuracy: 0.65
49
Mean accuracy: 0.68125
50
Mean accuracy: 0.68125
51
Mean accuracy: 0.60625
52
Mean accuracy: 0.63125
53
Mean accuracy: 0.6875
54
Mean accuracy: 0.60625
55
Mean accuracy: 0.575
56
Mean accuracy: 0.6
57
Mean accuracy: 0.60625
58
Mean accuracy: 0.60625
59
Mean accuracy: 0.63125
60
Mean accuracy: 0.64375
61
Mean accuracy: 0.675
62
Mean accuracy: 0.625
63
Mean accuracy: 0.5875
64
Mean accuracy: 0.625
65
Mean accuracy: 0.65625
66
Mean accuracy: 0.64375
67
Mean accuracy: 0.63125
68
Mean accuracy: 0.675
69
Mean accuracy: 0.625
70
Mean accuracy: 0.5875
71
Mean accuracy: 0.6
72
Mean accuracy: 0.56875
73
Mean accuracy: 0.65
74
Mean accuracy: 0.575
75
Mean accuracy: 0.60625
76
Mean accuracy: 0.64375
77
Mean accuracy: 0.64375
78
Mean accuracy: 0.64375
79
Mean accuracy: 0.625
80
Mean accuracy: 0.5625
81
Mean accuracy: 0.63125
82
Mean accuracy: 0.68125
83
Mean accuracy: 0.6375
84
Mean accuracy: 0.60625
85
Mean accuracy: 0.6
86
Mean accuracy: 0.64375
87
Mean accuracy: 0.7
88
Mean accuracy: 0.65625
89
Mean accuracy: 0.65625
90
Mean accuracy: 0.6
91
Mean accuracy: 0.6375
92
Mean accuracy: 0.59375
93
Mean accuracy: 0.58125
94
Mean accuracy: 0.6375
95
Mean accuracy: 0.625
96
Mean accuracy: 0.60625
97
Mean accuracy: 0.6
98
Mean accuracy: 0.61875
99
Mean accuracy: 0.63125
100
Mean accuracy: 0.65

In [13]:
print(mean(dframe1['Accuracy']))
dframe1.to_csv ("Apathy_Boruta50CpG_Male_100RF.csv", index = False)

0.6301250000000002

## RanFor Top 50 NMI 100 times. Samples = 50

In [14]:
df = pd.read_csv('Top50NMI_Apathy_Data_Male.csv')
print(df.shape)
df.head(2)

(308, 52)

,PATNO,APPRDX,cg20003494,cg19325183,cg06470379,cg02157463,cg25885883,cg03605226,cg12049462,cg19738007,...,cg26694605,cg21747876,cg03984780,cg27399558,cg02304033,cg06482044,cg18181070,cg06485214,cg20679560,cg11192270
0,3001,1,0.025708,0.833177,0.775220,0.641978,0.845724,0.051677,0.131758,0.033204,...,0.826091,0.898519,0.065929,0.625698,0.842137,0.037614,0.019802,0.859371,0.031971,0.088801
1,3004,2,0.035014,0.854240,0.806864,0.595703,0.836889,0.081028,0.046713,0.037324,...,0.854978,0.899897,0.066287,0.650475,0.782012,0.029573,0.018106,0.824870,0.025527,0.058767

In [15]:
df1 = df.drop(['PATNO'], axis=1)
df1.head(2)

,APPRDX,cg20003494,cg19325183,cg06470379,cg02157463,cg25885883,cg03605226,cg12049462,cg19738007,cg16260438,...,cg26694605,cg21747876,cg03984780,cg27399558,cg02304033,cg06482044,cg18181070,cg06485214,cg20679560,cg11192270
0,1,0.025708,0.833177,0.775220,0.641978,0.845724,0.051677,0.131758,0.033204,0.803189,...,0.826091,0.898519,0.065929,0.625698,0.842137,0.037614,0.019802,0.859371,0.031971,0.088801
1,2,0.035014,0.854240,0.806864,0.595703,0.836889,0.081028,0.046713,0.037324,0.860886,...,0.854978,0.899897,0.066287,0.650475,0.782012,0.029573,0.018106,0.824870,0.025527,0.058767

In [16]:
np.random.seed (1)
dframe1 = pd.DataFrame(columns=['Accuracy', 'Std_Dev'])

for i in range(1, 101):
    print(i)
    df2 = df1.groupby('APPRDX').apply(lambda x: x.sample(80))
    X = df2.drop('APPRDX', axis = 1)
    y = df2['APPRDX']
    random_forest_model = RandomForestClassifier(n_estimators = 100, max_depth = 5, criterion = 'gini')
    scores = cross_val_score(random_forest_model, X, y, cv = 10, n_jobs = -1)
    mean_score = scores.mean()
    print(f'Mean accuracy: {mean_score}')
    new_row = {'Accuracy': mean_score, 'Std_Dev': std(scores)}
    dframe1 = pd.concat([dframe1, pd.DataFrame(new_row, index=[0])], ignore_index=True)

1
Mean accuracy: 0.60625
2
Mean accuracy: 0.6
3
Mean accuracy: 0.6625
4
Mean accuracy: 0.65625
5
Mean accuracy: 0.65625
6
Mean accuracy: 0.6375
7
Mean accuracy: 0.71875
8
Mean accuracy: 0.625
9
Mean accuracy: 0.65
10
Mean accuracy: 0.63125
11
Mean accuracy: 0.6875
12
Mean accuracy: 0.68125
13
Mean accuracy: 0.71875
14
Mean accuracy: 0.70625
15
Mean accuracy: 0.6
16
Mean accuracy: 0.66875
17
Mean accuracy: 0.64375
18
Mean accuracy: 0.675
19
Mean accuracy: 0.61875
20
Mean accuracy: 0.6375
21
Mean accuracy: 0.6125
22
Mean accuracy: 0.625
23
Mean accuracy: 0.65
24
Mean accuracy: 0.73125
25
Mean accuracy: 0.6375
26
Mean accuracy: 0.70625
27
Mean accuracy: 0.64375
28
Mean accuracy: 0.64375
29
Mean accuracy: 0.6375
30
Mean accuracy: 0.64375
31
Mean accuracy: 0.66875
32
Mean accuracy: 0.6875
33
Mean accuracy: 0.69375
34
Mean accuracy: 0.6625
35
Mean accuracy: 0.7125
36
Mean accuracy: 0.65625
37
Mean accuracy: 0.7
38
Mean accuracy: 0.66875
39
Mean accuracy: 0.68125
40
Mean accuracy: 0.65
41
Mean accuracy: 0.63125
42
Mean accuracy: 0.6875
43
Mean accuracy: 0.6875
44
Mean accuracy: 0.70625
45
Mean accuracy: 0.68125
46
Mean accuracy: 0.61875
47
Mean accuracy: 0.65625
48
Mean accuracy: 0.6875
49
Mean accuracy: 0.725
50
Mean accuracy: 0.7
51
Mean accuracy: 0.65625
52
Mean accuracy: 0.65625
53
Mean accuracy: 0.7
54
Mean accuracy: 0.6875
55
Mean accuracy: 0.66875
56
Mean accuracy: 0.56875
57
Mean accuracy: 0.6375
58
Mean accuracy: 0.675
59
Mean accuracy: 0.675
60
Mean accuracy: 0.675
61
Mean accuracy: 0.73125
62
Mean accuracy: 0.6625
63
Mean accuracy: 0.65
64
Mean accuracy: 0.63125
65
Mean accuracy: 0.6875
66
Mean accuracy: 0.63125
67
Mean accuracy: 0.7
68
Mean accuracy: 0.68125
69
Mean accuracy: 0.61875
70
Mean accuracy: 0.60625
71
Mean accuracy: 0.6625
72
Mean accuracy: 0.6375
73
Mean accuracy: 0.675
74
Mean accuracy: 0.63125
75
Mean accuracy: 0.7
76
Mean accuracy: 0.61875
77
Mean accuracy: 0.6625
78
Mean accuracy: 0.71875
79
Mean accuracy: 0.65
80
Mean accuracy: 0.6125
81
Mean accuracy: 0.64375
82
Mean accuracy: 0.66875
83
Mean accuracy: 0.6625
84
Mean accuracy: 0.68125
85
Mean accuracy: 0.65
86
Mean accuracy: 0.64375
87
Mean accuracy: 0.66875
88
Mean accuracy: 0.74375
89
Mean accuracy: 0.675
90
Mean accuracy: 0.65
91
Mean accuracy: 0.6875
92
Mean accuracy: 0.6625
93
Mean accuracy: 0.64375
94
Mean accuracy: 0.70625
95
Mean accuracy: 0.70625
96
Mean accuracy: 0.6625
97
Mean accuracy: 0.675
98
Mean accuracy: 0.6625
99
Mean accuracy: 0.66875
100
Mean accuracy: 0.6375

In [17]:
print(mean(dframe1['Accuracy']))
dframe1.to_csv ("Apathy_NMI50CpG_Male_100RF.csv", index = False)

0.6634375

## RanFor Top 50 Boruta + NMI 100 times. Samples = 89

In [18]:
df = pd.read_csv('Apathy_Top50sMerge_Data_Male.csv')
print(df.shape)
df.head(2)

(308, 91)

,PATNO,APPRDX,cg20003494,cg19325183,cg06470379,cg02157463,cg25885883,cg03605226,cg12049462,cg19738007,...,cg06182337,cg20095237,cg19125584,cg25288762,cg23362473,cg16643803,cg26126367,cg07897734,cg06552618,cg13959611
0,3001,1,0.025708,0.833177,0.775220,0.641978,0.845724,0.051677,0.131758,0.033204,...,0.792306,0.826175,0.791878,0.85890,0.917361,0.029913,0.825690,0.842938,0.035788,0.044262
1,3004,2,0.035014,0.854240,0.806864,0.595703,0.836889,0.081028,0.046713,0.037324,...,0.854751,0.913702,0.832648,0.85435,0.900393,0.033853,0.852642,0.894486,0.031247,0.048167

In [19]:
df1 = df.drop(['PATNO'], axis=1)
df1.head(2)

,APPRDX,cg20003494,cg19325183,cg06470379,cg02157463,cg25885883,cg03605226,cg12049462,cg19738007,cg16260438,...,cg06182337,cg20095237,cg19125584,cg25288762,cg23362473,cg16643803,cg26126367,cg07897734,cg06552618,cg13959611
0,1,0.025708,0.833177,0.775220,0.641978,0.845724,0.051677,0.131758,0.033204,0.803189,...,0.792306,0.826175,0.791878,0.85890,0.917361,0.029913,0.825690,0.842938,0.035788,0.044262
1,2,0.035014,0.854240,0.806864,0.595703,0.836889,0.081028,0.046713,0.037324,0.860886,...,0.854751,0.913702,0.832648,0.85435,0.900393,0.033853,0.852642,0.894486,0.031247,0.048167

In [20]:
np.random.seed (1)
dframe1 = pd.DataFrame(columns=['Accuracy', 'Std_Dev'])

for i in range(1, 101):
    print(i)
    df2 = df1.groupby('APPRDX').apply(lambda x: x.sample(80))
    X = df2.drop('APPRDX', axis = 1)
    y = df2['APPRDX']
    random_forest_model = RandomForestClassifier(n_estimators = 100, max_depth = 5, criterion = 'gini')
    scores = cross_val_score(random_forest_model, X, y, cv = 10, n_jobs = -1)
    mean_score = scores.mean()
    print(f'Mean accuracy: {mean_score}')
    new_row = {'Accuracy': mean_score, 'Std_Dev': std(scores)}
    dframe1 = pd.concat([dframe1, pd.DataFrame(new_row, index=[0])], ignore_index=True)

1
Mean accuracy: 0.5625
2
Mean accuracy: 0.63125
3
Mean accuracy: 0.6375
4
Mean accuracy: 0.60625
5
Mean accuracy: 0.65
6
Mean accuracy: 0.61875
7
Mean accuracy: 0.65625
8
Mean accuracy: 0.6375
9
Mean accuracy: 0.65625
10
Mean accuracy: 0.61875
11
Mean accuracy: 0.65
12
Mean accuracy: 0.675
13
Mean accuracy: 0.6875
14
Mean accuracy: 0.64375
15
Mean accuracy: 0.63125
16
Mean accuracy: 0.7
17
Mean accuracy: 0.66875
18
Mean accuracy: 0.6625
19
Mean accuracy: 0.56875
20
Mean accuracy: 0.65
21
Mean accuracy: 0.6125
22
Mean accuracy: 0.58125
23
Mean accuracy: 0.6625
24
Mean accuracy: 0.7
25
Mean accuracy: 0.6125
26
Mean accuracy: 0.7
27
Mean accuracy: 0.6625
28
Mean accuracy: 0.61875
29
Mean accuracy: 0.6375
30
Mean accuracy: 0.6
31
Mean accuracy: 0.69375
32
Mean accuracy: 0.7
33
Mean accuracy: 0.64375
34
Mean accuracy: 0.6625
35
Mean accuracy: 0.7
36
Mean accuracy: 0.6875
37
Mean accuracy: 0.64375
38
Mean accuracy: 0.65
39
Mean accuracy: 0.675
40
Mean accuracy: 0.6
41
Mean accuracy: 0.675
42
Mean accuracy: 0.675
43
Mean accuracy: 0.675
44
Mean accuracy: 0.675
45
Mean accuracy: 0.675
46
Mean accuracy: 0.65
47
Mean accuracy: 0.63125
48
Mean accuracy: 0.675
49
Mean accuracy: 0.65625
50
Mean accuracy: 0.66875
51
Mean accuracy: 0.65
52
Mean accuracy: 0.63125
53
Mean accuracy: 0.625
54
Mean accuracy: 0.6125
55
Mean accuracy: 0.625
56
Mean accuracy: 0.6
57
Mean accuracy: 0.61875
58
Mean accuracy: 0.625
59
Mean accuracy: 0.65
60
Mean accuracy: 0.6875
61
Mean accuracy: 0.7
62
Mean accuracy: 0.60625
63
Mean accuracy: 0.60625
64
Mean accuracy: 0.6375
65
Mean accuracy: 0.65625
66
Mean accuracy: 0.625
67
Mean accuracy: 0.6375
68
Mean accuracy: 0.65
69
Mean accuracy: 0.5875
70
Mean accuracy: 0.58125
71
Mean accuracy: 0.6
72
Mean accuracy: 0.66875
73
Mean accuracy: 0.68125
74
Mean accuracy: 0.63125
75
Mean accuracy: 0.66875
76
Mean accuracy: 0.6125
77
Mean accuracy: 0.68125
78
Mean accuracy: 0.68125
79
Mean accuracy: 0.63125
80
Mean accuracy: 0.59375
81
Mean accuracy: 0.65625
82
Mean accuracy: 0.675
83
Mean accuracy: 0.63125
84
Mean accuracy: 0.65
85
Mean accuracy: 0.63125
86
Mean accuracy: 0.6375
87
Mean accuracy: 0.6
88
Mean accuracy: 0.66875
89
Mean accuracy: 0.66875
90
Mean accuracy: 0.63125
91
Mean accuracy: 0.675
92
Mean accuracy: 0.6125
93
Mean accuracy: 0.625
94
Mean accuracy: 0.69375
95
Mean accuracy: 0.6625
96
Mean accuracy: 0.6375
97
Mean accuracy: 0.6125
98
Mean accuracy: 0.64375
99
Mean accuracy: 0.6375
100
Mean accuracy: 0.65625

In [21]:
print(mean(dframe1['Accuracy']))
dframe1.to_csv ("Apathy_Top50sCpG89_100RF.csv", index = False)

0.6448125000000001