# Random Forest Classification

In [1]:
import random
import numpy as np
import pandas as pd
import seaborn as sn
from numpy import std
from numpy import mean
import matplotlib.pyplot as plt
from sklearn.datasets import make_classification
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.model_selection import RepeatedStratifiedKFold
from sklearn.metrics import confusion_matrix, accuracy_score
%matplotlib inline

## All CpG

In [2]:
%cd Z:\PPMI_Data\Excels\NonMotors\Derived250\Female\GeneCpG\Constipation
df = pd.read_csv('ConstipationCateg_Methylome_Female.csv')
print(df.shape)
df.head(3)

Z:\PPMI_Data\Excels\NonMotors\Derived250\Female\GeneCpG\Constipation
(150, 20758)

,Unnamed: 0,Sentrix,PATNO,HYS,Gender,APPRDX,MDSP_Constipate,cg13609937,cg13847987,cg13822231,...,cg06819251,cg22158158,cg20161227,cg05701765,cg25437180,cg06002203,cg21722170,cg13142750,cg12743359,cg04293703
0,214,200991620021_R03C01,3002,2,2,1,1,0.022266,0.939755,0.011179,...,0.913934,0.883586,0.946774,0.814700,0.642126,0.912947,0.870158,0.698537,0.871932,0.573198
1,215,200989060105_R03C01,3003,2,2,1,1,0.023747,0.954997,0.009352,...,0.923224,0.867354,0.969337,0.852062,0.694741,0.861585,0.764911,0.633921,0.823493,0.545910
2,216,200989060162_R04C01,3006,2,2,1,0,0.014894,0.966488,0.008085,...,0.904417,0.913206,0.975067,0.898309,0.665055,0.836574,0.826838,0.671315,0.890298,0.510879

In [3]:
df1 = df.drop(['Unnamed: 0','Sentrix','PATNO','HYS', 'Gender','MDSP_Constipate'], axis=1)
df1.head(2)

,APPRDX,cg13609937,cg13847987,cg13822231,cg20728472,cg14567798,cg14205952,cg13083110,cg24453271,cg18015632,...,cg06819251,cg22158158,cg20161227,cg05701765,cg25437180,cg06002203,cg21722170,cg13142750,cg12743359,cg04293703
0,1,0.022266,0.939755,0.011179,0.018786,0.018662,0.011471,0.587818,0.783724,0.827664,...,0.913934,0.883586,0.946774,0.814700,0.642126,0.912947,0.870158,0.698537,0.871932,0.573198
1,1,0.023747,0.954997,0.009352,0.034445,0.014196,0.009332,0.506270,0.809293,0.900723,...,0.923224,0.867354,0.969337,0.852062,0.694741,0.861585,0.764911,0.633921,0.823493,0.545910

In [4]:
np.random.seed (1)
dframe1 = pd.DataFrame(columns=['Accuracy', 'Std_Dev'])

for i in range(1, 101):
    print(i)
    df2 = df1.groupby('APPRDX').apply(lambda x: x.sample(30))
    X = df2.drop('APPRDX', axis = 1)
    y = df2['APPRDX']
    random_forest_model = RandomForestClassifier(n_estimators = 100, max_depth = 5, criterion = 'gini')
    scores = cross_val_score(random_forest_model, X, y, cv = 10, n_jobs = -1)
    mean_score = scores.mean()
    print(f'Mean accuracy: {mean_score}')
    new_row = {'Accuracy': mean_score, 'Std_Dev': std(scores)}
    dframe1 = pd.concat([dframe1, pd.DataFrame(new_row, index=[0])], ignore_index=True)

1
Mean accuracy: 0.55
2
Mean accuracy: 0.55
3
Mean accuracy: 0.4833333333333333
4
Mean accuracy: 0.4833333333333333
5
Mean accuracy: 0.4833333333333333
6
Mean accuracy: 0.4666666666666666
7
Mean accuracy: 0.4666666666666666
8
Mean accuracy: 0.6166666666666666
9
Mean accuracy: 0.65
10
Mean accuracy: 0.4666666666666666
11
Mean accuracy: 0.4666666666666666
12
Mean accuracy: 0.4833333333333333
13
Mean accuracy: 0.5166666666666667
14
Mean accuracy: 0.4833333333333333
15
Mean accuracy: 0.6
16
Mean accuracy: 0.4833333333333332
17
Mean accuracy: 0.6166666666666666
18
Mean accuracy: 0.5166666666666667
19
Mean accuracy: 0.55
20
Mean accuracy: 0.5
21
Mean accuracy: 0.5333333333333334
22
Mean accuracy: 0.4833333333333333
23
Mean accuracy: 0.5166666666666666
24
Mean accuracy: 0.45
25
Mean accuracy: 0.5666666666666667
26
Mean accuracy: 0.5
27
Mean accuracy: 0.5333333333333333
28
Mean accuracy: 0.5666666666666667
29
Mean accuracy: 0.5833333333333334
30
Mean accuracy: 0.5
31
Mean accuracy: 0.5833333333333333
32
Mean accuracy: 0.5666666666666667
33
Mean accuracy: 0.6
34
Mean accuracy: 0.29999999999999993
35
Mean accuracy: 0.55
36
Mean accuracy: 0.41666666666666663
37
Mean accuracy: 0.5499999999999999
38
Mean accuracy: 0.36666666666666664
39
Mean accuracy: 0.5166666666666666
40
Mean accuracy: 0.55
41
Mean accuracy: 0.5166666666666667
42
Mean accuracy: 0.5333333333333334
43
Mean accuracy: 0.5999999999999999
44
Mean accuracy: 0.5333333333333333
45
Mean accuracy: 0.6166666666666668
46
Mean accuracy: 0.5
47
Mean accuracy: 0.6
48
Mean accuracy: 0.6
49
Mean accuracy: 0.5833333333333333
50
Mean accuracy: 0.55
51
Mean accuracy: 0.5166666666666666
52
Mean accuracy: 0.4833333333333333
53
Mean accuracy: 0.4499999999999999
54
Mean accuracy: 0.5666666666666667
55
Mean accuracy: 0.55
56
Mean accuracy: 0.65
57
Mean accuracy: 0.5166666666666667
58
Mean accuracy: 0.55
59
Mean accuracy: 0.5666666666666667
60
Mean accuracy: 0.4833333333333334
61
Mean accuracy: 0.5666666666666667
62
Mean accuracy: 0.4833333333333334
63
Mean accuracy: 0.6
64
Mean accuracy: 0.6
65
Mean accuracy: 0.5666666666666667
66
Mean accuracy: 0.55
67
Mean accuracy: 0.55
68
Mean accuracy: 0.36666666666666664
69
Mean accuracy: 0.41666666666666663
70
Mean accuracy: 0.5666666666666667
71
Mean accuracy: 0.55
72
Mean accuracy: 0.55
73
Mean accuracy: 0.35
74
Mean accuracy: 0.45
75
Mean accuracy: 0.5166666666666667
76
Mean accuracy: 0.6
77
Mean accuracy: 0.4333333333333333
78
Mean accuracy: 0.5666666666666667
79
Mean accuracy: 0.5666666666666667
80
Mean accuracy: 0.5666666666666667
81
Mean accuracy: 0.6166666666666666
82
Mean accuracy: 0.43333333333333324
83
Mean accuracy: 0.41666666666666663
84
Mean accuracy: 0.5833333333333333
85
Mean accuracy: 0.5833333333333333
86
Mean accuracy: 0.4166666666666667
87
Mean accuracy: 0.55
88
Mean accuracy: 0.38333333333333336
89
Mean accuracy: 0.55
90
Mean accuracy: 0.5666666666666667
91
Mean accuracy: 0.5666666666666667
92
Mean accuracy: 0.5666666666666667
93
Mean accuracy: 0.5666666666666667
94
Mean accuracy: 0.5166666666666666
95
Mean accuracy: 0.5833333333333333
96
Mean accuracy: 0.6
97
Mean accuracy: 0.4
98
Mean accuracy: 0.5166666666666666
99
Mean accuracy: 0.33333333333333337
100
Mean accuracy: 0.5333333333333333

In [5]:
print(mean(dframe1['Accuracy']))
dframe1.to_csv ("Constipation_AllCpG_Female_100RF.csv", index = False)

0.5233333333333335

## RanFor 1000 times. Samples = 50

In [6]:
df2 = df1.drop (['APPRDX'], axis=1)

In [7]:
np.random.seed (1)
dframe1 = pd.DataFrame(columns=['Accuracy', 'Std_Dev'])
for i in range (1,101) :
        print(i)
        df3 = df2.sample(50, axis=1)
        df3 = df3.reindex(['APPRDX', *df3.columns], axis=1).assign(APPRDX=df1['APPRDX'])
        dataset = df3.groupby('APPRDX').apply(lambda x: x.sample(30))
        X = dataset.iloc[:, 1:].values
        y = dataset.iloc[:, 0].values
        random_forest_model = RandomForestClassifier(n_estimators = 100, max_depth = 5, criterion = 'gini')
        scores = cross_val_score(random_forest_model, X, y, cv = 10, n_jobs = -1)
        mean_score = scores.mean()
        print(f'Mean accuracy: {mean_score}')
        new_row = {'Accuracy': mean_score, 'Std_Dev': std(scores)}
        dframe1 = pd.concat([dframe1, pd.DataFrame(new_row, index=[0])], ignore_index=True)

1
Mean accuracy: 0.5
2
Mean accuracy: 0.4333333333333333
3
Mean accuracy: 0.4
4
Mean accuracy: 0.55
5
Mean accuracy: 0.4999999999999999
6
Mean accuracy: 0.5666666666666667
7
Mean accuracy: 0.5666666666666667
8
Mean accuracy: 0.3666666666666666
9
Mean accuracy: 0.5
10
Mean accuracy: 0.5833333333333333
11
Mean accuracy: 0.6166666666666666
12
Mean accuracy: 0.5833333333333334
13
Mean accuracy: 0.6166666666666667
14
Mean accuracy: 0.4333333333333333
15
Mean accuracy: 0.5666666666666667
16
Mean accuracy: 0.45
17
Mean accuracy: 0.39999999999999997
18
Mean accuracy: 0.5499999999999999
19
Mean accuracy: 0.5
20
Mean accuracy: 0.4333333333333334
21
Mean accuracy: 0.5333333333333334
22
Mean accuracy: 0.55
23
Mean accuracy: 0.6333333333333332
24
Mean accuracy: 0.5666666666666667
25
Mean accuracy: 0.45
26
Mean accuracy: 0.5000000000000001
27
Mean accuracy: 0.4833333333333333
28
Mean accuracy: 0.5166666666666666
29
Mean accuracy: 0.4499999999999999
30
Mean accuracy: 0.5833333333333333
31
Mean accuracy: 0.5833333333333334
32
Mean accuracy: 0.5666666666666667
33
Mean accuracy: 0.6333333333333334
34
Mean accuracy: 0.41666666666666663
35
Mean accuracy: 0.41666666666666663
36
Mean accuracy: 0.5166666666666666
37
Mean accuracy: 0.4666666666666667
38
Mean accuracy: 0.4833333333333333
39
Mean accuracy: 0.6
40
Mean accuracy: 0.55
41
Mean accuracy: 0.5666666666666667
42
Mean accuracy: 0.39999999999999997
43
Mean accuracy: 0.5
44
Mean accuracy: 0.5833333333333334
45
Mean accuracy: 0.4666666666666666
46
Mean accuracy: 0.5333333333333334
47
Mean accuracy: 0.5333333333333333
48
Mean accuracy: 0.5833333333333334
49
Mean accuracy: 0.55
50
Mean accuracy: 0.5166666666666666
51
Mean accuracy: 0.4666666666666667
52
Mean accuracy: 0.4833333333333333
53
Mean accuracy: 0.6666666666666666
54
Mean accuracy: 0.45
55
Mean accuracy: 0.4833333333333333
56
Mean accuracy: 0.45
57
Mean accuracy: 0.6666666666666667
58
Mean accuracy: 0.5
59
Mean accuracy: 0.6
60
Mean accuracy: 0.4833333333333332
61
Mean accuracy: 0.5666666666666667
62
Mean accuracy: 0.5166666666666667
63
Mean accuracy: 0.5166666666666667
64
Mean accuracy: 0.45
65
Mean accuracy: 0.4499999999999999
66
Mean accuracy: 0.5999999999999999
67
Mean accuracy: 0.4999999999999999
68
Mean accuracy: 0.5833333333333333
69
Mean accuracy: 0.5166666666666667
70
Mean accuracy: 0.5166666666666667
71
Mean accuracy: 0.41666666666666663
72
Mean accuracy: 0.6
73
Mean accuracy: 0.43333333333333324
74
Mean accuracy: 0.39999999999999997
75
Mean accuracy: 0.5166666666666667
76
Mean accuracy: 0.5166666666666666
77
Mean accuracy: 0.5833333333333333
78
Mean accuracy: 0.5833333333333334
79
Mean accuracy: 0.6166666666666667
80
Mean accuracy: 0.5
81
Mean accuracy: 0.6833333333333333
82
Mean accuracy: 0.4333333333333333
83
Mean accuracy: 0.5333333333333333
84
Mean accuracy: 0.4
85
Mean accuracy: 0.36666666666666664
86
Mean accuracy: 0.38333333333333336
87
Mean accuracy: 0.4666666666666667
88
Mean accuracy: 0.6166666666666667
89
Mean accuracy: 0.4666666666666667
90
Mean accuracy: 0.6333333333333334
91
Mean accuracy: 0.6000000000000001
92
Mean accuracy: 0.45
93
Mean accuracy: 0.6166666666666666
94
Mean accuracy: 0.55
95
Mean accuracy: 0.45
96
Mean accuracy: 0.5166666666666667
97
Mean accuracy: 0.55
98
Mean accuracy: 0.4666666666666666
99
Mean accuracy: 0.41666666666666663
100
Mean accuracy: 0.5333333333333332

In [8]:
print(mean(dframe1['Accuracy']))
dframe1.to_csv ("Constipation_Rand50CpG_Female_100RF.csv", index = False)

0.5161666666666667

## RanFor 100 times. Samples = 98

In [9]:
np.random.seed (1)
dframe1 = pd.DataFrame(columns=['Accuracy', 'Std_Dev'])
for i in range (1,101) :
        print(i)
        df3 = df2.sample(98, axis=1)
        df3 = df3.reindex(['APPRDX', *df3.columns], axis=1).assign(APPRDX=df1['APPRDX'])
        dataset = df3.groupby('APPRDX').apply(lambda x: x.sample(30))
        X = dataset.iloc[:, 1:].values
        y = dataset.iloc[:, 0].values
        random_forest_model = RandomForestClassifier(n_estimators = 100, max_depth = 5, criterion = 'gini')
        scores = cross_val_score(random_forest_model, X, y, cv = 10, n_jobs = -1)
        mean_score = scores.mean()
        print(f'Mean accuracy: {mean_score}')
        new_row = {'Accuracy': mean_score, 'Std_Dev': std(scores)}
        dframe1 = pd.concat([dframe1, pd.DataFrame(new_row, index=[0])], ignore_index=True)

1
Mean accuracy: 0.5666666666666667
2
Mean accuracy: 0.4499999999999999
3
Mean accuracy: 0.45
4
Mean accuracy: 0.55
5
Mean accuracy: 0.55
6
Mean accuracy: 0.6
7
Mean accuracy: 0.5166666666666666
8
Mean accuracy: 0.45
9
Mean accuracy: 0.5833333333333333
10
Mean accuracy: 0.5166666666666666
11
Mean accuracy: 0.6333333333333333
12
Mean accuracy: 0.6000000000000001
13
Mean accuracy: 0.65
14
Mean accuracy: 0.4833333333333334
15
Mean accuracy: 0.55
16
Mean accuracy: 0.4666666666666667
17
Mean accuracy: 0.39999999999999997
18
Mean accuracy: 0.6
19
Mean accuracy: 0.5333333333333332
20
Mean accuracy: 0.4833333333333333
21
Mean accuracy: 0.45
22
Mean accuracy: 0.5
23
Mean accuracy: 0.6166666666666667
24
Mean accuracy: 0.4
25
Mean accuracy: 0.4499999999999999
26
Mean accuracy: 0.5666666666666667
27
Mean accuracy: 0.4833333333333333
28
Mean accuracy: 0.5333333333333333
29
Mean accuracy: 0.5166666666666666
30
Mean accuracy: 0.6166666666666666
31
Mean accuracy: 0.5666666666666667
32
Mean accuracy: 0.55
33
Mean accuracy: 0.6666666666666666
34
Mean accuracy: 0.4833333333333333
35
Mean accuracy: 0.41666666666666663
36
Mean accuracy: 0.45
37
Mean accuracy: 0.41666666666666663
38
Mean accuracy: 0.5666666666666667
39
Mean accuracy: 0.5333333333333333
40
Mean accuracy: 0.5666666666666667
41
Mean accuracy: 0.5666666666666667
42
Mean accuracy: 0.4666666666666668
43
Mean accuracy: 0.5666666666666667
44
Mean accuracy: 0.6166666666666667
45
Mean accuracy: 0.4999999999999999
46
Mean accuracy: 0.5833333333333333
47
Mean accuracy: 0.6166666666666667
48
Mean accuracy: 0.5
49
Mean accuracy: 0.5833333333333333
50
Mean accuracy: 0.5
51
Mean accuracy: 0.5333333333333333
52
Mean accuracy: 0.5999999999999999
53
Mean accuracy: 0.6666666666666666
54
Mean accuracy: 0.39999999999999997
55
Mean accuracy: 0.4666666666666666
56
Mean accuracy: 0.4333333333333333
57
Mean accuracy: 0.6333333333333333
58
Mean accuracy: 0.5666666666666667
59
Mean accuracy: 0.5333333333333333
60
Mean accuracy: 0.55
61
Mean accuracy: 0.5333333333333334
62
Mean accuracy: 0.6333333333333334
63
Mean accuracy: 0.5833333333333333
64
Mean accuracy: 0.4666666666666667
65
Mean accuracy: 0.55
66
Mean accuracy: 0.5833333333333333
67
Mean accuracy: 0.4833333333333333
68
Mean accuracy: 0.5333333333333333
69
Mean accuracy: 0.55
70
Mean accuracy: 0.4833333333333333
71
Mean accuracy: 0.4666666666666666
72
Mean accuracy: 0.5666666666666667
73
Mean accuracy: 0.45
74
Mean accuracy: 0.38333333333333336
75
Mean accuracy: 0.5166666666666667
76
Mean accuracy: 0.4333333333333333
77
Mean accuracy: 0.5499999999999999
78
Mean accuracy: 0.5833333333333334
79
Mean accuracy: 0.5666666666666667
80
Mean accuracy: 0.5833333333333333
81
Mean accuracy: 0.5833333333333333
82
Mean accuracy: 0.6333333333333334
83
Mean accuracy: 0.6166666666666667
84
Mean accuracy: 0.4499999999999999
85
Mean accuracy: 0.39999999999999997
86
Mean accuracy: 0.41666666666666663
87
Mean accuracy: 0.4833333333333333
88
Mean accuracy: 0.5333333333333334
89
Mean accuracy: 0.41666666666666663
90
Mean accuracy: 0.5833333333333333
91
Mean accuracy: 0.55
92
Mean accuracy: 0.5666666666666667
93
Mean accuracy: 0.5833333333333333
94
Mean accuracy: 0.4333333333333334
95
Mean accuracy: 0.4333333333333334
96
Mean accuracy: 0.4333333333333333
97
Mean accuracy: 0.5499999999999999
98
Mean accuracy: 0.5166666666666667
99
Mean accuracy: 0.45
100
Mean accuracy: 0.5166666666666666

In [10]:
print(mean(dframe1['Accuracy']))
dframe1.to_csv ("Constipation_Rand98CpG_Female_100RF.csv", index = False)

0.5251666666666667

## RanFor Top 50 Boruta 100 times. Samples = 50

In [11]:
df = pd.read_csv('Constipation_Boruta_Top50_Data_Female.csv')
print(df.shape)
df.head(2)

(150, 52)

,PATNO,APPRDX,cg14270890,cg22237213,cg06630567,cg26856497,cg23565749,cg12413242,cg24784310,cg04359365,...,cg18258770,cg15454710,cg13365781,cg19878200,cg23814714,cg06173919,cg16694455,cg19458274,cg20641425,cg11712482
0,3002,1,0.905918,0.911791,0.930482,0.906581,0.033449,0.686040,0.140557,0.085721,...,0.066482,0.831087,0.014288,0.123791,0.879547,0.938525,0.907496,0.015144,0.611551,0.426216
1,3003,1,0.903949,0.932302,0.926093,0.889148,0.037335,0.703256,0.115134,0.199964,...,0.073510,0.885725,0.014145,0.104146,0.900867,0.958519,0.908508,0.015374,0.744868,0.431001

In [12]:
df1 = df.drop(['PATNO'], axis=1)
df1.head(2)

,APPRDX,cg14270890,cg22237213,cg06630567,cg26856497,cg23565749,cg12413242,cg24784310,cg04359365,cg00265238,...,cg18258770,cg15454710,cg13365781,cg19878200,cg23814714,cg06173919,cg16694455,cg19458274,cg20641425,cg11712482
0,1,0.905918,0.911791,0.930482,0.906581,0.033449,0.686040,0.140557,0.085721,0.036745,...,0.066482,0.831087,0.014288,0.123791,0.879547,0.938525,0.907496,0.015144,0.611551,0.426216
1,1,0.903949,0.932302,0.926093,0.889148,0.037335,0.703256,0.115134,0.199964,0.037143,...,0.073510,0.885725,0.014145,0.104146,0.900867,0.958519,0.908508,0.015374,0.744868,0.431001

In [13]:
np.random.seed (1)
dframe1 = pd.DataFrame(columns=['Accuracy', 'Std_Dev'])

for i in range(1, 101):
    print(i)
    df2 = df1.groupby('APPRDX').apply(lambda x: x.sample(30))
    X = df2.drop('APPRDX', axis = 1)
    y = df2['APPRDX']
    random_forest_model = RandomForestClassifier(n_estimators = 100, max_depth = 5, criterion = 'gini')
    scores = cross_val_score(random_forest_model, X, y, cv = 10, n_jobs = -1)
    mean_score = scores.mean()
    print(f'Mean accuracy: {mean_score}')
    new_row = {'Accuracy': mean_score, 'Std_Dev': std(scores)}
    dframe1 = pd.concat([dframe1, pd.DataFrame(new_row, index=[0])], ignore_index=True)

1
Mean accuracy: 0.7333333333333333
2
Mean accuracy: 0.7666666666666667
3
Mean accuracy: 0.6500000000000001
4
Mean accuracy: 0.7
5
Mean accuracy: 0.6666666666666666
6
Mean accuracy: 0.7666666666666666
7
Mean accuracy: 0.6833333333333333
8
Mean accuracy: 0.8166666666666668
9
Mean accuracy: 0.7833333333333333
10
Mean accuracy: 0.7000000000000001
11
Mean accuracy: 0.75
12
Mean accuracy: 0.7499999999999999
13
Mean accuracy: 0.7166666666666667
14
Mean accuracy: 0.7333333333333334
15
Mean accuracy: 0.7333333333333333
16
Mean accuracy: 0.7166666666666667
17
Mean accuracy: 0.6833333333333333
18
Mean accuracy: 0.75
19
Mean accuracy: 0.7666666666666666
20
Mean accuracy: 0.7
21
Mean accuracy: 0.6666666666666667
22
Mean accuracy: 0.7166666666666666
23
Mean accuracy: 0.7666666666666668
24
Mean accuracy: 0.6666666666666667
25
Mean accuracy: 0.8166666666666668
26
Mean accuracy: 0.7666666666666666
27
Mean accuracy: 0.7333333333333334
28
Mean accuracy: 0.6166666666666667
29
Mean accuracy: 0.7499999999999999
30
Mean accuracy: 0.7333333333333332
31
Mean accuracy: 0.7666666666666667
32
Mean accuracy: 0.7166666666666666
33
Mean accuracy: 0.7666666666666666
34
Mean accuracy: 0.75
35
Mean accuracy: 0.7666666666666667
36
Mean accuracy: 0.7333333333333333
37
Mean accuracy: 0.6500000000000001
38
Mean accuracy: 0.6499999999999999
39
Mean accuracy: 0.6833333333333333
40
Mean accuracy: 0.7333333333333333
41
Mean accuracy: 0.6833333333333333
42
Mean accuracy: 0.75
43
Mean accuracy: 0.7833333333333333
44
Mean accuracy: 0.7000000000000001
45
Mean accuracy: 0.7333333333333333
46
Mean accuracy: 0.7166666666666666
47
Mean accuracy: 0.6833333333333333
48
Mean accuracy: 0.75
49
Mean accuracy: 0.7666666666666666
50
Mean accuracy: 0.7666666666666667
51
Mean accuracy: 0.7333333333333334
52
Mean accuracy: 0.7166666666666666
53
Mean accuracy: 0.7333333333333334
54
Mean accuracy: 0.8166666666666667
55
Mean accuracy: 0.7166666666666668
56
Mean accuracy: 0.7333333333333333
57
Mean accuracy: 0.7666666666666666
58
Mean accuracy: 0.7166666666666666
59
Mean accuracy: 0.7
60
Mean accuracy: 0.85
61
Mean accuracy: 0.7166666666666666
62
Mean accuracy: 0.6833333333333333
63
Mean accuracy: 0.7
64
Mean accuracy: 0.6333333333333334
65
Mean accuracy: 0.7333333333333334
66
Mean accuracy: 0.6333333333333333
67
Mean accuracy: 0.7
68
Mean accuracy: 0.6166666666666666
69
Mean accuracy: 0.7666666666666667
70
Mean accuracy: 0.75
71
Mean accuracy: 0.6833333333333333
72
Mean accuracy: 0.7833333333333333
73
Mean accuracy: 0.5833333333333333
74
Mean accuracy: 0.8333333333333333
75
Mean accuracy: 0.75
76
Mean accuracy: 0.7666666666666667
77
Mean accuracy: 0.7166666666666667
78
Mean accuracy: 0.7166666666666668
79
Mean accuracy: 0.6666666666666667
80
Mean accuracy: 0.75
81
Mean accuracy: 0.7499999999999999
82
Mean accuracy: 0.7666666666666667
83
Mean accuracy: 0.75
84
Mean accuracy: 0.6166666666666667
85
Mean accuracy: 0.7499999999999999
86
Mean accuracy: 0.7499999999999999
87
Mean accuracy: 0.6666666666666667
88
Mean accuracy: 0.7
89
Mean accuracy: 0.6333333333333333
90
Mean accuracy: 0.7333333333333333
91
Mean accuracy: 0.7666666666666667
92
Mean accuracy: 0.6833333333333333
93
Mean accuracy: 0.7333333333333333
94
Mean accuracy: 0.7833333333333333
95
Mean accuracy: 0.6666666666666666
96
Mean accuracy: 0.7
97
Mean accuracy: 0.6833333333333333
98
Mean accuracy: 0.7333333333333333
99
Mean accuracy: 0.6166666666666667
100
Mean accuracy: 0.75

In [14]:
print(mean(dframe1['Accuracy']))
dframe1.to_csv ("Constipation_Boruta50CpG_Female_100RF.csv", index = False)

0.7225000000000001

## RanFor Top 50 NMI 100 times. Samples = 50

In [15]:
df = pd.read_csv('NMI_Top50_Constipation_Methylome_Female.csv')
print(df.shape)
df.head(2)

(150, 52)

,PATNO,APPRDX,cg14268784,cg22136726,cg00335286,cg20080383,cg17594730,cg03166896,cg21409615,cg09351848,...,cg19402876,cg07857267,cg06838963,cg15657588,cg20170632,cg12103037,cg00140813,cg19238390,cg18862481,cg04152151
0,3002,1,0.752473,0.699776,0.650353,0.644179,0.905597,0.941780,0.882367,0.864516,...,0.908583,0.891956,0.828953,0.475535,0.863334,0.088004,0.023514,0.822136,0.016866,0.877233
1,3003,1,0.742175,0.667122,0.708811,0.461084,0.937221,0.937959,0.893561,0.855371,...,0.932988,0.913486,0.819469,0.490711,0.756304,0.079265,0.013589,0.846568,0.015620,0.779324

In [16]:
df1 = df.drop(['PATNO'], axis=1)
df1.head(2)

,APPRDX,cg14268784,cg22136726,cg00335286,cg20080383,cg17594730,cg03166896,cg21409615,cg09351848,cg01493658,...,cg19402876,cg07857267,cg06838963,cg15657588,cg20170632,cg12103037,cg00140813,cg19238390,cg18862481,cg04152151
0,1,0.752473,0.699776,0.650353,0.644179,0.905597,0.941780,0.882367,0.864516,0.024975,...,0.908583,0.891956,0.828953,0.475535,0.863334,0.088004,0.023514,0.822136,0.016866,0.877233
1,1,0.742175,0.667122,0.708811,0.461084,0.937221,0.937959,0.893561,0.855371,0.018995,...,0.932988,0.913486,0.819469,0.490711,0.756304,0.079265,0.013589,0.846568,0.015620,0.779324

In [17]:
np.random.seed (1)
dframe1 = pd.DataFrame(columns=['Accuracy', 'Std_Dev'])

for i in range(1, 101):
    print(i)
    df2 = df1.groupby('APPRDX').apply(lambda x: x.sample(30))
    X = df2.drop('APPRDX', axis = 1)
    y = df2['APPRDX']
    random_forest_model = RandomForestClassifier(n_estimators = 100, max_depth = 5, criterion = 'gini')
    scores = cross_val_score(random_forest_model, X, y, cv = 10, n_jobs = -1)
    mean_score = scores.mean()
    print(f'Mean accuracy: {mean_score}')
    new_row = {'Accuracy': mean_score, 'Std_Dev': std(scores)}
    dframe1 = pd.concat([dframe1, pd.DataFrame(new_row, index=[0])], ignore_index=True)

1
Mean accuracy: 0.6833333333333333
2
Mean accuracy: 0.7666666666666667
3
Mean accuracy: 0.75
4
Mean accuracy: 0.7166666666666667
5
Mean accuracy: 0.6333333333333333
6
Mean accuracy: 0.7333333333333333
7
Mean accuracy: 0.6666666666666667
8
Mean accuracy: 0.7333333333333334
9
Mean accuracy: 0.8333333333333334
10
Mean accuracy: 0.6833333333333333
11
Mean accuracy: 0.7
12
Mean accuracy: 0.6166666666666667
13
Mean accuracy: 0.7666666666666666
14
Mean accuracy: 0.6833333333333332
15
Mean accuracy: 0.7333333333333333
16
Mean accuracy: 0.6666666666666667
17
Mean accuracy: 0.75
18
Mean accuracy: 0.7333333333333333
19
Mean accuracy: 0.6666666666666666
20
Mean accuracy: 0.75
21
Mean accuracy: 0.7166666666666666
22
Mean accuracy: 0.7333333333333334
23
Mean accuracy: 0.8
24
Mean accuracy: 0.6166666666666667
25
Mean accuracy: 0.6833333333333333
26
Mean accuracy: 0.7
27
Mean accuracy: 0.7333333333333334
28
Mean accuracy: 0.6666666666666667
29
Mean accuracy: 0.7
30
Mean accuracy: 0.7
31
Mean accuracy: 0.75
32
Mean accuracy: 0.7166666666666666
33
Mean accuracy: 0.7166666666666667
34
Mean accuracy: 0.7833333333333333
35
Mean accuracy: 0.7166666666666667
36
Mean accuracy: 0.6166666666666667
37
Mean accuracy: 0.6833333333333333
38
Mean accuracy: 0.6833333333333333
39
Mean accuracy: 0.7333333333333333
40
Mean accuracy: 0.7
41
Mean accuracy: 0.65
42
Mean accuracy: 0.6833333333333333
43
Mean accuracy: 0.7666666666666667
44
Mean accuracy: 0.7166666666666666
45
Mean accuracy: 0.7666666666666668
46
Mean accuracy: 0.7500000000000001
47
Mean accuracy: 0.7333333333333333
48
Mean accuracy: 0.6833333333333333
49
Mean accuracy: 0.6
50
Mean accuracy: 0.6833333333333332
51
Mean accuracy: 0.7333333333333333
52
Mean accuracy: 0.6666666666666667
53
Mean accuracy: 0.65
54
Mean accuracy: 0.7
55
Mean accuracy: 0.8
56
Mean accuracy: 0.7333333333333334
57
Mean accuracy: 0.65
58
Mean accuracy: 0.7333333333333333
59
Mean accuracy: 0.7833333333333332
60
Mean accuracy: 0.6666666666666666
61
Mean accuracy: 0.65
62
Mean accuracy: 0.65
63
Mean accuracy: 0.7333333333333334
64
Mean accuracy: 0.7666666666666667
65
Mean accuracy: 0.7333333333333332
66
Mean accuracy: 0.7333333333333333
67
Mean accuracy: 0.7
68
Mean accuracy: 0.7166666666666667
69
Mean accuracy: 0.6833333333333333
70
Mean accuracy: 0.7166666666666667
71
Mean accuracy: 0.6833333333333333
72
Mean accuracy: 0.7333333333333333
73
Mean accuracy: 0.7500000000000001
74
Mean accuracy: 0.7333333333333333
75
Mean accuracy: 0.8166666666666667
76
Mean accuracy: 0.7999999999999999
77
Mean accuracy: 0.7
78
Mean accuracy: 0.7333333333333334
79
Mean accuracy: 0.6333333333333334
80
Mean accuracy: 0.7166666666666667
81
Mean accuracy: 0.7499999999999999
82
Mean accuracy: 0.7166666666666667
83
Mean accuracy: 0.7166666666666666
84
Mean accuracy: 0.7666666666666667
85
Mean accuracy: 0.6833333333333333
86
Mean accuracy: 0.7
87
Mean accuracy: 0.8166666666666668
88
Mean accuracy: 0.6166666666666666
89
Mean accuracy: 0.7666666666666667
90
Mean accuracy: 0.6166666666666666
91
Mean accuracy: 0.6833333333333333
92
Mean accuracy: 0.75
93
Mean accuracy: 0.7166666666666668
94
Mean accuracy: 0.7333333333333333
95
Mean accuracy: 0.5833333333333333
96
Mean accuracy: 0.7
97
Mean accuracy: 0.7833333333333334
98
Mean accuracy: 0.6833333333333333
99
Mean accuracy: 0.6166666666666667
100
Mean accuracy: 0.7333333333333333

In [18]:
print(mean(dframe1['Accuracy']))
dframe1.to_csv ("Constipation_NMI50CpG_Female_100RF.csv", index = False)

0.7108333333333333

## RanFor Top 50 Boruta + NMI 100 times. Samples = 98

In [19]:
df = pd.read_csv('Constipation_Top50sMerge_Data_Female.csv')
print(df.shape)
df.head(2)

(150, 100)

,PATNO,APPRDX,cg14268784,cg22136726,cg00335286,cg20080383,cg17594730,cg03166896,cg21409615,cg09351848,...,cg24632646,cg18258770,cg15454710,cg13365781,cg19878200,cg23814714,cg06173919,cg19458274,cg20641425,cg11712482
0,3002,1,0.752473,0.699776,0.650353,0.644179,0.905597,0.941780,0.882367,0.864516,...,0.925054,0.066482,0.831087,0.014288,0.123791,0.879547,0.938525,0.015144,0.611551,0.426216
1,3003,1,0.742175,0.667122,0.708811,0.461084,0.937221,0.937959,0.893561,0.855371,...,0.921383,0.073510,0.885725,0.014145,0.104146,0.900867,0.958519,0.015374,0.744868,0.431001

In [20]:
df1 = df.drop(['PATNO'], axis=1)
df1.head(2)

,APPRDX,cg14268784,cg22136726,cg00335286,cg20080383,cg17594730,cg03166896,cg21409615,cg09351848,cg01493658,...,cg24632646,cg18258770,cg15454710,cg13365781,cg19878200,cg23814714,cg06173919,cg19458274,cg20641425,cg11712482
0,1,0.752473,0.699776,0.650353,0.644179,0.905597,0.941780,0.882367,0.864516,0.024975,...,0.925054,0.066482,0.831087,0.014288,0.123791,0.879547,0.938525,0.015144,0.611551,0.426216
1,1,0.742175,0.667122,0.708811,0.461084,0.937221,0.937959,0.893561,0.855371,0.018995,...,0.921383,0.073510,0.885725,0.014145,0.104146,0.900867,0.958519,0.015374,0.744868,0.431001

In [21]:
np.random.seed (1)
dframe1 = pd.DataFrame(columns=['Accuracy', 'Std_Dev'])

for i in range(1, 101):
    print(i)
    df2 = df1.groupby('APPRDX').apply(lambda x: x.sample(30))
    X = df2.drop('APPRDX', axis = 1)
    y = df2['APPRDX']
    random_forest_model = RandomForestClassifier(n_estimators = 100, max_depth = 5, criterion = 'gini')
    scores = cross_val_score(random_forest_model, X, y, cv = 10, n_jobs = -1)
    mean_score = scores.mean()
    print(f'Mean accuracy: {mean_score}')
    new_row = {'Accuracy': mean_score, 'Std_Dev': std(scores)}
    dframe1 = pd.concat([dframe1, pd.DataFrame(new_row, index=[0])], ignore_index=True)

1
Mean accuracy: 0.6666666666666666
2
Mean accuracy: 0.75
3
Mean accuracy: 0.7
4
Mean accuracy: 0.6666666666666666
5
Mean accuracy: 0.6333333333333333
6
Mean accuracy: 0.7333333333333333
7
Mean accuracy: 0.5833333333333333
8
Mean accuracy: 0.8166666666666667
9
Mean accuracy: 0.8333333333333334
10
Mean accuracy: 0.7500000000000001
11
Mean accuracy: 0.7333333333333334
12
Mean accuracy: 0.7166666666666666
13
Mean accuracy: 0.75
14
Mean accuracy: 0.65
15
Mean accuracy: 0.8333333333333334
16
Mean accuracy: 0.75
17
Mean accuracy: 0.8166666666666668
18
Mean accuracy: 0.7166666666666666
19
Mean accuracy: 0.6666666666666666
20
Mean accuracy: 0.7333333333333333
21
Mean accuracy: 0.7333333333333333
22
Mean accuracy: 0.7333333333333333
23
Mean accuracy: 0.8
24
Mean accuracy: 0.7666666666666666
25
Mean accuracy: 0.7833333333333333
26
Mean accuracy: 0.8333333333333334
27
Mean accuracy: 0.7333333333333333
28
Mean accuracy: 0.6666666666666666
29
Mean accuracy: 0.75
30
Mean accuracy: 0.7000000000000001
31
Mean accuracy: 0.75
32
Mean accuracy: 0.7333333333333332
33
Mean accuracy: 0.7166666666666666
34
Mean accuracy: 0.7666666666666667
35
Mean accuracy: 0.7333333333333333
36
Mean accuracy: 0.7
37
Mean accuracy: 0.7166666666666667
38
Mean accuracy: 0.6833333333333333
39
Mean accuracy: 0.7666666666666667
40
Mean accuracy: 0.7166666666666666
41
Mean accuracy: 0.7333333333333333
42
Mean accuracy: 0.7499999999999999
43
Mean accuracy: 0.7666666666666667
44
Mean accuracy: 0.7166666666666667
45
Mean accuracy: 0.7333333333333334
46
Mean accuracy: 0.7
47
Mean accuracy: 0.7666666666666666
48
Mean accuracy: 0.7333333333333333
49
Mean accuracy: 0.6833333333333333
50
Mean accuracy: 0.7166666666666666
51
Mean accuracy: 0.7
52
Mean accuracy: 0.6666666666666667
53
Mean accuracy: 0.6833333333333333
54
Mean accuracy: 0.7833333333333334
55
Mean accuracy: 0.7833333333333334
56
Mean accuracy: 0.7000000000000001
57
Mean accuracy: 0.7
58
Mean accuracy: 0.7333333333333333
59
Mean accuracy: 0.65
60
Mean accuracy: 0.8166666666666668
61
Mean accuracy: 0.7
62
Mean accuracy: 0.7666666666666666
63
Mean accuracy: 0.7
64
Mean accuracy: 0.75
65
Mean accuracy: 0.7833333333333332
66
Mean accuracy: 0.7166666666666666
67
Mean accuracy: 0.7
68
Mean accuracy: 0.6833333333333332
69
Mean accuracy: 0.8
70
Mean accuracy: 0.75
71
Mean accuracy: 0.7166666666666667
72
Mean accuracy: 0.6833333333333333
73
Mean accuracy: 0.6833333333333333
74
Mean accuracy: 0.7666666666666666
75
Mean accuracy: 0.7833333333333333
76
Mean accuracy: 0.7833333333333333
77
Mean accuracy: 0.6499999999999999
78
Mean accuracy: 0.7166666666666667
79
Mean accuracy: 0.65
80
Mean accuracy: 0.75
81
Mean accuracy: 0.75
82
Mean accuracy: 0.6833333333333333
83
Mean accuracy: 0.7333333333333334
84
Mean accuracy: 0.7000000000000001
85
Mean accuracy: 0.8
86
Mean accuracy: 0.7
87
Mean accuracy: 0.75
88
Mean accuracy: 0.7666666666666667
89
Mean accuracy: 0.7499999999999999
90
Mean accuracy: 0.7166666666666667
91
Mean accuracy: 0.7666666666666666
92
Mean accuracy: 0.7500000000000001
93
Mean accuracy: 0.7499999999999999
94
Mean accuracy: 0.7499999999999999
95
Mean accuracy: 0.6666666666666666
96
Mean accuracy: 0.7833333333333334
97
Mean accuracy: 0.8333333333333333
98
Mean accuracy: 0.7833333333333334
99
Mean accuracy: 0.6333333333333334
100
Mean accuracy: 0.7666666666666667

In [22]:
print(mean(dframe1['Accuracy']))
dframe1.to_csv ("Constipation_Top50sCpG98_Female_100RF.csv", index = False)

0.7316666666666666