In [1]:
import pandas as pd

%cd Z:\PPMI_Data\Excels\CollaborativeFiltering
NonMot = pd.read_csv('Feats45_unCategAge_APPRDX.csv')
NonMot1 = NonMot.drop(['PATNO', 'Patient_ID','APPRDX'], axis = 1)
print(NonMot1.shape)
NonMot1.head(2)

Z:\PPMI_Data\Excels\CollaborativeFiltering
(250, 46)

,Age,Anxiety,Apathy,Benton,Clock,Cognition,COGSTATE,Constipate,Depress,DopaDefic,...,Semantic,SleepDay,SleepNight,STAIA,STAIS,Symbol_Digit,Trail_Making_A,Trail_Making_B,UPSIT,Urine
0,67.578082,1,0,12.16,7,1,1,1,1,0,...,57,1,0,45,59,47.5,110,204,17,1
1,46.965716,1,1,7.76,6,1,1,0,0,0,...,36,1,3,40,39,52.0,27,52,9,0

In [2]:
# calculate maximum and minimum values of each column
max_values = NonMot1.max()
min_values = NonMot1.min()

# create a new DataFrame to store the results
result = pd.DataFrame({'max': max_values, 'min': min_values})

# print the result
result.head(11)

                  max        min
Age         83.682192  30.615825
Anxiety      3.000000   0.000000
Apathy       2.000000   0.000000
Benton      16.380000   5.100000
Clock        7.000000   1.000000
Cognition    2.000000   0.000000
COGSTATE     2.000000   1.000000
Constipate   3.000000   0.000000
Depress      4.000000   0.000000
DopaDefic    2.000000   0.000000
Education   26.000000   8.000000

In [3]:
result.to_csv('Feature_MinMaxScores.csv', index=True)

In [4]:
NonMot = pd.read_csv('Feats45_unCategSparse_APPRDX.csv')
NonMot1 = NonMot.drop(['PATNO', 'Patient_ID','APPRDX'], axis = 1)
print(NonMot1.shape)
NonMot1.head(2)

(619, 46)

,Age,Anxiety,Apathy,Benton,Clock,Cognition,COGSTATE,Constipate,Depress,DopaDefic,...,Semantic,SleepDay,SleepNight,STAIA,STAIS,Symbol_Digit,Trail_Making_A,Trail_Making_B,UPSIT,Urine
0,65.142466,1,0,15.46,NaN,0,1.0,0,0,0,...,49,1,0,47,44,48.330002,53.0,90.0,25,4.0
1,67.578082,1,0,12.16,7.0,1,1.0,1,1,0,...,57,1,0,45,59,47.500000,110.0,204.0,17,1.0

In [5]:
max_values = NonMot1.max()
min_values = NonMot1.min()
result = pd.DataFrame({'max': max_values, 'min': min_values})
result.head(11)

                  max        min
Age         84.884033  30.615825
Anxiety      4.000000   0.000000
Apathy       2.000000   0.000000
Benton      17.480000   3.080000
Clock        7.000000   0.000000
Cognition    2.000000   0.000000
COGSTATE     3.000000   1.000000
Constipate   3.000000   0.000000
Depress      4.000000   0.000000
DopaDefic    2.000000   0.000000
Education   26.000000   5.000000

In [6]:
result.to_csv('Feature_onSparseMinMaxScores.csv', index=True)