# Random Forest Classification

## Importing the libraries

In [1]:
import random
import numpy as np
import pandas as pd
import seaborn as sn
from numpy import std
from numpy import mean
import matplotlib.pyplot as plt
from sklearn.datasets import make_classification
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.model_selection import RepeatedStratifiedKFold
from sklearn.metrics import confusion_matrix, accuracy_score
%matplotlib inline

In [2]:
%cd Z:\PPMI_Data\Excels\NonMotors\Derived250\Female\GeneCpG\LexicalFluency
df = pd.read_csv('LexicalFluencyCateg_Methylome_Female.csv')
print(df.shape)
df.head(2)

Z:\PPMI_Data\Excels\NonMotors\Derived250\Female\GeneCpG\LexicalFluency
(75, 85923)

,Sentrix,PATNO,Gender,APPRDX,HYS,Age,AgeCate,Lexical_Fluency_Category,cg02315971,cg24133836,...,cg12092065,cg10388349,cg11918957,cg26583598,cg11023075,cg02097667,cg21616723,cg27335855,cg18259253,cg15404040
0,200973410159_R03C01,3000,2,2,0,69.1,4,1,0.030109,0.016106,...,0.953091,0.392056,0.913402,0.913637,0.897198,0.871237,0.913624,0.651860,0.852542,0.909412
1,200991620021_R03C01,3002,2,1,2,67.6,4,1,0.025308,0.017806,...,0.921575,0.416247,0.864819,0.942005,0.907732,0.869391,0.907648,0.834695,0.842573,0.917446

In [3]:
df1 = df.drop(['PATNO', 'Sentrix', 'HYS', 'Gender', 'Lexical_Fluency_Category','Age','AgeCate'], axis=1)
print(df1.shape)
df1.head(2)

(75, 85916)

,APPRDX,cg02315971,cg24133836,cg03286969,cg11738782,cg25741731,cg24629744,cg23836745,cg11685489,cg06081147,...,cg12092065,cg10388349,cg11918957,cg26583598,cg11023075,cg02097667,cg21616723,cg27335855,cg18259253,cg15404040
0,2,0.030109,0.016106,0.019371,0.884151,0.026326,0.868373,0.905809,0.825562,0.691096,...,0.953091,0.392056,0.913402,0.913637,0.897198,0.871237,0.913624,0.651860,0.852542,0.909412
1,1,0.025308,0.017806,0.014377,0.862173,0.025717,0.888906,0.906743,0.861073,0.661539,...,0.921575,0.416247,0.864819,0.942005,0.907732,0.869391,0.907648,0.834695,0.842573,0.917446

## RanFor 100 times, CpG only

In [4]:
np.random.seed (1)
dframe1 = pd.DataFrame(columns=['Accuracy', 'Std_Dev'])
for i in range (1,101) :
        print(i)
        dataset = df1.groupby('APPRDX').apply(lambda x: x.sample(20))
        X = dataset.iloc[:, 1:].values
        y = dataset.iloc[:, 0].values
        classifier = RandomForestClassifier(n_estimators = 100, criterion = 'entropy', random_state = 1)
        cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=1, random_state=1)
        n_scores = cross_val_score(classifier, X, y, scoring='accuracy', cv=cv, n_jobs=-1, error_score='raise')
        dframe1 = dframe1.append({'Accuracy': mean(n_scores), 'Std_Dev': std(n_scores)}, ignore_index=True)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100

In [5]:
dframe1.to_csv ("LexicalFluency_AllCpG_Accuracy_100RF.csv", index=False)

In [6]:
dframe1.head(2)

   Accuracy  Std_Dev
0     0.675    0.275
1     0.550    0.150

## RanFor 1000 times. Samples = 50

In [7]:
df2 = df1.drop (['APPRDX'], axis=1)

In [8]:
np.random.seed (1)
dframe1 = pd.DataFrame(columns=['Accuracy', 'Std_Dev'])
for i in range (1,101) :
        print(i)
        df3 = df2.sample(50, axis=1)
        df3 = df3.reindex(['APPRDX', *df3.columns], axis=1).assign(APPRDX=df1['APPRDX'])
        dataset = df3.groupby('APPRDX').apply(lambda x: x.sample(20))
        X = dataset.iloc[:, 1:].values
        y = dataset.iloc[:, 0].values
        classifier = RandomForestClassifier(n_estimators = 100, criterion = 'entropy', random_state = 1)
        cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=1, random_state=1)
        n_scores = cross_val_score(classifier, X, y, scoring='accuracy', cv=cv, n_jobs=-1, error_score='raise')
        dframe1 = dframe1.append({'Accuracy': mean(n_scores), 'Std_Dev': std(n_scores)}, ignore_index=True)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100

In [9]:
print(dframe1.head(3))
dframe1.to_csv ("LexicalFluency_Rand50CpG_100RF.csv")

   Accuracy   Std_Dev
0     0.625  0.230489
1     0.650  0.200000
2     0.600  0.165831

## RanFor 1000 times. Samples = 15

In [10]:
np.random.seed (1)
dframe2 = pd.DataFrame(columns=['Accuracy', 'Std_Dev'])
for i in range (1,101) :
        print(i)
        df3 = df2.sample(15, axis=1)
        df3 = df3.reindex(['APPRDX', *df3.columns], axis=1).assign(APPRDX=df1['APPRDX'])
        dataset = df3.groupby('APPRDX').apply(lambda x: x.sample(20))
        X = dataset.iloc[:, 1:].values
        y = dataset.iloc[:, 0].values
        classifier = RandomForestClassifier(n_estimators = 100, criterion = 'entropy', random_state = 1)
        cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=1, random_state=1)
        n_scores = cross_val_score(classifier, X, y, scoring='accuracy', cv=cv, n_jobs=-1, error_score='raise')
        dframe2 = dframe2.append({'Accuracy': mean(n_scores), 'Std_Dev': std(n_scores)}, ignore_index=True)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100

In [11]:
print(dframe1.head(3))
dframe1.to_csv ("LexicalFluency_Rand15CpG_100RF.csv")

   Accuracy   Std_Dev
0     0.625  0.230489
1     0.650  0.200000
2     0.600  0.165831

# NMI Top 50

In [12]:
df = pd.read_csv('Top50NMI_LexicalFluency_Female_Data.csv')
print(df.shape)
df.head(3)

(75, 52)

,PATNO,APPRDX,cg26111030,cg17605629,cg06480636,cg13901712,cg22190754,cg20717075,cg15000071,cg22707381,...,cg14265043,cg13852784,cg15706539,cg13263383,cg26632873,cg12060713,cg26510634,cg17592376,cg15206555,cg18498684
0,3000,2,0.027015,0.726750,0.629698,0.891398,0.383983,0.424800,0.550229,0.611164,...,0.932129,0.668282,0.792878,0.135516,0.011142,0.061573,0.828260,0.836170,0.861547,0.925725
1,3002,1,0.017736,0.668591,0.677090,0.863390,0.765749,0.612856,0.570055,0.668208,...,0.927390,0.698859,0.825159,0.078536,0.010213,0.050524,0.870167,0.873275,0.843785,0.856255
2,3003,1,0.034908,0.678999,0.660692,0.868010,0.833971,0.783968,0.556621,0.626078,...,0.947759,0.667061,0.726704,0.032036,0.010167,0.073414,0.835431,0.874345,0.778228,0.913142

In [13]:
df1 = df.drop(['PATNO'], axis=1)
df1.head(2)

,APPRDX,cg26111030,cg17605629,cg06480636,cg13901712,cg22190754,cg20717075,cg15000071,cg22707381,cg18804921,...,cg14265043,cg13852784,cg15706539,cg13263383,cg26632873,cg12060713,cg26510634,cg17592376,cg15206555,cg18498684
0,2,0.027015,0.726750,0.629698,0.891398,0.383983,0.424800,0.550229,0.611164,0.841155,...,0.932129,0.668282,0.792878,0.135516,0.011142,0.061573,0.828260,0.836170,0.861547,0.925725
1,1,0.017736,0.668591,0.677090,0.863390,0.765749,0.612856,0.570055,0.668208,0.870984,...,0.927390,0.698859,0.825159,0.078536,0.010213,0.050524,0.870167,0.873275,0.843785,0.856255

In [14]:
np.random.seed (1)
dframe1 = pd.DataFrame(columns=['Accuracy', 'Std_Dev'])
for i in range (1,101) :
        print(i)
        dataset = df1.groupby('APPRDX').apply(lambda x: x.sample(20))
        X = dataset.iloc[:, 1:].values
        y = dataset.iloc[:, 0].values
        classifier = RandomForestClassifier(n_estimators = 100, criterion = 'entropy', random_state = 1)
        cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=5, random_state=1)
        n_scores = cross_val_score(classifier, X, y, scoring='accuracy', cv=cv, n_jobs=-1, error_score='raise')
        dframe1 = dframe1.append({'Accuracy': mean(n_scores), 'Std_Dev': std(n_scores)}, ignore_index=True)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100

In [15]:
print(dframe1.head(2))
dframe1.to_csv ("LexicalFluency_NMICpG_100RF.csv")

   Accuracy   Std_Dev
0     0.900  0.141421
1     0.835  0.191115

# Boruta Top 50

In [16]:
df = pd.read_csv('Top50Boruta_LexicalFluency_Female_Data.csv')
print(df.shape)
df.head(3)

(75, 52)

,PATNO,APPRDX,cg06632027,cg23677000,cg02471166,cg02451730,cg03644025,cg06019273,cg10769891,cg21088420,...,cg14410319,cg25158734,cg05302035,cg00337440,cg11543740,cg20546928,cg25126016,cg18295068,cg12942009,cg02320740
0,3000,2,0.043348,0.198972,0.601775,0.022587,0.868069,0.835377,0.031391,0.159974,...,0.087773,0.282774,0.866670,0.609358,0.928531,0.053702,0.887791,0.077857,0.907575,0.019762
1,3002,1,0.025609,0.196651,0.734715,0.017709,0.853484,0.835399,0.015638,0.164491,...,0.078954,0.286004,0.888044,0.554657,0.905266,0.042847,0.940108,0.052616,0.919997,0.024096
2,3003,1,0.026290,0.204988,0.718823,0.018384,0.817852,0.873231,0.015852,0.180256,...,0.064126,0.294334,0.858995,0.636999,0.884232,0.030363,0.920627,0.074936,0.912444,0.024365

In [17]:
df1 = df.drop(['PATNO'], axis=1)
df1.head(2)

,APPRDX,cg06632027,cg23677000,cg02471166,cg02451730,cg03644025,cg06019273,cg10769891,cg21088420,cg10253929,...,cg14410319,cg25158734,cg05302035,cg00337440,cg11543740,cg20546928,cg25126016,cg18295068,cg12942009,cg02320740
0,2,0.043348,0.198972,0.601775,0.022587,0.868069,0.835377,0.031391,0.159974,0.027381,...,0.087773,0.282774,0.866670,0.609358,0.928531,0.053702,0.887791,0.077857,0.907575,0.019762
1,1,0.025609,0.196651,0.734715,0.017709,0.853484,0.835399,0.015638,0.164491,0.019520,...,0.078954,0.286004,0.888044,0.554657,0.905266,0.042847,0.940108,0.052616,0.919997,0.024096

In [18]:
np.random.seed (1)
dframe1 = pd.DataFrame(columns=['Accuracy', 'Std_Dev'])
for i in range (1,101) :
        print(i)
        dataset = df1.groupby('APPRDX').apply(lambda x: x.sample(20))
        X = dataset.iloc[:, 1:].values
        y = dataset.iloc[:, 0].values
        classifier = RandomForestClassifier(n_estimators = 100, criterion = 'entropy', random_state = 1)
        cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=5, random_state=1)
        n_scores = cross_val_score(classifier, X, y, scoring='accuracy', cv=cv, n_jobs=-1, error_score='raise')
        dframe1 = dframe1.append({'Accuracy': mean(n_scores), 'Std_Dev': std(n_scores)}, ignore_index=True)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100

In [19]:
print(dframe1.head(2))
dframe1.to_csv ("LexicalFluency_BorutaCpG_100RF.csv")

   Accuracy   Std_Dev
0      0.88  0.151987
1      0.82  0.180555

# BorutaR

In [2]:
%cd Z:\PPMI_Data\Excels\NonMotors\Derived250\Female\GeneCpG\LexicalFluency
df = pd.read_csv('BorutaR_LexicalFluency_Female_CpG.csv')
print(df.shape)
df.head(3)

Z:\PPMI_Data\Excels\NonMotors\Derived250\Female\GeneCpG\LexicalFluency
(75, 41)

,PATNO,APPRDX,cg12511331,cg22552084,cg03357721,cg26632873,cg13040886,cg17414718,cg05596698,cg04398983,...,cg06480636,cg00422267,cg04582295,cg03983726,cg14478495,cg05524387,cg23905638,cg12906589,ch.21.664518F,cg05382797
0,3000,2,0.863643,0.813674,0.846083,0.011142,0.181648,0.856309,0.835721,0.086594,...,0.629698,0.921720,0.822861,0.976932,0.079537,0.866867,0.649672,0.831329,0.089775,0.023748
1,3002,1,0.768467,0.815722,0.797132,0.010213,0.323011,0.908134,0.829359,0.048404,...,0.677090,0.911813,0.801689,0.976549,0.018098,0.899621,0.614659,0.881764,0.053289,0.027251
2,3003,1,0.809496,0.787378,0.755281,0.010167,0.240343,0.921888,0.858929,0.083015,...,0.660692,0.900590,0.857237,0.976534,0.018181,0.856454,0.624340,0.900044,0.055758,0.029957

In [3]:
df1 = df.drop(['PATNO'], axis=1)
df1.head(2)

,APPRDX,cg12511331,cg22552084,cg03357721,cg26632873,cg13040886,cg17414718,cg05596698,cg04398983,cg02933993,...,cg06480636,cg00422267,cg04582295,cg03983726,cg14478495,cg05524387,cg23905638,cg12906589,ch.21.664518F,cg05382797
0,2,0.863643,0.813674,0.846083,0.011142,0.181648,0.856309,0.835721,0.086594,0.723011,...,0.629698,0.921720,0.822861,0.976932,0.079537,0.866867,0.649672,0.831329,0.089775,0.023748
1,1,0.768467,0.815722,0.797132,0.010213,0.323011,0.908134,0.829359,0.048404,0.583824,...,0.677090,0.911813,0.801689,0.976549,0.018098,0.899621,0.614659,0.881764,0.053289,0.027251

In [4]:
np.random.seed (1)
dframe1 = pd.DataFrame(columns=['Accuracy', 'Std_Dev'])
for i in range (1,101) :
        print(i)
        dataset = df1.groupby('APPRDX').apply(lambda x: x.sample(20))
        X = dataset.iloc[:, 1:].values
        y = dataset.iloc[:, 0].values
        classifier = RandomForestClassifier(n_estimators = 100, criterion = 'entropy', random_state = 1)
        cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=5, random_state=1)
        n_scores = cross_val_score(classifier, X, y, scoring='accuracy', cv=cv, n_jobs=-1, error_score='raise')
        dframe1 = dframe1.append({'Accuracy': mean(n_scores), 'Std_Dev': std(n_scores)}, ignore_index=True)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100

In [5]:
print(dframe1.head(2))
dframe1.to_csv ("LexicalFluency_Female_BorutaRCpG_100RF.csv")

   Accuracy   Std_Dev
0     0.825  0.195256
1     0.780  0.215870

# Common CpG

In [23]:
df = pd.read_csv('Common15_LexicalFluency_Data_Female.csv')
print(df.shape)
df.head(3)

(75, 17)

,PATNO,APPRDX,cg02933993,cg04294383,cg04451259,cg05302035,cg05382797,cg06480636,cg06632027,cg07433663,cg10253929,cg10769891,cg17990657,cg18795825,cg21088420,cg25158734,cg26632873
0,3000,2,0.723011,0.921624,0.835350,0.866670,0.023748,0.629698,0.043348,0.088087,0.027381,0.031391,0.572508,0.025923,0.159974,0.282774,0.011142
1,3002,1,0.583824,0.893732,0.764024,0.888044,0.027251,0.677090,0.025609,0.064613,0.019520,0.015638,0.548622,0.026647,0.164491,0.286004,0.010213
2,3003,1,0.655206,0.904422,0.809877,0.858995,0.029957,0.660692,0.026290,0.062986,0.024756,0.015852,0.587842,0.017492,0.180256,0.294334,0.010167

In [24]:
df1 = df.drop(['PATNO'], axis=1)
df1.head(2)

,APPRDX,cg02933993,cg04294383,cg04451259,cg05302035,cg05382797,cg06480636,cg06632027,cg07433663,cg10253929,cg10769891,cg17990657,cg18795825,cg21088420,cg25158734,cg26632873
0,2,0.723011,0.921624,0.835350,0.866670,0.023748,0.629698,0.043348,0.088087,0.027381,0.031391,0.572508,0.025923,0.159974,0.282774,0.011142
1,1,0.583824,0.893732,0.764024,0.888044,0.027251,0.677090,0.025609,0.064613,0.019520,0.015638,0.548622,0.026647,0.164491,0.286004,0.010213

In [25]:
np.random.seed (1)
dframe1 = pd.DataFrame(columns=['Accuracy', 'Std_Dev'])
for i in range (1,101) :
        print(i)
        dataset = df1.groupby('APPRDX').apply(lambda x: x.sample(20))
        X = dataset.iloc[:, 1:].values
        y = dataset.iloc[:, 0].values
        classifier = RandomForestClassifier(n_estimators = 100, criterion = 'entropy', random_state = 1)
        cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=5, random_state=1)
        n_scores = cross_val_score(classifier, X, y, scoring='accuracy', cv=cv, n_jobs=-1, error_score='raise')
        dframe1 = dframe1.append({'Accuracy': mean(n_scores), 'Std_Dev': std(n_scores)}, ignore_index=True)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100

In [26]:
print(dframe1.head(2))
dframe1.to_csv ("LexicalFluency_Female_Common15CpG_100RF.csv")

   Accuracy   Std_Dev
0      0.89  0.167033
1      0.83  0.169115