# Random Forest Classification

In [1]:
import random
import numpy as np
import pandas as pd
import seaborn as sn
from numpy import std
from numpy import mean
import matplotlib.pyplot as plt
from sklearn.datasets import make_classification
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.model_selection import RepeatedStratifiedKFold
from sklearn.metrics import confusion_matrix, accuracy_score
%matplotlib inline

## NMI

In [2]:
%cd Z:\PPMI_Data\Excels\NonMotors\Derived250\GeneCpG\LexicalFluency
df = pd.read_csv('Top50NMI_LexicalFluency_Data.csv')
print(df.shape)
df.head(3)

Z:\PPMI_Data\Excels\NonMotors\Derived250\GeneCpG\LexicalFluency
(233, 52)

,PATNO,APPRDX,cg18504826,cg24706032,cg04958915,cg23983141,cg04310833,cg12184854,cg08550831,cg08096908,...,cg25045630,cg07956247,cg17287767,cg13739582,cg06173919,cg00379002,cg25361663,cg01083159,cg01219549,cg14478495
0,3000,2,0.923461,0.013061,0.953291,0.873134,0.919058,0.935107,0.926300,0.937764,...,0.925686,0.950869,0.027357,0.661946,0.920101,0.070987,0.922851,0.285636,0.978548,0.079537
1,3001,1,0.912524,0.014550,0.912131,0.863465,0.914570,0.933108,0.907085,0.905542,...,0.896759,0.954344,0.030067,0.581498,0.906110,0.081577,0.911043,0.323545,0.975563,0.018922
2,3002,1,0.924475,0.011182,0.934635,0.880092,0.925335,0.939486,0.937941,0.936556,...,0.907252,0.965318,0.028958,0.664156,0.938525,0.054870,0.909074,0.369534,0.970690,0.018098

In [3]:
df1 = df.drop(['PATNO'], axis=1)
df1.head(2)

,APPRDX,cg18504826,cg24706032,cg04958915,cg23983141,cg04310833,cg12184854,cg08550831,cg08096908,cg15355127,...,cg25045630,cg07956247,cg17287767,cg13739582,cg06173919,cg00379002,cg25361663,cg01083159,cg01219549,cg14478495
0,2,0.923461,0.013061,0.953291,0.873134,0.919058,0.935107,0.926300,0.937764,0.685666,...,0.925686,0.950869,0.027357,0.661946,0.920101,0.070987,0.922851,0.285636,0.978548,0.079537
1,1,0.912524,0.014550,0.912131,0.863465,0.914570,0.933108,0.907085,0.905542,0.676244,...,0.896759,0.954344,0.030067,0.581498,0.906110,0.081577,0.911043,0.323545,0.975563,0.018922

In [4]:
np.random.seed (1)
dframe1 = pd.DataFrame(columns=['Accuracy', 'Std_Dev'])
for i in range (1,101) :
        print(i)
        dataset = df1.groupby('APPRDX').apply(lambda x: x.sample(60))
        X = dataset.iloc[:, 1:].values
        y = dataset.iloc[:, 0].values
        classifier = RandomForestClassifier(n_estimators = 100, criterion = 'entropy', random_state = 1)
        cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=5, random_state=1)
        n_scores = cross_val_score(classifier, X, y, scoring='accuracy', cv=cv, n_jobs=-1, error_score='raise')
        dframe1 = dframe1.append({'Accuracy': mean(n_scores), 'Std_Dev': std(n_scores)}, ignore_index=True)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100

In [5]:
print(dframe1.head(2))
dframe1.to_csv ("LexicalFluency_NMICpG_100RF.csv")

   Accuracy   Std_Dev
0  0.718333  0.132172
1  0.728333  0.121117

## Boruta

In [6]:
df = pd.read_csv('Top50Boruta_LexicalFluency_Data.csv')
print(df.shape)
df.head(3)

(233, 52)

,PATNO,APPRDX,cg21507882,cg13546658,cg26725638,cg09304381,ch.22.78028F,cg25513853,cg26869617,cg09670616,...,cg09671015,cg13648501,cg03397659,cg08810486,cg15247645,cg25689730,cg00892798,cg26211126,cg06004734,cg10399719
0,3000,2,0.031090,0.232474,0.882607,0.981877,0.031958,0.887706,0.923248,0.017773,...,0.833174,0.048405,0.816637,0.446588,0.019462,0.011273,0.039366,0.967684,0.912588,0.020254
1,3001,1,0.029286,0.164460,0.896464,0.960567,0.032447,0.905946,0.906871,0.031018,...,0.827930,0.045928,0.683608,0.028135,0.016190,0.012957,0.058593,0.960001,0.904207,0.019902
2,3002,1,0.025906,0.286757,0.900922,0.959723,0.026469,0.926980,0.896811,0.021487,...,0.800614,0.048304,0.724759,0.420296,0.012782,0.009241,0.042979,0.963367,0.921960,0.017725

In [7]:
df1 = df.drop(['PATNO'], axis=1)
df1.head(2)

,APPRDX,cg21507882,cg13546658,cg26725638,cg09304381,ch.22.78028F,cg25513853,cg26869617,cg09670616,cg27038439,...,cg09671015,cg13648501,cg03397659,cg08810486,cg15247645,cg25689730,cg00892798,cg26211126,cg06004734,cg10399719
0,2,0.031090,0.232474,0.882607,0.981877,0.031958,0.887706,0.923248,0.017773,0.887488,...,0.833174,0.048405,0.816637,0.446588,0.019462,0.011273,0.039366,0.967684,0.912588,0.020254
1,1,0.029286,0.164460,0.896464,0.960567,0.032447,0.905946,0.906871,0.031018,0.759094,...,0.827930,0.045928,0.683608,0.028135,0.016190,0.012957,0.058593,0.960001,0.904207,0.019902

In [8]:
np.random.seed (1)
dframe1 = pd.DataFrame(columns=['Accuracy', 'Std_Dev'])
for i in range (1,101) :
        print(i)
        dataset = df1.groupby('APPRDX').apply(lambda x: x.sample(60))
        X = dataset.iloc[:, 1:].values
        y = dataset.iloc[:, 0].values
        classifier = RandomForestClassifier(n_estimators = 100, criterion = 'entropy', random_state = 1)
        cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=5, random_state=1)
        n_scores = cross_val_score(classifier, X, y, scoring='accuracy', cv=cv, n_jobs=-1, error_score='raise')
        dframe1 = dframe1.append({'Accuracy': mean(n_scores), 'Std_Dev': std(n_scores)}, ignore_index=True)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100

In [9]:
print(dframe1.head(2))
dframe1.to_csv ("LexicalFluency_BorutaCpG_100RF.csv")

   Accuracy   Std_Dev
0  0.655000  0.134381
1  0.646667  0.121974

## BorutaR

In [10]:
df = pd.read_csv('BorutaR_LexicalFluency_CpG.csv')
print(df.shape)
df.head(3)

(233, 10)

,PATNO,APPRDX,cg04001014,cg03691812,cg18504826,ch.14.1421228R,cg17217677,cg18223453,cg02618319,cg25911279
0,3000,2,0.036511,0.037567,0.923461,0.020897,0.831306,0.732237,0.981089,0.035425
1,3001,1,0.038820,0.039701,0.912524,0.025722,0.746003,0.727934,0.977055,0.031463
2,3002,1,0.042524,0.026869,0.924475,0.015331,0.798021,0.780938,0.980235,0.024504

In [11]:
df1 = df.drop(['PATNO'], axis=1)
df1.head(2)

,APPRDX,cg04001014,cg03691812,cg18504826,ch.14.1421228R,cg17217677,cg18223453,cg02618319,cg25911279
0,2,0.036511,0.037567,0.923461,0.020897,0.831306,0.732237,0.981089,0.035425
1,1,0.038820,0.039701,0.912524,0.025722,0.746003,0.727934,0.977055,0.031463

In [12]:
np.random.seed (1)
dframe1 = pd.DataFrame(columns=['Accuracy', 'Std_Dev'])
for i in range (1,101) :
        print(i)
        dataset = df1.groupby('APPRDX').apply(lambda x: x.sample(60))
        X = dataset.iloc[:, 1:].values
        y = dataset.iloc[:, 0].values
        classifier = RandomForestClassifier(n_estimators = 100, criterion = 'entropy', random_state = 1)
        cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=5, random_state=1)
        n_scores = cross_val_score(classifier, X, y, scoring='accuracy', cv=cv, n_jobs=-1, error_score='raise')
        dframe1 = dframe1.append({'Accuracy': mean(n_scores), 'Std_Dev': std(n_scores)}, ignore_index=True)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100

In [13]:
print(dframe1.head(2))
dframe1.to_csv ("LexicalFluency_BorutaRCpG_100RF.csv")

   Accuracy   Std_Dev
0      0.67  0.141382
1      0.67  0.129056

## Common

In [15]:
df = pd.read_csv('Common5_Lexical_Data.csv')
print(df.shape)
df.head(3)

(233, 7)

   PATNO  APPRDX  cg02471166  cg11492856  cg04001014  cg02618319  cg18504826
0   3000       2    0.601775    0.921944    0.036511    0.981089    0.923461
1   3001       1    0.804546    0.911869    0.038820    0.977055    0.912524
2   3002       1    0.734715    0.927646    0.042524    0.980235    0.924475

In [16]:
df1 = df.drop(['PATNO'], axis=1)
df1.head(2)

   APPRDX  cg02471166  cg11492856  cg04001014  cg02618319  cg18504826
0       2    0.601775    0.921944    0.036511    0.981089    0.923461
1       1    0.804546    0.911869    0.038820    0.977055    0.912524

In [17]:
np.random.seed (1)
dframe1 = pd.DataFrame(columns=['Accuracy', 'Std_Dev'])
for i in range (1,101) :
        print(i)
        dataset = df1.groupby('APPRDX').apply(lambda x: x.sample(60))
        X = dataset.iloc[:, 1:].values
        y = dataset.iloc[:, 0].values
        classifier = RandomForestClassifier(n_estimators = 100, criterion = 'entropy', random_state = 1)
        cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=5, random_state=1)
        n_scores = cross_val_score(classifier, X, y, scoring='accuracy', cv=cv, n_jobs=-1, error_score='raise')
        dframe1 = dframe1.append({'Accuracy': mean(n_scores), 'Std_Dev': std(n_scores)}, ignore_index=True)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100

In [18]:
print(dframe1.head(2))
dframe1.to_csv ("LexicalFluency_Common10CpG_100RF.csv")

   Accuracy   Std_Dev
0     0.615  0.145191
1     0.610  0.115998