# Random Forest Classification

In [1]:
import random
import numpy as np
import pandas as pd
import seaborn as sn
from numpy import std
from numpy import mean
import matplotlib.pyplot as plt
from sklearn.datasets import make_classification
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.model_selection import RepeatedStratifiedKFold
from sklearn.metrics import confusion_matrix, accuracy_score
%matplotlib inline

## All CpG

In [2]:
%cd Z:\PPMI_Data\Excels\NonMotors\Derived250\Female\GeneCpG\LexicalFluency
df = pd.read_csv('LexicalFluencyCateg_Methylome_Female.csv')
print(df.shape)
df.head(2)

Z:\PPMI_Data\Excels\NonMotors\Derived250\Female\GeneCpG\LexicalFluency
(75, 85923)

,Sentrix,PATNO,Gender,APPRDX,HYS,Age,AgeCate,Lexical_Fluency_Category,cg02315971,cg24133836,...,cg12092065,cg10388349,cg11918957,cg26583598,cg11023075,cg02097667,cg21616723,cg27335855,cg18259253,cg15404040
0,200973410159_R03C01,3000,2,2,0,69.1,4,1,0.030109,0.016106,...,0.953091,0.392056,0.913402,0.913637,0.897198,0.871237,0.913624,0.651860,0.852542,0.909412
1,200991620021_R03C01,3002,2,1,2,67.6,4,1,0.025308,0.017806,...,0.921575,0.416247,0.864819,0.942005,0.907732,0.869391,0.907648,0.834695,0.842573,0.917446

In [3]:
df1 = df.drop(['Sentrix','PATNO','HYS','Gender','Lexical_Fluency_Category','Age','AgeCate'], axis=1)
df1.head(2)

,APPRDX,cg02315971,cg24133836,cg03286969,cg11738782,cg25741731,cg24629744,cg23836745,cg11685489,cg06081147,...,cg12092065,cg10388349,cg11918957,cg26583598,cg11023075,cg02097667,cg21616723,cg27335855,cg18259253,cg15404040
0,2,0.030109,0.016106,0.019371,0.884151,0.026326,0.868373,0.905809,0.825562,0.691096,...,0.953091,0.392056,0.913402,0.913637,0.897198,0.871237,0.913624,0.651860,0.852542,0.909412
1,1,0.025308,0.017806,0.014377,0.862173,0.025717,0.888906,0.906743,0.861073,0.661539,...,0.921575,0.416247,0.864819,0.942005,0.907732,0.869391,0.907648,0.834695,0.842573,0.917446

In [5]:
np.random.seed (1)
dframe1 = pd.DataFrame(columns=['Accuracy', 'Std_Dev'])

for i in range(1, 101):
    print(i)
    df2 = df1.groupby('APPRDX').apply(lambda x: x.sample(20))
    X = df2.drop('APPRDX', axis = 1)
    y = df2['APPRDX']
    random_forest_model = RandomForestClassifier(n_estimators = 100, max_depth = 5, criterion = 'gini')
    scores = cross_val_score(random_forest_model, X, y, cv = 10, n_jobs = -1)
    mean_score = scores.mean()
    print(f'Mean accuracy: {mean_score}')
    new_row = {'Accuracy': mean_score, 'Std_Dev': std(scores)}
    dframe1 = pd.concat([dframe1, pd.DataFrame(new_row, index=[0])], ignore_index=True)

1
Mean accuracy: 0.625
2
Mean accuracy: 0.65
3
Mean accuracy: 0.575
4
Mean accuracy: 0.625
5
Mean accuracy: 0.625
6
Mean accuracy: 0.55
7
Mean accuracy: 0.725
8
Mean accuracy: 0.625
9
Mean accuracy: 0.65
10
Mean accuracy: 0.55
11
Mean accuracy: 0.575
12
Mean accuracy: 0.6
13
Mean accuracy: 0.7
14
Mean accuracy: 0.65
15
Mean accuracy: 0.55
16
Mean accuracy: 0.7
17
Mean accuracy: 0.65
18
Mean accuracy: 0.65
19
Mean accuracy: 0.575
20
Mean accuracy: 0.575
21
Mean accuracy: 0.625
22
Mean accuracy: 0.6
23
Mean accuracy: 0.525
24
Mean accuracy: 0.475
25
Mean accuracy: 0.675
26
Mean accuracy: 0.575
27
Mean accuracy: 0.65
28
Mean accuracy: 0.625
29
Mean accuracy: 0.625
30
Mean accuracy: 0.55
31
Mean accuracy: 0.575
32
Mean accuracy: 0.65
33
Mean accuracy: 0.65
34
Mean accuracy: 0.5
35
Mean accuracy: 0.7
36
Mean accuracy: 0.65
37
Mean accuracy: 0.55
38
Mean accuracy: 0.625
39
Mean accuracy: 0.575
40
Mean accuracy: 0.7
41
Mean accuracy: 0.575
42
Mean accuracy: 0.575
43
Mean accuracy: 0.65
44
Mean accuracy: 0.675
45
Mean accuracy: 0.525
46
Mean accuracy: 0.575
47
Mean accuracy: 0.575
48
Mean accuracy: 0.65
49
Mean accuracy: 0.6
50
Mean accuracy: 0.65
51
Mean accuracy: 0.7
52
Mean accuracy: 0.625
53
Mean accuracy: 0.475
54
Mean accuracy: 0.7
55
Mean accuracy: 0.75
56
Mean accuracy: 0.6
57
Mean accuracy: 0.75
58
Mean accuracy: 0.6
59
Mean accuracy: 0.675
60
Mean accuracy: 0.725
61
Mean accuracy: 0.65
62
Mean accuracy: 0.675
63
Mean accuracy: 0.625
64
Mean accuracy: 0.675
65
Mean accuracy: 0.675
66
Mean accuracy: 0.475
67
Mean accuracy: 0.625
68
Mean accuracy: 0.575
69
Mean accuracy: 0.775
70
Mean accuracy: 0.65
71
Mean accuracy: 0.55
72
Mean accuracy: 0.65
73
Mean accuracy: 0.6
74
Mean accuracy: 0.55
75
Mean accuracy: 0.65
76
Mean accuracy: 0.75
77
Mean accuracy: 0.6
78
Mean accuracy: 0.625
79
Mean accuracy: 0.625
80
Mean accuracy: 0.675
81
Mean accuracy: 0.475
82
Mean accuracy: 0.575
83
Mean accuracy: 0.725
84
Mean accuracy: 0.575
85
Mean accuracy: 0.65
86
Mean accuracy: 0.675
87
Mean accuracy: 0.6
88
Mean accuracy: 0.675
89
Mean accuracy: 0.65
90
Mean accuracy: 0.575
91
Mean accuracy: 0.5
92
Mean accuracy: 0.625
93
Mean accuracy: 0.7
94
Mean accuracy: 0.575
95
Mean accuracy: 0.725
96
Mean accuracy: 0.625
97
Mean accuracy: 0.625
98
Mean accuracy: 0.6
99
Mean accuracy: 0.6
100
Mean accuracy: 0.625

In [6]:
print(mean(dframe1['Accuracy']))
dframe1.to_csv ("LexicalFluency_AllCpG_Female_100RF.csv", index = False)

0.6222499999999999

## RanFor 1000 times. Samples = 50

In [7]:
df2 = df1.drop (['APPRDX'], axis=1)

In [8]:
np.random.seed (1)
dframe1 = pd.DataFrame(columns=['Accuracy', 'Std_Dev'])
for i in range (1,101) :
        print(i)
        df3 = df2.sample(50, axis=1)
        df3 = df3.reindex(['APPRDX', *df3.columns], axis=1).assign(APPRDX=df1['APPRDX'])
        dataset = df3.groupby('APPRDX').apply(lambda x: x.sample(20))
        X = dataset.iloc[:, 1:].values
        y = dataset.iloc[:, 0].values
        random_forest_model = RandomForestClassifier(n_estimators = 100, max_depth = 5, criterion = 'gini')
        scores = cross_val_score(random_forest_model, X, y, cv = 10, n_jobs = -1)
        mean_score = scores.mean()
        print(f'Mean accuracy: {mean_score}')
        new_row = {'Accuracy': mean_score, 'Std_Dev': std(scores)}
        dframe1 = pd.concat([dframe1, pd.DataFrame(new_row, index=[0])], ignore_index=True)

1
Mean accuracy: 0.575
2
Mean accuracy: 0.6
3
Mean accuracy: 0.55
4
Mean accuracy: 0.675
5
Mean accuracy: 0.625
6
Mean accuracy: 0.65
7
Mean accuracy: 0.575
8
Mean accuracy: 0.65
9
Mean accuracy: 0.575
10
Mean accuracy: 0.65
11
Mean accuracy: 0.625
12
Mean accuracy: 0.725
13
Mean accuracy: 0.55
14
Mean accuracy: 0.65
15
Mean accuracy: 0.65
16
Mean accuracy: 0.55
17
Mean accuracy: 0.575
18
Mean accuracy: 0.65
19
Mean accuracy: 0.8
20
Mean accuracy: 0.65
21
Mean accuracy: 0.65
22
Mean accuracy: 0.675
23
Mean accuracy: 0.55
24
Mean accuracy: 0.675
25
Mean accuracy: 0.575
26
Mean accuracy: 0.7
27
Mean accuracy: 0.75
28
Mean accuracy: 0.475
29
Mean accuracy: 0.6
30
Mean accuracy: 0.55
31
Mean accuracy: 0.6
32
Mean accuracy: 0.65
33
Mean accuracy: 0.75
34
Mean accuracy: 0.675
35
Mean accuracy: 0.675
36
Mean accuracy: 0.475
37
Mean accuracy: 0.55
38
Mean accuracy: 0.775
39
Mean accuracy: 0.75
40
Mean accuracy: 0.6
41
Mean accuracy: 0.5
42
Mean accuracy: 0.7
43
Mean accuracy: 0.55
44
Mean accuracy: 0.625
45
Mean accuracy: 0.775
46
Mean accuracy: 0.5
47
Mean accuracy: 0.525
48
Mean accuracy: 0.55
49
Mean accuracy: 0.6
50
Mean accuracy: 0.625
51
Mean accuracy: 0.6
52
Mean accuracy: 0.55
53
Mean accuracy: 0.475
54
Mean accuracy: 0.6
55
Mean accuracy: 0.575
56
Mean accuracy: 0.55
57
Mean accuracy: 0.475
58
Mean accuracy: 0.55
59
Mean accuracy: 0.6
60
Mean accuracy: 0.625
61
Mean accuracy: 0.55
62
Mean accuracy: 0.5
63
Mean accuracy: 0.65
64
Mean accuracy: 0.7
65
Mean accuracy: 0.75
66
Mean accuracy: 0.5
67
Mean accuracy: 0.5
68
Mean accuracy: 0.75
69
Mean accuracy: 0.6
70
Mean accuracy: 0.6
71
Mean accuracy: 0.625
72
Mean accuracy: 0.55
73
Mean accuracy: 0.7
74
Mean accuracy: 0.725
75
Mean accuracy: 0.525
76
Mean accuracy: 0.575
77
Mean accuracy: 0.6
78
Mean accuracy: 0.55
79
Mean accuracy: 0.55
80
Mean accuracy: 0.525
81
Mean accuracy: 0.6
82
Mean accuracy: 0.625
83
Mean accuracy: 0.5
84
Mean accuracy: 0.425
85
Mean accuracy: 0.6
86
Mean accuracy: 0.5
87
Mean accuracy: 0.675
88
Mean accuracy: 0.5
89
Mean accuracy: 0.625
90
Mean accuracy: 0.525
91
Mean accuracy: 0.5
92
Mean accuracy: 0.7
93
Mean accuracy: 0.6
94
Mean accuracy: 0.5
95
Mean accuracy: 0.75
96
Mean accuracy: 0.675
97
Mean accuracy: 0.525
98
Mean accuracy: 0.65
99
Mean accuracy: 0.65
100
Mean accuracy: 0.625

In [9]:
print(mean(dframe1['Accuracy']))
dframe1.to_csv ("LexicalFluency_Rand50CpG_Female_100RF.csv", index = False)

0.60575

## RanFor 100 times. Samples = 94

In [10]:
np.random.seed (1)
dframe1 = pd.DataFrame(columns=['Accuracy', 'Std_Dev'])
for i in range (1,101) :
        print(i)
        df3 = df2.sample(94, axis=1)
        df3 = df3.reindex(['APPRDX', *df3.columns], axis=1).assign(APPRDX=df1['APPRDX'])
        dataset = df3.groupby('APPRDX').apply(lambda x: x.sample(20))
        X = dataset.iloc[:, 1:].values
        y = dataset.iloc[:, 0].values
        random_forest_model = RandomForestClassifier(n_estimators = 100, max_depth = 5, criterion = 'gini')
        scores = cross_val_score(random_forest_model, X, y, cv = 10, n_jobs = -1)
        mean_score = scores.mean()
        print(f'Mean accuracy: {mean_score}')
        new_row = {'Accuracy': mean_score, 'Std_Dev': std(scores)}
        dframe1 = pd.concat([dframe1, pd.DataFrame(new_row, index=[0])], ignore_index=True)

1
Mean accuracy: 0.625
2
Mean accuracy: 0.525
3
Mean accuracy: 0.575
4
Mean accuracy: 0.65
5
Mean accuracy: 0.525
6
Mean accuracy: 0.65
7
Mean accuracy: 0.6
8
Mean accuracy: 0.65
9
Mean accuracy: 0.5
10
Mean accuracy: 0.5
11
Mean accuracy: 0.6
12
Mean accuracy: 0.775
13
Mean accuracy: 0.625
14
Mean accuracy: 0.65
15
Mean accuracy: 0.55
16
Mean accuracy: 0.6
17
Mean accuracy: 0.6
18
Mean accuracy: 0.6
19
Mean accuracy: 0.675
20
Mean accuracy: 0.625
21
Mean accuracy: 0.65
22
Mean accuracy: 0.575
23
Mean accuracy: 0.65
24
Mean accuracy: 0.7
25
Mean accuracy: 0.575
26
Mean accuracy: 0.75
27
Mean accuracy: 0.7
28
Mean accuracy: 0.6
29
Mean accuracy: 0.65
30
Mean accuracy: 0.55
31
Mean accuracy: 0.625
32
Mean accuracy: 0.625
33
Mean accuracy: 0.625
34
Mean accuracy: 0.6
35
Mean accuracy: 0.8
36
Mean accuracy: 0.525
37
Mean accuracy: 0.625
38
Mean accuracy: 0.65
39
Mean accuracy: 0.625
40
Mean accuracy: 0.6
41
Mean accuracy: 0.55
42
Mean accuracy: 0.6
43
Mean accuracy: 0.6
44
Mean accuracy: 0.625
45
Mean accuracy: 0.825
46
Mean accuracy: 0.55
47
Mean accuracy: 0.575
48
Mean accuracy: 0.5
49
Mean accuracy: 0.675
50
Mean accuracy: 0.675
51
Mean accuracy: 0.6
52
Mean accuracy: 0.6
53
Mean accuracy: 0.55
54
Mean accuracy: 0.55
55
Mean accuracy: 0.575
56
Mean accuracy: 0.5
57
Mean accuracy: 0.525
58
Mean accuracy: 0.65
59
Mean accuracy: 0.65
60
Mean accuracy: 0.625
61
Mean accuracy: 0.65
62
Mean accuracy: 0.45
63
Mean accuracy: 0.55
64
Mean accuracy: 0.725
65
Mean accuracy: 0.65
66
Mean accuracy: 0.55
67
Mean accuracy: 0.575
68
Mean accuracy: 0.7
69
Mean accuracy: 0.65
70
Mean accuracy: 0.6
71
Mean accuracy: 0.675
72
Mean accuracy: 0.625
73
Mean accuracy: 0.675
74
Mean accuracy: 0.75
75
Mean accuracy: 0.55
76
Mean accuracy: 0.675
77
Mean accuracy: 0.625
78
Mean accuracy: 0.5
79
Mean accuracy: 0.575
80
Mean accuracy: 0.6
81
Mean accuracy: 0.6
82
Mean accuracy: 0.525
83
Mean accuracy: 0.45
84
Mean accuracy: 0.525
85
Mean accuracy: 0.575
86
Mean accuracy: 0.55
87
Mean accuracy: 0.525
88
Mean accuracy: 0.475
89
Mean accuracy: 0.575
90
Mean accuracy: 0.6
91
Mean accuracy: 0.525
92
Mean accuracy: 0.675
93
Mean accuracy: 0.55
94
Mean accuracy: 0.675
95
Mean accuracy: 0.675
96
Mean accuracy: 0.6
97
Mean accuracy: 0.65
98
Mean accuracy: 0.65
99
Mean accuracy: 0.625
100
Mean accuracy: 0.625

In [11]:
print(mean(dframe1['Accuracy']))
dframe1.to_csv ("LexicalFluency_Rand94CpG_Female_100RF.csv", index = False)

0.6079999999999999

## RanFor Top 50 Boruta 100 times. Samples = 50

In [12]:
df = pd.read_csv('Top50Boruta_LexicalFluency_Female_Data.csv')
print(df.shape)
df.head(2)

(75, 52)

,PATNO,APPRDX,cg06632027,cg23677000,cg02471166,cg02451730,cg03644025,cg06019273,cg10769891,cg21088420,...,cg14410319,cg25158734,cg05302035,cg00337440,cg11543740,cg20546928,cg25126016,cg18295068,cg12942009,cg02320740
0,3000,2,0.043348,0.198972,0.601775,0.022587,0.868069,0.835377,0.031391,0.159974,...,0.087773,0.282774,0.866670,0.609358,0.928531,0.053702,0.887791,0.077857,0.907575,0.019762
1,3002,1,0.025609,0.196651,0.734715,0.017709,0.853484,0.835399,0.015638,0.164491,...,0.078954,0.286004,0.888044,0.554657,0.905266,0.042847,0.940108,0.052616,0.919997,0.024096

In [13]:
df1 = df.drop(['PATNO'], axis=1)
df1.head(2)

,APPRDX,cg06632027,cg23677000,cg02471166,cg02451730,cg03644025,cg06019273,cg10769891,cg21088420,cg10253929,...,cg14410319,cg25158734,cg05302035,cg00337440,cg11543740,cg20546928,cg25126016,cg18295068,cg12942009,cg02320740
0,2,0.043348,0.198972,0.601775,0.022587,0.868069,0.835377,0.031391,0.159974,0.027381,...,0.087773,0.282774,0.866670,0.609358,0.928531,0.053702,0.887791,0.077857,0.907575,0.019762
1,1,0.025609,0.196651,0.734715,0.017709,0.853484,0.835399,0.015638,0.164491,0.019520,...,0.078954,0.286004,0.888044,0.554657,0.905266,0.042847,0.940108,0.052616,0.919997,0.024096

In [14]:
np.random.seed (1)
dframe1 = pd.DataFrame(columns=['Accuracy', 'Std_Dev'])

for i in range(1, 101):
    print(i)
    df2 = df1.groupby('APPRDX').apply(lambda x: x.sample(20))
    X = df2.drop('APPRDX', axis = 1)
    y = df2['APPRDX']
    random_forest_model = RandomForestClassifier(n_estimators = 100, max_depth = 5, criterion = 'gini')
    scores = cross_val_score(random_forest_model, X, y, cv = 10, n_jobs = -1)
    mean_score = scores.mean()
    print(f'Mean accuracy: {mean_score}')
    new_row = {'Accuracy': mean_score, 'Std_Dev': std(scores)}
    dframe1 = pd.concat([dframe1, pd.DataFrame(new_row, index=[0])], ignore_index=True)

1
Mean accuracy: 0.85
2
Mean accuracy: 0.8
3
Mean accuracy: 0.875
4
Mean accuracy: 0.95
5
Mean accuracy: 0.9
6
Mean accuracy: 0.8
7
Mean accuracy: 0.925
8
Mean accuracy: 0.85
9
Mean accuracy: 0.9
10
Mean accuracy: 0.85
11
Mean accuracy: 0.925
12
Mean accuracy: 0.925
13
Mean accuracy: 0.875
14
Mean accuracy: 0.875
15
Mean accuracy: 0.85
16
Mean accuracy: 0.925
17
Mean accuracy: 0.875
18
Mean accuracy: 0.85
19
Mean accuracy: 0.875
20
Mean accuracy: 0.8
21
Mean accuracy: 0.85
22
Mean accuracy: 0.825
23
Mean accuracy: 0.85
24
Mean accuracy: 0.8
25
Mean accuracy: 0.9
26
Mean accuracy: 0.825
27
Mean accuracy: 0.9
28
Mean accuracy: 0.9
29
Mean accuracy: 0.85
30
Mean accuracy: 0.825
31
Mean accuracy: 0.825
32
Mean accuracy: 0.9
33
Mean accuracy: 0.875
34
Mean accuracy: 0.85
35
Mean accuracy: 0.875
36
Mean accuracy: 0.775
37
Mean accuracy: 0.8
38
Mean accuracy: 0.9
39
Mean accuracy: 0.875
40
Mean accuracy: 0.9
41
Mean accuracy: 0.8
42
Mean accuracy: 0.825
43
Mean accuracy: 0.825
44
Mean accuracy: 0.875
45
Mean accuracy: 0.85
46
Mean accuracy: 0.875
47
Mean accuracy: 0.85
48
Mean accuracy: 0.85
49
Mean accuracy: 0.925
50
Mean accuracy: 0.825
51
Mean accuracy: 0.85
52
Mean accuracy: 0.9
53
Mean accuracy: 0.85
54
Mean accuracy: 0.925
55
Mean accuracy: 0.95
56
Mean accuracy: 0.825
57
Mean accuracy: 0.875
58
Mean accuracy: 0.875
59
Mean accuracy: 0.875
60
Mean accuracy: 0.85
61
Mean accuracy: 0.85
62
Mean accuracy: 0.9
63
Mean accuracy: 0.825
64
Mean accuracy: 0.925
65
Mean accuracy: 0.875
66
Mean accuracy: 0.85
67
Mean accuracy: 0.875
68
Mean accuracy: 0.825
69
Mean accuracy: 1.0
70
Mean accuracy: 0.9
71
Mean accuracy: 0.85
72
Mean accuracy: 0.8
73
Mean accuracy: 0.8
74
Mean accuracy: 0.875
75
Mean accuracy: 0.9
76
Mean accuracy: 0.95
77
Mean accuracy: 0.825
78
Mean accuracy: 0.875
79
Mean accuracy: 0.925
80
Mean accuracy: 0.95
81
Mean accuracy: 0.85
82
Mean accuracy: 0.8
83
Mean accuracy: 0.85
84
Mean accuracy: 0.875
85
Mean accuracy: 0.875
86
Mean accuracy: 0.9
87
Mean accuracy: 0.85
88
Mean accuracy: 0.95
89
Mean accuracy: 0.825
90
Mean accuracy: 0.875
91
Mean accuracy: 0.825
92
Mean accuracy: 0.8
93
Mean accuracy: 0.95
94
Mean accuracy: 0.775
95
Mean accuracy: 0.925
96
Mean accuracy: 0.875
97
Mean accuracy: 0.8
98
Mean accuracy: 0.825
99
Mean accuracy: 0.875
100
Mean accuracy: 0.85

In [15]:
print(mean(dframe1['Accuracy']))
dframe1.to_csv ("LexicalFluency_Boruta50CpG_Female_100RF.csv", index = False)

0.86575

## RanFor Top 50 NMI 100 times. Samples = 50

In [16]:
df = pd.read_csv('Top50NMI_LexicalFluency_Female_Data.csv')
print(df.shape)
df.head(2)

(75, 52)

,PATNO,APPRDX,cg26111030,cg17605629,cg06480636,cg13901712,cg22190754,cg20717075,cg15000071,cg22707381,...,cg14265043,cg13852784,cg15706539,cg13263383,cg26632873,cg12060713,cg26510634,cg17592376,cg15206555,cg18498684
0,3000,2,0.027015,0.726750,0.629698,0.891398,0.383983,0.424800,0.550229,0.611164,...,0.932129,0.668282,0.792878,0.135516,0.011142,0.061573,0.828260,0.836170,0.861547,0.925725
1,3002,1,0.017736,0.668591,0.677090,0.863390,0.765749,0.612856,0.570055,0.668208,...,0.927390,0.698859,0.825159,0.078536,0.010213,0.050524,0.870167,0.873275,0.843785,0.856255

In [17]:
df1 = df.drop(['PATNO'], axis=1)
df1.head(2)

,APPRDX,cg26111030,cg17605629,cg06480636,cg13901712,cg22190754,cg20717075,cg15000071,cg22707381,cg18804921,...,cg14265043,cg13852784,cg15706539,cg13263383,cg26632873,cg12060713,cg26510634,cg17592376,cg15206555,cg18498684
0,2,0.027015,0.726750,0.629698,0.891398,0.383983,0.424800,0.550229,0.611164,0.841155,...,0.932129,0.668282,0.792878,0.135516,0.011142,0.061573,0.828260,0.836170,0.861547,0.925725
1,1,0.017736,0.668591,0.677090,0.863390,0.765749,0.612856,0.570055,0.668208,0.870984,...,0.927390,0.698859,0.825159,0.078536,0.010213,0.050524,0.870167,0.873275,0.843785,0.856255

In [18]:
np.random.seed (1)
dframe1 = pd.DataFrame(columns=['Accuracy', 'Std_Dev'])

for i in range(1, 101):
    print(i)
    df2 = df1.groupby('APPRDX').apply(lambda x: x.sample(20))
    X = df2.drop('APPRDX', axis = 1)
    y = df2['APPRDX']
    random_forest_model = RandomForestClassifier(n_estimators = 100, max_depth = 5, criterion = 'gini')
    scores = cross_val_score(random_forest_model, X, y, cv = 10, n_jobs = -1)
    mean_score = scores.mean()
    print(f'Mean accuracy: {mean_score}')
    new_row = {'Accuracy': mean_score, 'Std_Dev': std(scores)}
    dframe1 = pd.concat([dframe1, pd.DataFrame(new_row, index=[0])], ignore_index=True)

1
Mean accuracy: 0.9
2
Mean accuracy: 0.8
3
Mean accuracy: 0.725
4
Mean accuracy: 0.8
5
Mean accuracy: 0.85
6
Mean accuracy: 0.775
7
Mean accuracy: 0.85
8
Mean accuracy: 0.825
9
Mean accuracy: 0.9
10
Mean accuracy: 0.825
11
Mean accuracy: 0.875
12
Mean accuracy: 0.825
13
Mean accuracy: 0.85
14
Mean accuracy: 0.85
15
Mean accuracy: 0.825
16
Mean accuracy: 0.85
17
Mean accuracy: 0.85
18
Mean accuracy: 0.9
19
Mean accuracy: 0.875
20
Mean accuracy: 0.825
21
Mean accuracy: 0.8
22
Mean accuracy: 0.775
23
Mean accuracy: 0.8
24
Mean accuracy: 0.725
25
Mean accuracy: 0.85
26
Mean accuracy: 0.775
27
Mean accuracy: 0.9
28
Mean accuracy: 0.875
29
Mean accuracy: 0.8
30
Mean accuracy: 0.775
31
Mean accuracy: 0.8
32
Mean accuracy: 0.85
33
Mean accuracy: 0.825
34
Mean accuracy: 0.825
35
Mean accuracy: 0.9
36
Mean accuracy: 0.9
37
Mean accuracy: 0.85
38
Mean accuracy: 0.775
39
Mean accuracy: 0.85
40
Mean accuracy: 0.925
41
Mean accuracy: 0.8
42
Mean accuracy: 0.825
43
Mean accuracy: 0.85
44
Mean accuracy: 0.8
45
Mean accuracy: 0.8
46
Mean accuracy: 0.8
47
Mean accuracy: 0.85
48
Mean accuracy: 0.85
49
Mean accuracy: 0.875
50
Mean accuracy: 0.8
51
Mean accuracy: 0.825
52
Mean accuracy: 0.775
53
Mean accuracy: 0.825
54
Mean accuracy: 0.875
55
Mean accuracy: 0.875
56
Mean accuracy: 0.8
57
Mean accuracy: 0.9
58
Mean accuracy: 0.8
59
Mean accuracy: 0.85
60
Mean accuracy: 0.825
61
Mean accuracy: 0.75
62
Mean accuracy: 0.9
63
Mean accuracy: 0.8
64
Mean accuracy: 0.95
65
Mean accuracy: 0.85
66
Mean accuracy: 0.75
67
Mean accuracy: 0.775
68
Mean accuracy: 0.8
69
Mean accuracy: 0.925
70
Mean accuracy: 0.8
71
Mean accuracy: 0.825
72
Mean accuracy: 0.8
73
Mean accuracy: 0.85
74
Mean accuracy: 0.8
75
Mean accuracy: 0.875
76
Mean accuracy: 0.925
77
Mean accuracy: 0.8
78
Mean accuracy: 0.825
79
Mean accuracy: 0.875
80
Mean accuracy: 0.85
81
Mean accuracy: 0.775
82
Mean accuracy: 0.775
83
Mean accuracy: 0.825
84
Mean accuracy: 0.825
85
Mean accuracy: 0.9
86
Mean accuracy: 0.85
87
Mean accuracy: 0.825
88
Mean accuracy: 0.9
89
Mean accuracy: 0.775
90
Mean accuracy: 0.85
91
Mean accuracy: 0.8
92
Mean accuracy: 0.85
93
Mean accuracy: 0.875
94
Mean accuracy: 0.725
95
Mean accuracy: 0.925
96
Mean accuracy: 0.875
97
Mean accuracy: 0.825
98
Mean accuracy: 0.775
99
Mean accuracy: 0.825
100
Mean accuracy: 0.85

In [19]:
print(mean(dframe1['Accuracy']))
dframe1.to_csv ("LexicalFluency_NMI50CpG_Female_100RF.csv", index = False)

0.8329999999999999

## RanFor Top 50 Boruta + NMI 100 times. Samples = 94

In [20]:
df = pd.read_csv('LexicalFluency_Top50sMerge_Data_Female.csv')
print(df.shape)
df.head(2)

(75, 96)

,PATNO,APPRDX,cg26111030,cg17605629,cg06480636,cg13901712,cg22190754,cg20717075,cg15000071,cg22707381,...,cg10364513,cg14410319,cg25158734,cg00337440,cg11543740,cg20546928,cg25126016,cg18295068,cg12942009,cg02320740
0,3000,2,0.027015,0.726750,0.629698,0.891398,0.383983,0.424800,0.550229,0.611164,...,0.048438,0.087773,0.282774,0.609358,0.928531,0.053702,0.887791,0.077857,0.907575,0.019762
1,3002,1,0.017736,0.668591,0.677090,0.863390,0.765749,0.612856,0.570055,0.668208,...,0.032091,0.078954,0.286004,0.554657,0.905266,0.042847,0.940108,0.052616,0.919997,0.024096

In [21]:
df1 = df.drop(['PATNO'], axis=1)
df1.head(2)

,APPRDX,cg26111030,cg17605629,cg06480636,cg13901712,cg22190754,cg20717075,cg15000071,cg22707381,cg18804921,...,cg10364513,cg14410319,cg25158734,cg00337440,cg11543740,cg20546928,cg25126016,cg18295068,cg12942009,cg02320740
0,2,0.027015,0.726750,0.629698,0.891398,0.383983,0.424800,0.550229,0.611164,0.841155,...,0.048438,0.087773,0.282774,0.609358,0.928531,0.053702,0.887791,0.077857,0.907575,0.019762
1,1,0.017736,0.668591,0.677090,0.863390,0.765749,0.612856,0.570055,0.668208,0.870984,...,0.032091,0.078954,0.286004,0.554657,0.905266,0.042847,0.940108,0.052616,0.919997,0.024096

In [22]:
np.random.seed (1)
dframe1 = pd.DataFrame(columns=['Accuracy', 'Std_Dev'])

for i in range(1, 101):
    print(i)
    df2 = df1.groupby('APPRDX').apply(lambda x: x.sample(20))
    X = df2.drop('APPRDX', axis = 1)
    y = df2['APPRDX']
    random_forest_model = RandomForestClassifier(n_estimators = 100, max_depth = 5, criterion = 'gini')
    scores = cross_val_score(random_forest_model, X, y, cv = 10, n_jobs = -1)
    mean_score = scores.mean()
    print(f'Mean accuracy: {mean_score}')
    new_row = {'Accuracy': mean_score, 'Std_Dev': std(scores)}
    dframe1 = pd.concat([dframe1, pd.DataFrame(new_row, index=[0])], ignore_index=True)

1
Mean accuracy: 0.85
2
Mean accuracy: 0.825
3
Mean accuracy: 0.775
4
Mean accuracy: 0.9
5
Mean accuracy: 0.825
6
Mean accuracy: 0.725
7
Mean accuracy: 0.9
8
Mean accuracy: 0.85
9
Mean accuracy: 0.9
10
Mean accuracy: 0.825
11
Mean accuracy: 0.9
12
Mean accuracy: 0.875
13
Mean accuracy: 0.825
14
Mean accuracy: 0.875
15
Mean accuracy: 0.825
16
Mean accuracy: 0.9
17
Mean accuracy: 0.85
18
Mean accuracy: 0.875
19
Mean accuracy: 0.925
20
Mean accuracy: 0.825
21
Mean accuracy: 0.8
22
Mean accuracy: 0.85
23
Mean accuracy: 0.8
24
Mean accuracy: 0.7
25
Mean accuracy: 0.875
26
Mean accuracy: 0.7
27
Mean accuracy: 0.875
28
Mean accuracy: 0.825
29
Mean accuracy: 0.825
30
Mean accuracy: 0.75
31
Mean accuracy: 0.8
32
Mean accuracy: 0.825
33
Mean accuracy: 0.825
34
Mean accuracy: 0.775
35
Mean accuracy: 0.875
36
Mean accuracy: 0.875
37
Mean accuracy: 0.8
38
Mean accuracy: 0.875
39
Mean accuracy: 0.925
40
Mean accuracy: 0.9
41
Mean accuracy: 0.8
42
Mean accuracy: 0.85
43
Mean accuracy: 0.85
44
Mean accuracy: 0.85
45
Mean accuracy: 0.825
46
Mean accuracy: 0.775
47
Mean accuracy: 0.875
48
Mean accuracy: 0.9
49
Mean accuracy: 0.85
50
Mean accuracy: 0.875
51
Mean accuracy: 0.825
52
Mean accuracy: 0.825
53
Mean accuracy: 0.825
54
Mean accuracy: 0.875
55
Mean accuracy: 0.925
56
Mean accuracy: 0.825
57
Mean accuracy: 0.85
58
Mean accuracy: 0.85
59
Mean accuracy: 0.9
60
Mean accuracy: 0.875
61
Mean accuracy: 0.85
62
Mean accuracy: 0.875
63
Mean accuracy: 0.775
64
Mean accuracy: 0.9
65
Mean accuracy: 0.9
66
Mean accuracy: 0.85
67
Mean accuracy: 0.825
68
Mean accuracy: 0.875
69
Mean accuracy: 1.0
70
Mean accuracy: 0.85
71
Mean accuracy: 0.825
72
Mean accuracy: 0.825
73
Mean accuracy: 0.825
74
Mean accuracy: 0.825
75
Mean accuracy: 0.875
76
Mean accuracy: 0.875
77
Mean accuracy: 0.825
78
Mean accuracy: 0.85
79
Mean accuracy: 0.925
80
Mean accuracy: 0.85
81
Mean accuracy: 0.825
82
Mean accuracy: 0.75
83
Mean accuracy: 0.825
84
Mean accuracy: 0.85
85
Mean accuracy: 0.875
86
Mean accuracy: 0.875
87
Mean accuracy: 0.875
88
Mean accuracy: 0.9
89
Mean accuracy: 0.875
90
Mean accuracy: 0.8
91
Mean accuracy: 0.775
92
Mean accuracy: 0.775
93
Mean accuracy: 0.925
94
Mean accuracy: 0.775
95
Mean accuracy: 0.925
96
Mean accuracy: 0.875
97
Mean accuracy: 0.85
98
Mean accuracy: 0.775
99
Mean accuracy: 0.85
100
Mean accuracy: 0.825

In [23]:
print(mean(dframe1['Accuracy']))
dframe1.to_csv ("LexicalFluency_Top50sCpG94_Female_100RF.csv", index = False)

0.8455000000000001