In [1]:
import random
import numpy as np
import pandas as pd
import seaborn as sn
from numpy import std
from numpy import mean
import matplotlib.pyplot as plt
from sklearn.datasets import make_classification
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.model_selection import RepeatedStratifiedKFold
from sklearn.metrics import confusion_matrix, accuracy_score
%matplotlib inline

In [2]:
%cd Z:\PPMI_Data\Excels\Raw_And_More
df = pd.read_csv ("beta_post_Funnorm_PPMI_EPICn524final030618.csv")
df.head(2)

Z:\PPMI_Data\Excels\Raw_And_More

,200973410159_R03C01,200991620021_R01C01,200991620021_R03C01,200989060105_R03C01,200989060135_R07C01,200989060162_R04C01,200973410167_R04C01,200973410143_R01C01,200973410143_R06C01,200973410167_R05C01,...,200989060089_R02C01,200989060089_R01C01,200989060089_R04C01,200973410143_R08C01,200973410143_R07C01,200989060089_R03C01,200989060150_R04C01,200989060150_R05C01,200989060150_R06C01,200991620049_R08C01
cg14817997,0.834027,0.849201,0.772995,0.885288,0.772547,0.756429,0.719766,0.775910,0.768914,0.759352,...,0.788239,0.838946,0.845263,0.770405,0.852917,0.783813,0.806930,0.875691,0.661276,0.737917
cg26928153,0.945589,0.948538,0.962199,0.944048,0.926306,0.956061,0.912988,0.955983,0.957120,0.897589,...,0.951206,0.958975,0.957062,0.954738,0.947765,0.958086,0.948044,0.942405,0.954990,0.946272

In [3]:
df.index.name ='CpG'
df.reset_index(inplace=True)
df.head(2)

,CpG,200973410159_R03C01,200991620021_R01C01,200991620021_R03C01,200989060105_R03C01,200989060135_R07C01,200989060162_R04C01,200973410167_R04C01,200973410143_R01C01,200973410143_R06C01,...,200989060089_R02C01,200989060089_R01C01,200989060089_R04C01,200973410143_R08C01,200973410143_R07C01,200989060089_R03C01,200989060150_R04C01,200989060150_R05C01,200989060150_R06C01,200991620049_R08C01
0,cg14817997,0.834027,0.849201,0.772995,0.885288,0.772547,0.756429,0.719766,0.775910,0.768914,...,0.788239,0.838946,0.845263,0.770405,0.852917,0.783813,0.806930,0.875691,0.661276,0.737917
1,cg26928153,0.945589,0.948538,0.962199,0.944048,0.926306,0.956061,0.912988,0.955983,0.957120,...,0.951206,0.958975,0.957062,0.954738,0.947765,0.958086,0.948044,0.942405,0.954990,0.946272

In [4]:
df = df.transpose()
df.head(2)

,0,1,2,3,4,5,6,7,8,9,...,864057,864058,864059,864060,864061,864062,864063,864064,864065,864066
CpG,cg14817997,cg26928153,cg16269199,cg13869341,cg14008030,cg12045430,cg20826792,cg20253340,cg02404219,cg21870274,...,cg02995750,cg14467015,cg15516537,cg05999368,cg15462332,cg00335297,cg02600718,cg10488260,cg07587934,cg16855331
200973410159_R03C01,0.834027,0.945589,0.845186,0.928455,0.582476,0.11692,0.059963,0.523214,0.758915,0.887897,...,0.693517,0.128043,0.478095,0.300037,0.270093,0.217182,0.244948,0.273165,0.781204,0.539283

In [5]:
df.rename(columns=df.iloc[0], inplace = True)

In [6]:
df.index.name ='CpG'
df.reset_index(inplace=True)
df.head(2)

,CpG,cg14817997,cg26928153,cg16269199,cg13869341,cg14008030,cg12045430,cg20826792,cg20253340,cg02404219,...,cg02995750,cg14467015,cg15516537,cg05999368,cg15462332,cg00335297,cg02600718,cg10488260,cg07587934,cg16855331
0,CpG,cg14817997,cg26928153,cg16269199,cg13869341,cg14008030,cg12045430,cg20826792,cg20253340,cg02404219,...,cg02995750,cg14467015,cg15516537,cg05999368,cg15462332,cg00335297,cg02600718,cg10488260,cg07587934,cg16855331
1,200973410159_R03C01,0.834027,0.945589,0.845186,0.928455,0.582476,0.11692,0.059963,0.523214,0.758915,...,0.693517,0.128043,0.478095,0.300037,0.270093,0.217182,0.244948,0.273165,0.781204,0.539283

In [7]:
df = df.drop ([0], axis = 0)
df.head(2)

,CpG,cg14817997,cg26928153,cg16269199,cg13869341,cg14008030,cg12045430,cg20826792,cg20253340,cg02404219,...,cg02995750,cg14467015,cg15516537,cg05999368,cg15462332,cg00335297,cg02600718,cg10488260,cg07587934,cg16855331
1,200973410159_R03C01,0.834027,0.945589,0.845186,0.928455,0.582476,0.11692,0.059963,0.523214,0.758915,...,0.693517,0.128043,0.478095,0.300037,0.270093,0.217182,0.244948,0.273165,0.781204,0.539283
2,200991620021_R01C01,0.849201,0.948538,0.911488,0.885379,0.53699,0.097013,0.083405,0.539284,0.670439,...,0.887561,0.850783,0.860009,0.736628,0.870584,0.742256,0.247742,0.845816,0.716938,0.519672

In [8]:
df.rename (columns = {"CpG" : "Sentrix"}, inplace = True)
df.head(2)

,Sentrix,cg14817997,cg26928153,cg16269199,cg13869341,cg14008030,cg12045430,cg20826792,cg20253340,cg02404219,...,cg02995750,cg14467015,cg15516537,cg05999368,cg15462332,cg00335297,cg02600718,cg10488260,cg07587934,cg16855331
1,200973410159_R03C01,0.834027,0.945589,0.845186,0.928455,0.582476,0.11692,0.059963,0.523214,0.758915,...,0.693517,0.128043,0.478095,0.300037,0.270093,0.217182,0.244948,0.273165,0.781204,0.539283
2,200991620021_R01C01,0.849201,0.948538,0.911488,0.885379,0.53699,0.097013,0.083405,0.539284,0.670439,...,0.887561,0.850783,0.860009,0.736628,0.870584,0.742256,0.247742,0.845816,0.716938,0.519672

In [9]:
df1 = pd.read_csv ("Sentrix_APPRDX.csv")
df1.head(2)

               Sentrix  APPRDX
0  200973410159_R03C01       2
1  200991620021_R01C01       1

In [10]:
df2 = pd.merge (df1, df, on= "Sentrix", how= "inner")
df2.head(2)

,Sentrix,APPRDX,cg14817997,cg26928153,cg16269199,cg13869341,cg14008030,cg12045430,cg20826792,cg20253340,...,cg02995750,cg14467015,cg15516537,cg05999368,cg15462332,cg00335297,cg02600718,cg10488260,cg07587934,cg16855331
0,200973410159_R03C01,2,0.834027,0.945589,0.845186,0.928455,0.582476,0.11692,0.059963,0.523214,...,0.693517,0.128043,0.478095,0.300037,0.270093,0.217182,0.244948,0.273165,0.781204,0.539283
1,200991620021_R01C01,1,0.849201,0.948538,0.911488,0.885379,0.53699,0.097013,0.083405,0.539284,...,0.887561,0.850783,0.860009,0.736628,0.870584,0.742256,0.247742,0.845816,0.716938,0.519672

In [11]:
df2.shape

(457, 864069)

In [12]:
df = df2.drop (['APPRDX', 'Sentrix'], axis=1)

# Random 54 Cpg

In [13]:
np.random.seed (1)
dframe1 = pd.DataFrame(columns=['Accuracy', 'Std_Dev'])
for i in range (1,101) :
        print(i)
        df3 = df.sample(54, axis=1)
        df3 = df3.reindex(['APPRDX', *df3.columns], axis=1).assign(APPRDX=df2['APPRDX'])
        dataset = df3.groupby('APPRDX').apply(lambda x: x.sample(100))
        X = dataset.iloc[:, 1:].values
        y = dataset.iloc[:, 0].values
        classifier = RandomForestClassifier(n_estimators = 100, criterion = 'entropy', random_state = 1)
        cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=1, random_state=1)
        n_scores = cross_val_score(classifier, X, y, scoring='accuracy', cv=cv, n_jobs=-1, error_score='raise')
        dframe1 = dframe1.append({'Accuracy': mean(n_scores), 'Std_Dev': std(n_scores)}, ignore_index=True)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100

In [14]:
dframe1.head(3)

   Accuracy   Std_Dev
0     0.515  0.118427
1     0.540  0.111355
2     0.565  0.095000

In [15]:
dframe1.to_csv ("AllChr_Random_CpG54_Accuracy_1000RF.csv")

# Random 9 Cpg

In [16]:
np.random.seed (1)
dframe1 = pd.DataFrame(columns=['Accuracy', 'Std_Dev'])
for i in range (1,101) :
        print(i)
        df3 = df.sample(9, axis=1)
        df3 = df3.reindex(['APPRDX', *df3.columns], axis=1).assign(APPRDX=df2['APPRDX'])
        dataset = df3.groupby('APPRDX').apply(lambda x: x.sample(100))
        X = dataset.iloc[:, 1:].values
        y = dataset.iloc[:, 0].values
        classifier = RandomForestClassifier(n_estimators = 100, criterion = 'entropy', random_state = 1)
        cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=1, random_state=1)
        n_scores = cross_val_score(classifier, X, y, scoring='accuracy', cv=cv, n_jobs=-1, error_score='raise')
        dframe1 = dframe1.append({'Accuracy': mean(n_scores), 'Std_Dev': std(n_scores)}, ignore_index=True)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100

In [17]:
dframe1.head(3)

   Accuracy   Std_Dev
0     0.420  0.102956
1     0.450  0.116190
2     0.505  0.129325

In [18]:
dframe1.to_csv ("AllChr_Random_CpG9_Accuracy_1000RF.csv")