In [1]:
import pandas as pd
import numpy as np
%cd Z:\PPMI_Data\Excels\Raw_And_More

Z:\PPMI_Data\Excels\Raw_And_More

In [2]:
Cpg_File = pd.read_csv ("beta_post_Funnorm_PPMI_EPICn524final030618.csv")
Cpg_File.head(3)

,200973410159_R03C01,200991620021_R01C01,200991620021_R03C01,200989060105_R03C01,200989060135_R07C01,200989060162_R04C01,200973410167_R04C01,200973410143_R01C01,200973410143_R06C01,200973410167_R05C01,...,200989060089_R02C01,200989060089_R01C01,200989060089_R04C01,200973410143_R08C01,200973410143_R07C01,200989060089_R03C01,200989060150_R04C01,200989060150_R05C01,200989060150_R06C01,200991620049_R08C01
cg14817997,0.834027,0.849201,0.772995,0.885288,0.772547,0.756429,0.719766,0.775910,0.768914,0.759352,...,0.788239,0.838946,0.845263,0.770405,0.852917,0.783813,0.806930,0.875691,0.661276,0.737917
cg26928153,0.945589,0.948538,0.962199,0.944048,0.926306,0.956061,0.912988,0.955983,0.957120,0.897589,...,0.951206,0.958975,0.957062,0.954738,0.947765,0.958086,0.948044,0.942405,0.954990,0.946272
cg16269199,0.845186,0.911488,0.948206,0.913622,0.778551,0.903924,0.742258,0.934683,0.897787,0.741083,...,0.889774,0.899517,0.908055,0.946297,0.910522,0.895500,0.889243,0.825368,0.913328,0.898812

In [3]:
Cpg_File.index.name ='CpG'
Cpg_File.reset_index(inplace=True)
Cpg_File.head(3)

,CpG,200973410159_R03C01,200991620021_R01C01,200991620021_R03C01,200989060105_R03C01,200989060135_R07C01,200989060162_R04C01,200973410167_R04C01,200973410143_R01C01,200973410143_R06C01,...,200989060089_R02C01,200989060089_R01C01,200989060089_R04C01,200973410143_R08C01,200973410143_R07C01,200989060089_R03C01,200989060150_R04C01,200989060150_R05C01,200989060150_R06C01,200991620049_R08C01
0,cg14817997,0.834027,0.849201,0.772995,0.885288,0.772547,0.756429,0.719766,0.775910,0.768914,...,0.788239,0.838946,0.845263,0.770405,0.852917,0.783813,0.806930,0.875691,0.661276,0.737917
1,cg26928153,0.945589,0.948538,0.962199,0.944048,0.926306,0.956061,0.912988,0.955983,0.957120,...,0.951206,0.958975,0.957062,0.954738,0.947765,0.958086,0.948044,0.942405,0.954990,0.946272
2,cg16269199,0.845186,0.911488,0.948206,0.913622,0.778551,0.903924,0.742258,0.934683,0.897787,...,0.889774,0.899517,0.908055,0.946297,0.910522,0.895500,0.889243,0.825368,0.913328,0.898812

In [4]:
%cd Z:\PPMI_Data\Excels\NonMotors\Derived250\Male\GeneCpG\Hopkins
df1 = pd.read_csv ("CpG_Hopkins_Gene.csv")
df1.head(2)

Z:\PPMI_Data\Excels\NonMotors\Derived250\Male\GeneCpG\Hopkins

  Gene         CpG
0  ACE  cg02440279
1  ACE  cg02131967

In [5]:
df = pd.merge (df1, Cpg_File, on = 'CpG', how = 'inner')
df.head(2)

,Gene,CpG,200973410159_R03C01,200991620021_R01C01,200991620021_R03C01,200989060105_R03C01,200989060135_R07C01,200989060162_R04C01,200973410167_R04C01,200973410143_R01C01,...,200989060089_R02C01,200989060089_R01C01,200989060089_R04C01,200973410143_R08C01,200973410143_R07C01,200989060089_R03C01,200989060150_R04C01,200989060150_R05C01,200989060150_R06C01,200991620049_R08C01
0,ACE,cg02440279,0.012122,0.012942,0.011114,0.010308,0.009494,0.008924,0.004305,0.007891,...,0.008702,0.008749,0.010415,0.009735,0.011398,0.007547,0.008011,0.008602,0.008554,0.013379
1,ACE,cg02131967,0.013210,0.012920,0.009891,0.015167,0.012278,0.009686,0.020017,0.008273,...,0.010419,0.010646,0.011802,0.012049,0.011220,0.011542,0.011740,0.009805,0.013057,0.013564

df.to_csv ("TrailMakingB_CpG_Methylome.csv",index = 'False')

In [6]:
df = df.drop('Gene', axis=1)

In [7]:
dft = df.transpose()
dft.head(2)

,0,1,2,3,4,5,6,7,8,9,...,4333,4334,4335,4336,4337,4338,4339,4340,4341,4342
CpG,cg02440279,cg02131967,cg09920557,cg05952120,cg21796427,cg10468385,cg19354750,cg21657705,cg02040921,cg01489398,...,cg08990112,cg24987754,cg01108057,cg11424763,cg08584264,cg02750308,cg00382771,cg13510423,cg22194345,cg13669748
200973410159_R03C01,0.012122,0.01321,0.012391,0.019678,0.952778,0.9725,0.037777,0.972551,0.010487,0.964294,...,0.069262,0.905806,0.038993,0.921572,0.186159,0.776681,0.914206,0.330456,0.096746,0.050952

In [8]:
dft.rename(columns=dft.iloc[0], inplace = True)
dft.head(2)

,cg02440279,cg02131967,cg09920557,cg05952120,cg21796427,cg10468385,cg19354750,cg21657705,cg02040921,cg01489398,...,cg08990112,cg24987754,cg01108057,cg11424763,cg08584264,cg02750308,cg00382771,cg13510423,cg22194345,cg13669748
CpG,cg02440279,cg02131967,cg09920557,cg05952120,cg21796427,cg10468385,cg19354750,cg21657705,cg02040921,cg01489398,...,cg08990112,cg24987754,cg01108057,cg11424763,cg08584264,cg02750308,cg00382771,cg13510423,cg22194345,cg13669748
200973410159_R03C01,0.012122,0.01321,0.012391,0.019678,0.952778,0.9725,0.037777,0.972551,0.010487,0.964294,...,0.069262,0.905806,0.038993,0.921572,0.186159,0.776681,0.914206,0.330456,0.096746,0.050952

In [9]:
dft.index.name ='CpG'
dft.reset_index(inplace=True)
dft.head(2)

,CpG,cg02440279,cg02131967,cg09920557,cg05952120,cg21796427,cg10468385,cg19354750,cg21657705,cg02040921,...,cg08990112,cg24987754,cg01108057,cg11424763,cg08584264,cg02750308,cg00382771,cg13510423,cg22194345,cg13669748
0,CpG,cg02440279,cg02131967,cg09920557,cg05952120,cg21796427,cg10468385,cg19354750,cg21657705,cg02040921,...,cg08990112,cg24987754,cg01108057,cg11424763,cg08584264,cg02750308,cg00382771,cg13510423,cg22194345,cg13669748
1,200973410159_R03C01,0.012122,0.01321,0.012391,0.019678,0.952778,0.9725,0.037777,0.972551,0.010487,...,0.069262,0.905806,0.038993,0.921572,0.186159,0.776681,0.914206,0.330456,0.096746,0.050952

In [10]:
dft = dft.drop ([0], axis = 0)
dft.head(2)

,CpG,cg02440279,cg02131967,cg09920557,cg05952120,cg21796427,cg10468385,cg19354750,cg21657705,cg02040921,...,cg08990112,cg24987754,cg01108057,cg11424763,cg08584264,cg02750308,cg00382771,cg13510423,cg22194345,cg13669748
1,200973410159_R03C01,0.012122,0.01321,0.012391,0.019678,0.952778,0.9725,0.037777,0.972551,0.010487,...,0.069262,0.905806,0.038993,0.921572,0.186159,0.776681,0.914206,0.330456,0.096746,0.050952
2,200991620021_R01C01,0.012942,0.01292,0.013851,0.019254,0.931499,0.958497,0.027943,0.965904,0.012343,...,0.052416,0.883735,0.043388,0.872053,0.238532,0.878945,0.900896,0.316275,0.049689,0.08568

In [11]:
dft.rename (columns = {"CpG" : "Sentrix"}, inplace = True)
dft.head(2)

,Sentrix,cg02440279,cg02131967,cg09920557,cg05952120,cg21796427,cg10468385,cg19354750,cg21657705,cg02040921,...,cg08990112,cg24987754,cg01108057,cg11424763,cg08584264,cg02750308,cg00382771,cg13510423,cg22194345,cg13669748
1,200973410159_R03C01,0.012122,0.01321,0.012391,0.019678,0.952778,0.9725,0.037777,0.972551,0.010487,...,0.069262,0.905806,0.038993,0.921572,0.186159,0.776681,0.914206,0.330456,0.096746,0.050952
2,200991620021_R01C01,0.012942,0.01292,0.013851,0.019254,0.931499,0.958497,0.027943,0.965904,0.012343,...,0.052416,0.883735,0.043388,0.872053,0.238532,0.878945,0.900896,0.316275,0.049689,0.08568

In [12]:
df2 = pd.read_csv ("Hopkinswith_PATNO_APPRDX_Age_in524Methyl_Male.csv")
df3 = pd.merge (df2, dft, on= "Sentrix", how= "inner")
print(df3.shape)
df3.head(2)

(110, 4351)

,Sentrix,PATNO,Gender,APPRDX,HYS,Age,AgeCate,Category,cg02440279,cg02131967,...,cg08990112,cg24987754,cg01108057,cg11424763,cg08584264,cg02750308,cg00382771,cg13510423,cg22194345,cg13669748
0,200973410167_R05C01,3010,1,1,2,47.0,2,0,0.012232,0.015209,...,0.038912,0.856477,0.036409,0.907263,0.10837,0.546931,0.845835,0.307199,0.008555,0.060829
1,200989060143_R08C01,3024,1,1,2,52.7,2,0,0.009682,0.009379,...,0.046467,0.905048,0.022939,0.87388,0.213721,0.900037,0.916755,0.255893,0.040234,0.041951

In [13]:
df3.to_csv ("Hopkins_with_MethylomeDetails_Male.csv", index=False)