In [1]:
import pandas as pd
import numpy as np
%cd Z:\PPMI_Data\Excels\Raw_And_More

Z:\PPMI_Data\Excels\Raw_And_More

In [2]:
Cpg_File = pd.read_csv ("beta_post_Funnorm_PPMI_EPICn524final030618.csv")
Cpg_File.head(3)

,200973410159_R03C01,200991620021_R01C01,200991620021_R03C01,200989060105_R03C01,200989060135_R07C01,200989060162_R04C01,200973410167_R04C01,200973410143_R01C01,200973410143_R06C01,200973410167_R05C01,...,200989060089_R02C01,200989060089_R01C01,200989060089_R04C01,200973410143_R08C01,200973410143_R07C01,200989060089_R03C01,200989060150_R04C01,200989060150_R05C01,200989060150_R06C01,200991620049_R08C01
cg14817997,0.834027,0.849201,0.772995,0.885288,0.772547,0.756429,0.719766,0.775910,0.768914,0.759352,...,0.788239,0.838946,0.845263,0.770405,0.852917,0.783813,0.806930,0.875691,0.661276,0.737917
cg26928153,0.945589,0.948538,0.962199,0.944048,0.926306,0.956061,0.912988,0.955983,0.957120,0.897589,...,0.951206,0.958975,0.957062,0.954738,0.947765,0.958086,0.948044,0.942405,0.954990,0.946272
cg16269199,0.845186,0.911488,0.948206,0.913622,0.778551,0.903924,0.742258,0.934683,0.897787,0.741083,...,0.889774,0.899517,0.908055,0.946297,0.910522,0.895500,0.889243,0.825368,0.913328,0.898812

In [3]:
Cpg_File.index.name ='CpG'
Cpg_File.reset_index(inplace=True)
Cpg_File.head(3)

,CpG,200973410159_R03C01,200991620021_R01C01,200991620021_R03C01,200989060105_R03C01,200989060135_R07C01,200989060162_R04C01,200973410167_R04C01,200973410143_R01C01,200973410143_R06C01,...,200989060089_R02C01,200989060089_R01C01,200989060089_R04C01,200973410143_R08C01,200973410143_R07C01,200989060089_R03C01,200989060150_R04C01,200989060150_R05C01,200989060150_R06C01,200991620049_R08C01
0,cg14817997,0.834027,0.849201,0.772995,0.885288,0.772547,0.756429,0.719766,0.775910,0.768914,...,0.788239,0.838946,0.845263,0.770405,0.852917,0.783813,0.806930,0.875691,0.661276,0.737917
1,cg26928153,0.945589,0.948538,0.962199,0.944048,0.926306,0.956061,0.912988,0.955983,0.957120,...,0.951206,0.958975,0.957062,0.954738,0.947765,0.958086,0.948044,0.942405,0.954990,0.946272
2,cg16269199,0.845186,0.911488,0.948206,0.913622,0.778551,0.903924,0.742258,0.934683,0.897787,...,0.889774,0.899517,0.908055,0.946297,0.910522,0.895500,0.889243,0.825368,0.913328,0.898812

In [4]:
%cd Z:\PPMI_Data\Excels\NonMotors\Derived250\Female\GeneCpG\STAIS
df1 = pd.read_csv ("CpG_STAIS_Female_Gene.csv")
df1.head(2)

Z:\PPMI_Data\Excels\NonMotors\Derived250\Female\GeneCpG\STAIS

      Gene         CpG
0  ADORA2A  cg26354221
1  ADORA2A  cg02237342

In [5]:
df = pd.merge (df1, Cpg_File, on = 'CpG', how = 'inner')
df.head(2)

,Gene,CpG,200973410159_R03C01,200991620021_R01C01,200991620021_R03C01,200989060105_R03C01,200989060135_R07C01,200989060162_R04C01,200973410167_R04C01,200973410143_R01C01,...,200989060089_R02C01,200989060089_R01C01,200989060089_R04C01,200973410143_R08C01,200973410143_R07C01,200989060089_R03C01,200989060150_R04C01,200989060150_R05C01,200989060150_R06C01,200991620049_R08C01
0,ADORA2A,cg26354221,0.918085,0.924711,0.931688,0.958247,0.941753,0.947348,0.956772,0.927744,...,0.965767,0.924744,0.955017,0.937119,0.952122,0.945475,0.951114,0.940691,0.921226,0.954533
1,ADORA2A,cg02237342,0.016498,0.025191,0.025810,0.017621,0.018109,0.009537,0.027056,0.016664,...,0.016807,0.020812,0.015113,0.015787,0.015707,0.018724,0.015660,0.017092,0.024251,0.022443

df.to_csv ("TrailMakingB_CpG_Methylome.csv",index = 'False')

In [6]:
df = df.drop('Gene', axis=1)

In [7]:
dft = df.transpose()
dft.head(2)

,0,1,2,3,4,5,6,7,8,9,...,3032,3033,3034,3035,3036,3037,3038,3039,3040,3041
CpG,cg26354221,cg02237342,cg06516974,cg20660269,cg12793123,cg08025954,cg21584430,cg26001125,cg10766357,cg04250930,...,cg12383788,cg09938164,cg16043968,cg06398244,cg26924480,cg06985259,cg09180977,cg05600023,cg01781529,cg02839875
200973410159_R03C01,0.918085,0.016498,0.016215,0.01499,0.011442,0.054316,0.864747,0.679647,0.869149,0.769781,...,0.920545,0.820139,0.943315,0.920632,0.876711,0.929227,0.946104,0.848444,0.605773,0.629179

In [8]:
dft.rename(columns=dft.iloc[0], inplace = True)
dft.head(2)

,cg26354221,cg02237342,cg06516974,cg20660269,cg12793123,cg08025954,cg21584430,cg26001125,cg10766357,cg04250930,...,cg12383788,cg09938164,cg16043968,cg06398244,cg26924480,cg06985259,cg09180977,cg05600023,cg01781529,cg02839875
CpG,cg26354221,cg02237342,cg06516974,cg20660269,cg12793123,cg08025954,cg21584430,cg26001125,cg10766357,cg04250930,...,cg12383788,cg09938164,cg16043968,cg06398244,cg26924480,cg06985259,cg09180977,cg05600023,cg01781529,cg02839875
200973410159_R03C01,0.918085,0.016498,0.016215,0.01499,0.011442,0.054316,0.864747,0.679647,0.869149,0.769781,...,0.920545,0.820139,0.943315,0.920632,0.876711,0.929227,0.946104,0.848444,0.605773,0.629179

In [9]:
dft.index.name ='CpG'
dft.reset_index(inplace=True)
dft.head(2)

,CpG,cg26354221,cg02237342,cg06516974,cg20660269,cg12793123,cg08025954,cg21584430,cg26001125,cg10766357,...,cg12383788,cg09938164,cg16043968,cg06398244,cg26924480,cg06985259,cg09180977,cg05600023,cg01781529,cg02839875
0,CpG,cg26354221,cg02237342,cg06516974,cg20660269,cg12793123,cg08025954,cg21584430,cg26001125,cg10766357,...,cg12383788,cg09938164,cg16043968,cg06398244,cg26924480,cg06985259,cg09180977,cg05600023,cg01781529,cg02839875
1,200973410159_R03C01,0.918085,0.016498,0.016215,0.01499,0.011442,0.054316,0.864747,0.679647,0.869149,...,0.920545,0.820139,0.943315,0.920632,0.876711,0.929227,0.946104,0.848444,0.605773,0.629179

In [10]:
dft = dft.drop ([0], axis = 0)
dft.head(2)

,CpG,cg26354221,cg02237342,cg06516974,cg20660269,cg12793123,cg08025954,cg21584430,cg26001125,cg10766357,...,cg12383788,cg09938164,cg16043968,cg06398244,cg26924480,cg06985259,cg09180977,cg05600023,cg01781529,cg02839875
1,200973410159_R03C01,0.918085,0.016498,0.016215,0.01499,0.011442,0.054316,0.864747,0.679647,0.869149,...,0.920545,0.820139,0.943315,0.920632,0.876711,0.929227,0.946104,0.848444,0.605773,0.629179
2,200991620021_R01C01,0.924711,0.025191,0.018947,0.016032,0.017506,0.064285,0.784169,0.614111,0.860275,...,0.908416,0.726545,0.923891,0.86475,0.81658,0.933854,0.908872,0.827141,0.602518,0.609845

In [11]:
dft.rename (columns = {"CpG" : "Sentrix"}, inplace = True)
dft.head(2)

,Sentrix,cg26354221,cg02237342,cg06516974,cg20660269,cg12793123,cg08025954,cg21584430,cg26001125,cg10766357,...,cg12383788,cg09938164,cg16043968,cg06398244,cg26924480,cg06985259,cg09180977,cg05600023,cg01781529,cg02839875
1,200973410159_R03C01,0.918085,0.016498,0.016215,0.01499,0.011442,0.054316,0.864747,0.679647,0.869149,...,0.920545,0.820139,0.943315,0.920632,0.876711,0.929227,0.946104,0.848444,0.605773,0.629179
2,200991620021_R01C01,0.924711,0.025191,0.018947,0.016032,0.017506,0.064285,0.784169,0.614111,0.860275,...,0.908416,0.726545,0.923891,0.86475,0.81658,0.933854,0.908872,0.827141,0.602518,0.609845

In [12]:
df2 = pd.read_csv ("STAISwith_PATNO_APPRDX_Age_in524Methyl_Female.csv")
df3 = pd.merge (df2, dft, on= "Sentrix", how= "inner")
print(df3.shape)
df3.head(2)

(150, 3050)

,Sentrix,PATNO,Gender,APPRDX,HYS,Age,AgeCate,STAIS_Category,cg26354221,cg02237342,...,cg12383788,cg09938164,cg16043968,cg06398244,cg26924480,cg06985259,cg09180977,cg05600023,cg01781529,cg02839875
0,200973410159_R03C01,3000,2,2,0,69.1,4,1,0.918085,0.016498,...,0.920545,0.820139,0.943315,0.920632,0.876711,0.929227,0.946104,0.848444,0.605773,0.629179
1,200991620021_R03C01,3002,2,1,2,67.6,4,2,0.931688,0.02581,...,0.927666,0.774644,0.944821,0.885769,0.870694,0.933138,0.916203,0.797292,0.631043,0.648518

In [14]:
df3.to_csv ("STAIS_with_MethylomeDetails_Female.csv", index=False)