In [1]:
import numpy as np
import pandas as pd

In [2]:
%cd Z:\PPMI_Data\Excels\Raw_And_More
Cpg_File = pd.read_csv ("beta_post_Funnorm_PPMI_EPICn524final030618.csv")
Cpg_File.head(3)

Z:\PPMI_Data\Excels\Raw_And_More

,200973410159_R03C01,200991620021_R01C01,200991620021_R03C01,200989060105_R03C01,200989060135_R07C01,200989060162_R04C01,200973410167_R04C01,200973410143_R01C01,200973410143_R06C01,200973410167_R05C01,...,200989060089_R02C01,200989060089_R01C01,200989060089_R04C01,200973410143_R08C01,200973410143_R07C01,200989060089_R03C01,200989060150_R04C01,200989060150_R05C01,200989060150_R06C01,200991620049_R08C01
cg14817997,0.834027,0.849201,0.772995,0.885288,0.772547,0.756429,0.719766,0.775910,0.768914,0.759352,...,0.788239,0.838946,0.845263,0.770405,0.852917,0.783813,0.806930,0.875691,0.661276,0.737917
cg26928153,0.945589,0.948538,0.962199,0.944048,0.926306,0.956061,0.912988,0.955983,0.957120,0.897589,...,0.951206,0.958975,0.957062,0.954738,0.947765,0.958086,0.948044,0.942405,0.954990,0.946272
cg16269199,0.845186,0.911488,0.948206,0.913622,0.778551,0.903924,0.742258,0.934683,0.897787,0.741083,...,0.889774,0.899517,0.908055,0.946297,0.910522,0.895500,0.889243,0.825368,0.913328,0.898812

In [3]:
Cpg_File.index.name ='CpG'
Cpg_File.reset_index(inplace=True)
Cpg_File.head(3)

,CpG,200973410159_R03C01,200991620021_R01C01,200991620021_R03C01,200989060105_R03C01,200989060135_R07C01,200989060162_R04C01,200973410167_R04C01,200973410143_R01C01,200973410143_R06C01,...,200989060089_R02C01,200989060089_R01C01,200989060089_R04C01,200973410143_R08C01,200973410143_R07C01,200989060089_R03C01,200989060150_R04C01,200989060150_R05C01,200989060150_R06C01,200991620049_R08C01
0,cg14817997,0.834027,0.849201,0.772995,0.885288,0.772547,0.756429,0.719766,0.775910,0.768914,...,0.788239,0.838946,0.845263,0.770405,0.852917,0.783813,0.806930,0.875691,0.661276,0.737917
1,cg26928153,0.945589,0.948538,0.962199,0.944048,0.926306,0.956061,0.912988,0.955983,0.957120,...,0.951206,0.958975,0.957062,0.954738,0.947765,0.958086,0.948044,0.942405,0.954990,0.946272
2,cg16269199,0.845186,0.911488,0.948206,0.913622,0.778551,0.903924,0.742258,0.934683,0.897787,...,0.889774,0.899517,0.908055,0.946297,0.910522,0.895500,0.889243,0.825368,0.913328,0.898812

# Trail Making A

In [4]:
%cd Z:\PPMI_Data\Excels\NonMotors\The251\GeneCpG\TrailMakeA
df1 = pd.read_csv ("CpG_TrailMakeA_Gene.csv")
df1.head(2)

Z:\PPMI_Data\Excels\NonMotors\The251\GeneCpG\TrailMakeA

  Gene         CpG
0  A2M  cg08012045
1  A2M  cg08300930

In [5]:
df = pd.merge (df1, Cpg_File, on = 'CpG', how = 'inner')
df.head(2)

,Gene,CpG,200973410159_R03C01,200991620021_R01C01,200991620021_R03C01,200989060105_R03C01,200989060135_R07C01,200989060162_R04C01,200973410167_R04C01,200973410143_R01C01,...,200989060089_R02C01,200989060089_R01C01,200989060089_R04C01,200973410143_R08C01,200973410143_R07C01,200989060089_R03C01,200989060150_R04C01,200989060150_R05C01,200989060150_R06C01,200991620049_R08C01
0,A2M,cg08012045,0.964598,0.962437,0.952757,0.948345,0.938567,0.961376,0.962158,0.974459,...,0.957219,0.968821,0.963070,0.964867,0.962382,0.962788,0.957560,0.952518,0.953154,0.961284
1,A2M,cg08300930,0.960974,0.964442,0.970714,0.966610,0.960982,0.974806,0.963041,0.970139,...,0.968219,0.967798,0.968836,0.968424,0.972526,0.966961,0.970827,0.967216,0.968653,0.962201

df.to_csv ("TrailMakingB_CpG_Methylome.csv",index = 'False')

In [6]:
df = df.drop('Gene', axis=1)

In [7]:
dft = df.transpose()
dft.head(2)

,0,1,2,3,4,5,6,7,8,9,...,87708,87709,87710,87711,87712,87713,87714,87715,87716,87717
CpG,cg08012045,cg08300930,cg00134295,cg10537824,cg04990650,cg03379001,cg02215627,cg06699201,cg18100935,cg19220149,...,cg00956423,cg14462343,cg07481734,cg22394535,cg13044444,cg23223756,cg16870358,cg04754776,cg00154746,cg06155771
200973410159_R03C01,0.964598,0.960974,0.241886,0.852113,0.765526,0.856057,0.874673,0.798285,0.89382,0.879652,...,0.148515,0.036822,0.053052,0.044051,0.040994,0.047501,0.04635,0.904242,0.021033,0.813738

In [8]:
dft.rename(columns=dft.iloc[0], inplace = True)
dft.head(2)

,cg08012045,cg08300930,cg00134295,cg10537824,cg04990650,cg03379001,cg02215627,cg06699201,cg18100935,cg19220149,...,cg00956423,cg14462343,cg07481734,cg22394535,cg13044444,cg23223756,cg16870358,cg04754776,cg00154746,cg06155771
CpG,cg08012045,cg08300930,cg00134295,cg10537824,cg04990650,cg03379001,cg02215627,cg06699201,cg18100935,cg19220149,...,cg00956423,cg14462343,cg07481734,cg22394535,cg13044444,cg23223756,cg16870358,cg04754776,cg00154746,cg06155771
200973410159_R03C01,0.964598,0.960974,0.241886,0.852113,0.765526,0.856057,0.874673,0.798285,0.89382,0.879652,...,0.148515,0.036822,0.053052,0.044051,0.040994,0.047501,0.04635,0.904242,0.021033,0.813738

In [9]:
dft.index.name ='CpG'
dft.reset_index(inplace=True)
dft.head(2)

,CpG,cg08012045,cg08300930,cg00134295,cg10537824,cg04990650,cg03379001,cg02215627,cg06699201,cg18100935,...,cg00956423,cg14462343,cg07481734,cg22394535,cg13044444,cg23223756,cg16870358,cg04754776,cg00154746,cg06155771
0,CpG,cg08012045,cg08300930,cg00134295,cg10537824,cg04990650,cg03379001,cg02215627,cg06699201,cg18100935,...,cg00956423,cg14462343,cg07481734,cg22394535,cg13044444,cg23223756,cg16870358,cg04754776,cg00154746,cg06155771
1,200973410159_R03C01,0.964598,0.960974,0.241886,0.852113,0.765526,0.856057,0.874673,0.798285,0.89382,...,0.148515,0.036822,0.053052,0.044051,0.040994,0.047501,0.04635,0.904242,0.021033,0.813738

In [10]:
dft = dft.drop ([0], axis = 0)
dft.head(2)

,CpG,cg08012045,cg08300930,cg00134295,cg10537824,cg04990650,cg03379001,cg02215627,cg06699201,cg18100935,...,cg00956423,cg14462343,cg07481734,cg22394535,cg13044444,cg23223756,cg16870358,cg04754776,cg00154746,cg06155771
1,200973410159_R03C01,0.964598,0.960974,0.241886,0.852113,0.765526,0.856057,0.874673,0.798285,0.89382,...,0.148515,0.036822,0.053052,0.044051,0.040994,0.047501,0.04635,0.904242,0.021033,0.813738
2,200991620021_R01C01,0.962437,0.964442,0.24353,0.826172,0.84533,0.852316,0.871498,0.65314,0.89167,...,0.10987,0.056582,0.064137,0.053802,0.083556,0.042638,0.041733,0.896521,0.033285,0.753096

In [11]:
dft.rename (columns = {"CpG" : "Sentrix"}, inplace = True)
dft.head(2)

,Sentrix,cg08012045,cg08300930,cg00134295,cg10537824,cg04990650,cg03379001,cg02215627,cg06699201,cg18100935,...,cg00956423,cg14462343,cg07481734,cg22394535,cg13044444,cg23223756,cg16870358,cg04754776,cg00154746,cg06155771
1,200973410159_R03C01,0.964598,0.960974,0.241886,0.852113,0.765526,0.856057,0.874673,0.798285,0.89382,...,0.148515,0.036822,0.053052,0.044051,0.040994,0.047501,0.04635,0.904242,0.021033,0.813738
2,200991620021_R01C01,0.962437,0.964442,0.24353,0.826172,0.84533,0.852316,0.871498,0.65314,0.89167,...,0.10987,0.056582,0.064137,0.053802,0.083556,0.042638,0.041733,0.896521,0.033285,0.753096

In [12]:
df2 = pd.read_csv ("TrailMakeA_PATNO_APPRDX_Age_in524Methyl.csv")
df3 = pd.merge (df2, dft, on= "Sentrix", how= "inner")
print(df3.shape)
df3.head(2)

(231, 87726)

,Sentrix,PATNO,Gender,Age,AgeCate,HYS,APPRDX,Trail_Making_A,cg08012045,cg08300930,...,cg00956423,cg14462343,cg07481734,cg22394535,cg13044444,cg23223756,cg16870358,cg04754776,cg00154746,cg06155771
0,200973410159_R03C01,3000,2,69.1,4,0,2,0.0,0.964598,0.960974,...,0.148515,0.036822,0.053052,0.044051,0.040994,0.047501,0.04635,0.904242,0.021033,0.813738
1,200991620021_R01C01,3001,1,65.1,4,2,1,1.0,0.962437,0.964442,...,0.10987,0.056582,0.064137,0.053802,0.083556,0.042638,0.041733,0.896521,0.033285,0.753096

In [13]:
df3.to_csv ("TrailMakeA_with_MethylomeDetails.csv", index=False)

In [14]:
df4 = df3.loc[df3['Gender'] == 1]
print(df4.shape)
df4.to_csv('TrailMakeA_with_MethylomeDetails_Male.csv')
df4.head(2)

(158, 87726)

,Sentrix,PATNO,Gender,Age,AgeCate,HYS,APPRDX,Trail_Making_A,cg08012045,cg08300930,...,cg00956423,cg14462343,cg07481734,cg22394535,cg13044444,cg23223756,cg16870358,cg04754776,cg00154746,cg06155771
1,200991620021_R01C01,3001,1,65.1,4,2,1,1.0,0.962437,0.964442,...,0.10987,0.056582,0.064137,0.053802,0.083556,0.042638,0.041733,0.896521,0.033285,0.753096
4,200989060135_R07C01,3004,1,59.4,3,0,2,1.0,0.938567,0.960982,...,0.1365,0.038891,0.039595,0.026053,0.051206,0.02966,0.027424,0.868682,0.020491,0.8888

# Dream

In [16]:
%cd Z:\PPMI_Data\Excels\NonMotors\The251\GeneCpG\Dream
df1 = pd.read_csv ("CpG_Dream_Gene.csv")
df1.head(2)

Z:\PPMI_Data\Excels\NonMotors\The251\GeneCpG\Dream

    Gene         CpG
0  ABCB6  cg07920064
1  ABCB6  cg27486695

In [17]:
df = pd.merge (df1, Cpg_File, on = 'CpG', how = 'inner')
df.head(2)

,Gene,CpG,200973410159_R03C01,200991620021_R01C01,200991620021_R03C01,200989060105_R03C01,200989060135_R07C01,200989060162_R04C01,200973410167_R04C01,200973410143_R01C01,...,200989060089_R02C01,200989060089_R01C01,200989060089_R04C01,200973410143_R08C01,200973410143_R07C01,200989060089_R03C01,200989060150_R04C01,200989060150_R05C01,200989060150_R06C01,200991620049_R08C01
0,ABCB6,cg07920064,0.012204,0.015851,0.023631,0.020341,0.019711,0.011479,0.021828,0.011070,...,0.015494,0.015469,0.027811,0.012207,0.015003,0.018568,0.020127,0.022636,0.020195,0.027371
1,ABCB6,cg27486695,0.009979,0.011071,0.010635,0.008186,0.009162,0.007719,0.012624,0.008845,...,0.007798,0.008052,0.007211,0.007299,0.011395,0.007122,0.008785,0.008824,0.007610,0.009819

In [18]:
df = df.drop('Gene', axis=1)

In [19]:
dft = df.transpose()
dft.head(2)

,0,1,2,3,4,5,6,7,8,9,...,629,630,631,632,633,634,635,636,637,638
CpG,cg07920064,cg27486695,cg08290072,cg19964303,cg24775454,cg26544277,cg23153680,cg06716437,cg18014247,cg19412109,...,cg12444710,cg01442833,cg17429457,cg26703873,cg21642591,cg06818627,cg20495247,cg12696399,cg22978941,cg12009719
200973410159_R03C01,0.012204,0.009979,0.018714,0.980246,0.020983,0.012105,0.036079,0.141707,0.060812,0.163503,...,0.88429,0.032632,0.86719,0.919339,0.04823,0.031371,0.047275,0.021027,0.037911,0.561618

In [20]:
dft.rename(columns=dft.iloc[0], inplace = True)
dft.head(2)

,cg07920064,cg27486695,cg08290072,cg19964303,cg24775454,cg26544277,cg23153680,cg06716437,cg18014247,cg19412109,...,cg12444710,cg01442833,cg17429457,cg26703873,cg21642591,cg06818627,cg20495247,cg12696399,cg22978941,cg12009719
CpG,cg07920064,cg27486695,cg08290072,cg19964303,cg24775454,cg26544277,cg23153680,cg06716437,cg18014247,cg19412109,...,cg12444710,cg01442833,cg17429457,cg26703873,cg21642591,cg06818627,cg20495247,cg12696399,cg22978941,cg12009719
200973410159_R03C01,0.012204,0.009979,0.018714,0.980246,0.020983,0.012105,0.036079,0.141707,0.060812,0.163503,...,0.88429,0.032632,0.86719,0.919339,0.04823,0.031371,0.047275,0.021027,0.037911,0.561618

In [21]:
dft.index.name ='CpG'
dft.reset_index(inplace=True)
dft.head(2)

,CpG,cg07920064,cg27486695,cg08290072,cg19964303,cg24775454,cg26544277,cg23153680,cg06716437,cg18014247,...,cg12444710,cg01442833,cg17429457,cg26703873,cg21642591,cg06818627,cg20495247,cg12696399,cg22978941,cg12009719
0,CpG,cg07920064,cg27486695,cg08290072,cg19964303,cg24775454,cg26544277,cg23153680,cg06716437,cg18014247,...,cg12444710,cg01442833,cg17429457,cg26703873,cg21642591,cg06818627,cg20495247,cg12696399,cg22978941,cg12009719
1,200973410159_R03C01,0.012204,0.009979,0.018714,0.980246,0.020983,0.012105,0.036079,0.141707,0.060812,...,0.88429,0.032632,0.86719,0.919339,0.04823,0.031371,0.047275,0.021027,0.037911,0.561618

In [22]:
dft = dft.drop ([0], axis = 0)
dft.head(2)

,CpG,cg07920064,cg27486695,cg08290072,cg19964303,cg24775454,cg26544277,cg23153680,cg06716437,cg18014247,...,cg12444710,cg01442833,cg17429457,cg26703873,cg21642591,cg06818627,cg20495247,cg12696399,cg22978941,cg12009719
1,200973410159_R03C01,0.012204,0.009979,0.018714,0.980246,0.020983,0.012105,0.036079,0.141707,0.060812,...,0.88429,0.032632,0.86719,0.919339,0.04823,0.031371,0.047275,0.021027,0.037911,0.561618
2,200991620021_R01C01,0.015851,0.011071,0.023565,0.9773,0.021343,0.016275,0.052446,0.144513,0.04109,...,0.86097,0.026532,0.811899,0.863209,0.029864,0.023758,0.032163,0.063712,0.052133,0.535793

In [23]:
dft.rename (columns = {"CpG" : "Sentrix"}, inplace = True)
dft.head(2)

,Sentrix,cg07920064,cg27486695,cg08290072,cg19964303,cg24775454,cg26544277,cg23153680,cg06716437,cg18014247,...,cg12444710,cg01442833,cg17429457,cg26703873,cg21642591,cg06818627,cg20495247,cg12696399,cg22978941,cg12009719
1,200973410159_R03C01,0.012204,0.009979,0.018714,0.980246,0.020983,0.012105,0.036079,0.141707,0.060812,...,0.88429,0.032632,0.86719,0.919339,0.04823,0.031371,0.047275,0.021027,0.037911,0.561618
2,200991620021_R01C01,0.015851,0.011071,0.023565,0.9773,0.021343,0.016275,0.052446,0.144513,0.04109,...,0.86097,0.026532,0.811899,0.863209,0.029864,0.023758,0.032163,0.063712,0.052133,0.535793

In [24]:
df2 = pd.read_csv ("Dream_PATNO_APPRDX_Age_in524Methyl.csv")
df3 = pd.merge (df2, dft, on= "Sentrix", how= "inner")
print(df3.shape)
df3.head(2)

(160, 647)

,Sentrix,PATNO,Gender,Age,AgeCate,HYS,APPRDX,REM_Dream,cg07920064,cg27486695,...,cg12444710,cg01442833,cg17429457,cg26703873,cg21642591,cg06818627,cg20495247,cg12696399,cg22978941,cg12009719
0,200991620021_R03C01,3002,2,67.6,4,2,1,2,0.023631,0.010635,...,0.865247,0.026656,0.916954,0.913505,0.03158,0.041244,0.052317,0.022932,0.045476,0.586523
1,200973410143_R01C01,3008,2,81.9,5,0,2,2,0.01107,0.008845,...,0.775811,0.021784,0.776223,0.926893,0.019075,0.018032,0.027572,0.026038,0.022241,0.526541

In [25]:
df3.to_csv ("Dream_with_MethylomeDetails.csv", index=False)

In [26]:
df4 = df3.loc[df3['Gender'] == 1]
print(df4.shape)
df4.to_csv('Dream_with_MethylomeDetails_Male.csv')
df4.head(2)

(110, 647)

,Sentrix,PATNO,Gender,Age,AgeCate,HYS,APPRDX,REM_Dream,cg07920064,cg27486695,...,cg12444710,cg01442833,cg17429457,cg26703873,cg21642591,cg06818627,cg20495247,cg12696399,cg22978941,cg12009719
3,200973410167_R05C01,3010,1,47.0,2,2,1,2,0.020416,0.010285,...,0.875451,0.022926,0.863662,0.907782,0.022595,0.019975,0.046285,0.021058,0.031956,0.590721
8,200989060143_R08C01,3024,1,52.7,2,2,1,0,0.011673,0.007561,...,0.857053,0.023881,0.829684,0.916199,0.039999,0.031587,0.041728,0.034263,0.02673,0.514764