In [1]:
import pandas as pd
import numpy as np
%cd Z:\PPMI_Data\Excels\Raw_And_More

Z:\PPMI_Data\Excels\Raw_And_More

In [2]:
Cpg_File = pd.read_csv ("beta_post_Funnorm_PPMI_EPICn524final030618.csv")
Cpg_File.head(3)

,200973410159_R03C01,200991620021_R01C01,200991620021_R03C01,200989060105_R03C01,200989060135_R07C01,200989060162_R04C01,200973410167_R04C01,200973410143_R01C01,200973410143_R06C01,200973410167_R05C01,...,200989060089_R02C01,200989060089_R01C01,200989060089_R04C01,200973410143_R08C01,200973410143_R07C01,200989060089_R03C01,200989060150_R04C01,200989060150_R05C01,200989060150_R06C01,200991620049_R08C01
cg14817997,0.834027,0.849201,0.772995,0.885288,0.772547,0.756429,0.719766,0.775910,0.768914,0.759352,...,0.788239,0.838946,0.845263,0.770405,0.852917,0.783813,0.806930,0.875691,0.661276,0.737917
cg26928153,0.945589,0.948538,0.962199,0.944048,0.926306,0.956061,0.912988,0.955983,0.957120,0.897589,...,0.951206,0.958975,0.957062,0.954738,0.947765,0.958086,0.948044,0.942405,0.954990,0.946272
cg16269199,0.845186,0.911488,0.948206,0.913622,0.778551,0.903924,0.742258,0.934683,0.897787,0.741083,...,0.889774,0.899517,0.908055,0.946297,0.910522,0.895500,0.889243,0.825368,0.913328,0.898812

In [3]:
Cpg_File.index.name ='CpG'
Cpg_File.reset_index(inplace=True)
Cpg_File.head(3)

,CpG,200973410159_R03C01,200991620021_R01C01,200991620021_R03C01,200989060105_R03C01,200989060135_R07C01,200989060162_R04C01,200973410167_R04C01,200973410143_R01C01,200973410143_R06C01,...,200989060089_R02C01,200989060089_R01C01,200989060089_R04C01,200973410143_R08C01,200973410143_R07C01,200989060089_R03C01,200989060150_R04C01,200989060150_R05C01,200989060150_R06C01,200991620049_R08C01
0,cg14817997,0.834027,0.849201,0.772995,0.885288,0.772547,0.756429,0.719766,0.775910,0.768914,...,0.788239,0.838946,0.845263,0.770405,0.852917,0.783813,0.806930,0.875691,0.661276,0.737917
1,cg26928153,0.945589,0.948538,0.962199,0.944048,0.926306,0.956061,0.912988,0.955983,0.957120,...,0.951206,0.958975,0.957062,0.954738,0.947765,0.958086,0.948044,0.942405,0.954990,0.946272
2,cg16269199,0.845186,0.911488,0.948206,0.913622,0.778551,0.903924,0.742258,0.934683,0.897787,...,0.889774,0.899517,0.908055,0.946297,0.910522,0.895500,0.889243,0.825368,0.913328,0.898812

In [14]:
%cd Z:\PPMI_Data\Excels\Only_Female\GeneCpG\Gastro
df1 = pd.read_csv ("CpG_Gastro_Gene.csv")
df1.head(2)

Z:\PPMI_Data\Excels\Only_Female\GeneCpG\Gastro

   Gene         CpG
0  ABAT  cg03441945
1  ABAT  cg21094410

In [15]:
df = pd.merge (df1, Cpg_File, on = 'CpG', how = 'inner')
df.head(2)

,Gene,CpG,200973410159_R03C01,200991620021_R01C01,200991620021_R03C01,200989060105_R03C01,200989060135_R07C01,200989060162_R04C01,200973410167_R04C01,200973410143_R01C01,...,200989060089_R02C01,200989060089_R01C01,200989060089_R04C01,200973410143_R08C01,200973410143_R07C01,200989060089_R03C01,200989060150_R04C01,200989060150_R05C01,200989060150_R06C01,200991620049_R08C01
0,ABAT,cg03441945,0.892410,0.908813,0.922532,0.876056,0.813126,0.935165,0.866976,0.905115,...,0.896406,0.882445,0.888929,0.899099,0.884275,0.875572,0.878673,0.904825,0.895282,0.859994
1,ABAT,cg21094410,0.015756,0.011350,0.013309,0.011801,0.012203,0.008164,0.022294,0.010226,...,0.011297,0.009869,0.010037,0.009838,0.012505,0.009203,0.010027,0.011897,0.010000,0.012657

In [16]:
df = df.drop('Gene', axis=1)

In [17]:
dft = df.transpose()
dft.head(2)

,0,1,2,3,4,5,6,7,8,9,...,33994,33995,33996,33997,33998,33999,34000,34001,34002,34003
CpG,cg03441945,cg21094410,cg22926093,cg25025609,cg16704802,cg06228737,cg00220102,cg19016494,cg12247200,cg24658413,...,cg12522722,cg11255513,cg09615521,cg12658517,cg02150941,cg22992837,cg02699881,cg05225390,cg01481208,cg08634588
200973410159_R03C01,0.89241,0.015756,0.011101,0.018491,0.020476,0.962482,0.677222,0.02956,0.929821,0.899519,...,0.909955,0.043985,0.054816,0.904326,0.135138,0.742557,0.029678,0.079017,0.894593,0.902949

In [18]:
dft.rename(columns=dft.iloc[0], inplace = True)
dft.head(2)

,cg03441945,cg21094410,cg22926093,cg25025609,cg16704802,cg06228737,cg00220102,cg19016494,cg12247200,cg24658413,...,cg12522722,cg11255513,cg09615521,cg12658517,cg02150941,cg22992837,cg02699881,cg05225390,cg01481208,cg08634588
CpG,cg03441945,cg21094410,cg22926093,cg25025609,cg16704802,cg06228737,cg00220102,cg19016494,cg12247200,cg24658413,...,cg12522722,cg11255513,cg09615521,cg12658517,cg02150941,cg22992837,cg02699881,cg05225390,cg01481208,cg08634588
200973410159_R03C01,0.89241,0.015756,0.011101,0.018491,0.020476,0.962482,0.677222,0.02956,0.929821,0.899519,...,0.909955,0.043985,0.054816,0.904326,0.135138,0.742557,0.029678,0.079017,0.894593,0.902949

In [19]:
dft.index.name ='CpG'
dft.reset_index(inplace=True)
dft.head(2)

,CpG,cg03441945,cg21094410,cg22926093,cg25025609,cg16704802,cg06228737,cg00220102,cg19016494,cg12247200,...,cg12522722,cg11255513,cg09615521,cg12658517,cg02150941,cg22992837,cg02699881,cg05225390,cg01481208,cg08634588
0,CpG,cg03441945,cg21094410,cg22926093,cg25025609,cg16704802,cg06228737,cg00220102,cg19016494,cg12247200,...,cg12522722,cg11255513,cg09615521,cg12658517,cg02150941,cg22992837,cg02699881,cg05225390,cg01481208,cg08634588
1,200973410159_R03C01,0.89241,0.015756,0.011101,0.018491,0.020476,0.962482,0.677222,0.02956,0.929821,...,0.909955,0.043985,0.054816,0.904326,0.135138,0.742557,0.029678,0.079017,0.894593,0.902949

In [20]:
dft = dft.drop ([0], axis = 0)
dft.head(2)

,CpG,cg03441945,cg21094410,cg22926093,cg25025609,cg16704802,cg06228737,cg00220102,cg19016494,cg12247200,...,cg12522722,cg11255513,cg09615521,cg12658517,cg02150941,cg22992837,cg02699881,cg05225390,cg01481208,cg08634588
1,200973410159_R03C01,0.89241,0.015756,0.011101,0.018491,0.020476,0.962482,0.677222,0.02956,0.929821,...,0.909955,0.043985,0.054816,0.904326,0.135138,0.742557,0.029678,0.079017,0.894593,0.902949
2,200991620021_R01C01,0.908813,0.01135,0.012197,0.022372,0.018128,0.945195,0.730494,0.017911,0.921435,...,0.900398,0.043525,0.043829,0.899376,0.078902,0.754703,0.030224,0.075161,0.909315,0.903716

In [21]:
dft.rename (columns = {"CpG" : "Sentrix"}, inplace = True)
dft.head(2)

,Sentrix,cg03441945,cg21094410,cg22926093,cg25025609,cg16704802,cg06228737,cg00220102,cg19016494,cg12247200,...,cg12522722,cg11255513,cg09615521,cg12658517,cg02150941,cg22992837,cg02699881,cg05225390,cg01481208,cg08634588
1,200973410159_R03C01,0.89241,0.015756,0.011101,0.018491,0.020476,0.962482,0.677222,0.02956,0.929821,...,0.909955,0.043985,0.054816,0.904326,0.135138,0.742557,0.029678,0.079017,0.894593,0.902949
2,200991620021_R01C01,0.908813,0.01135,0.012197,0.022372,0.018128,0.945195,0.730494,0.017911,0.921435,...,0.900398,0.043525,0.043829,0.899376,0.078902,0.754703,0.030224,0.075161,0.909315,0.903716

In [22]:
df2 = pd.read_csv ("Gastro_with_PATNO_APPRDX_Age_in524Methyl_Female.csv")
df3 = pd.merge (df2, dft, on= "Sentrix", how= "inner")
print(df3.shape)
df3.head(2)

(150, 34012)

,Sentrix,PATNO,Gender,APPRDX,HYS,Age,AgeCate,SCOPA_Gastro_Category,cg03441945,cg21094410,...,cg12522722,cg11255513,cg09615521,cg12658517,cg02150941,cg22992837,cg02699881,cg05225390,cg01481208,cg08634588
0,200973410159_R03C01,3000,2,2,0,69.1,4,0,0.89241,0.015756,...,0.909955,0.043985,0.054816,0.904326,0.135138,0.742557,0.029678,0.079017,0.894593,0.902949
1,200991620021_R03C01,3002,2,1,2,67.6,4,1,0.922532,0.013309,...,0.93175,0.051855,0.039594,0.92165,0.074618,0.843395,0.020945,0.058536,0.872011,0.890447

In [23]:
df3.to_csv ("Gastro_with_MethylomeDetails_Female.csv", index=False)