In [1]:
import pandas as pd
import numpy as np
%cd Z:\PPMI_Data\Excels\Raw_And_More

Z:\PPMI_Data\Excels\Raw_And_More

In [2]:
Cpg_File = pd.read_csv ("beta_post_Funnorm_PPMI_EPICn524final030618.csv")
Cpg_File.head(3)

,200973410159_R03C01,200991620021_R01C01,200991620021_R03C01,200989060105_R03C01,200989060135_R07C01,200989060162_R04C01,200973410167_R04C01,200973410143_R01C01,200973410143_R06C01,200973410167_R05C01,...,200989060089_R02C01,200989060089_R01C01,200989060089_R04C01,200973410143_R08C01,200973410143_R07C01,200989060089_R03C01,200989060150_R04C01,200989060150_R05C01,200989060150_R06C01,200991620049_R08C01
cg14817997,0.834027,0.849201,0.772995,0.885288,0.772547,0.756429,0.719766,0.775910,0.768914,0.759352,...,0.788239,0.838946,0.845263,0.770405,0.852917,0.783813,0.806930,0.875691,0.661276,0.737917
cg26928153,0.945589,0.948538,0.962199,0.944048,0.926306,0.956061,0.912988,0.955983,0.957120,0.897589,...,0.951206,0.958975,0.957062,0.954738,0.947765,0.958086,0.948044,0.942405,0.954990,0.946272
cg16269199,0.845186,0.911488,0.948206,0.913622,0.778551,0.903924,0.742258,0.934683,0.897787,0.741083,...,0.889774,0.899517,0.908055,0.946297,0.910522,0.895500,0.889243,0.825368,0.913328,0.898812

In [3]:
Cpg_File.index.name ='CpG'
Cpg_File.reset_index(inplace=True)
Cpg_File.head(3)

,CpG,200973410159_R03C01,200991620021_R01C01,200991620021_R03C01,200989060105_R03C01,200989060135_R07C01,200989060162_R04C01,200973410167_R04C01,200973410143_R01C01,200973410143_R06C01,...,200989060089_R02C01,200989060089_R01C01,200989060089_R04C01,200973410143_R08C01,200973410143_R07C01,200989060089_R03C01,200989060150_R04C01,200989060150_R05C01,200989060150_R06C01,200991620049_R08C01
0,cg14817997,0.834027,0.849201,0.772995,0.885288,0.772547,0.756429,0.719766,0.775910,0.768914,...,0.788239,0.838946,0.845263,0.770405,0.852917,0.783813,0.806930,0.875691,0.661276,0.737917
1,cg26928153,0.945589,0.948538,0.962199,0.944048,0.926306,0.956061,0.912988,0.955983,0.957120,...,0.951206,0.958975,0.957062,0.954738,0.947765,0.958086,0.948044,0.942405,0.954990,0.946272
2,cg16269199,0.845186,0.911488,0.948206,0.913622,0.778551,0.903924,0.742258,0.934683,0.897787,...,0.889774,0.899517,0.908055,0.946297,0.910522,0.895500,0.889243,0.825368,0.913328,0.898812

# Apathy

In [4]:
%cd Z:\PPMI_Data\Excels\NonMotors\Derived250\GeneCpG\Apathy
df1 = pd.read_csv ("CpG_Apathy_Gene.csv")
df1.head(2)

Z:\PPMI_Data\Excels\NonMotors\Derived250\GeneCpG\Apathy

    Gene         CpG
0  ACAT1  cg19958696
1  ACAT1  cg05962325

In [5]:
df = pd.merge (df1, Cpg_File, on = 'CpG', how = 'inner')
df.head(2)

,Gene,CpG,200973410159_R03C01,200991620021_R01C01,200991620021_R03C01,200989060105_R03C01,200989060135_R07C01,200989060162_R04C01,200973410167_R04C01,200973410143_R01C01,...,200989060089_R02C01,200989060089_R01C01,200989060089_R04C01,200973410143_R08C01,200973410143_R07C01,200989060089_R03C01,200989060150_R04C01,200989060150_R05C01,200989060150_R06C01,200991620049_R08C01
0,ACAT1,cg19958696,0.010314,0.014601,0.014465,0.011637,0.013334,0.012459,0.015753,0.010916,...,0.009128,0.012179,0.011363,0.015272,0.013397,0.011690,0.015407,0.012158,0.015253,0.018327
1,ACAT1,cg05962325,0.057597,0.068728,0.043749,0.060551,0.038642,0.045945,0.079013,0.038821,...,0.054511,0.037310,0.048636,0.043564,0.048270,0.047306,0.047491,0.047185,0.047315,0.062502

df.to_csv ("TrailMakingB_CpG_Methylome.csv",index = 'False')

In [6]:
df = df.drop('Gene', axis=1)

In [7]:
dft = df.transpose()
dft.head(2)

,0,1,2,3,4,5,6,7,8,9,...,3554,3555,3556,3557,3558,3559,3560,3561,3562,3563
CpG,cg19958696,cg05962325,cg15093662,cg04873221,cg05903298,cg19020436,cg14994056,cg05973813,cg18337422,cg11738745,...,cg19795267,cg16922840,cg19628277,cg26480988,cg01673347,cg12994818,cg09008531,cg16463148,cg04021430,cg04863888
200973410159_R03C01,0.010314,0.057597,0.020549,0.015659,0.011741,0.014318,0.035177,0.014771,0.013507,0.010626,...,0.751058,0.901978,0.580283,0.548182,0.725312,0.092118,0.723395,0.129795,0.017529,0.026699

In [8]:
dft.rename(columns=dft.iloc[0], inplace = True)
dft.head(2)

,cg19958696,cg05962325,cg15093662,cg04873221,cg05903298,cg19020436,cg14994056,cg05973813,cg18337422,cg11738745,...,cg19795267,cg16922840,cg19628277,cg26480988,cg01673347,cg12994818,cg09008531,cg16463148,cg04021430,cg04863888
CpG,cg19958696,cg05962325,cg15093662,cg04873221,cg05903298,cg19020436,cg14994056,cg05973813,cg18337422,cg11738745,...,cg19795267,cg16922840,cg19628277,cg26480988,cg01673347,cg12994818,cg09008531,cg16463148,cg04021430,cg04863888
200973410159_R03C01,0.010314,0.057597,0.020549,0.015659,0.011741,0.014318,0.035177,0.014771,0.013507,0.010626,...,0.751058,0.901978,0.580283,0.548182,0.725312,0.092118,0.723395,0.129795,0.017529,0.026699

In [9]:
dft.index.name ='CpG'
dft.reset_index(inplace=True)
dft.head(2)

,CpG,cg19958696,cg05962325,cg15093662,cg04873221,cg05903298,cg19020436,cg14994056,cg05973813,cg18337422,...,cg19795267,cg16922840,cg19628277,cg26480988,cg01673347,cg12994818,cg09008531,cg16463148,cg04021430,cg04863888
0,CpG,cg19958696,cg05962325,cg15093662,cg04873221,cg05903298,cg19020436,cg14994056,cg05973813,cg18337422,...,cg19795267,cg16922840,cg19628277,cg26480988,cg01673347,cg12994818,cg09008531,cg16463148,cg04021430,cg04863888
1,200973410159_R03C01,0.010314,0.057597,0.020549,0.015659,0.011741,0.014318,0.035177,0.014771,0.013507,...,0.751058,0.901978,0.580283,0.548182,0.725312,0.092118,0.723395,0.129795,0.017529,0.026699

In [10]:
dft = dft.drop ([0], axis = 0)
dft.head(2)

,CpG,cg19958696,cg05962325,cg15093662,cg04873221,cg05903298,cg19020436,cg14994056,cg05973813,cg18337422,...,cg19795267,cg16922840,cg19628277,cg26480988,cg01673347,cg12994818,cg09008531,cg16463148,cg04021430,cg04863888
1,200973410159_R03C01,0.010314,0.057597,0.020549,0.015659,0.011741,0.014318,0.035177,0.014771,0.013507,...,0.751058,0.901978,0.580283,0.548182,0.725312,0.092118,0.723395,0.129795,0.017529,0.026699
2,200991620021_R01C01,0.014601,0.068728,0.019329,0.021747,0.012923,0.017399,0.033939,0.020282,0.01716,...,0.630319,0.85156,0.52162,0.495925,0.830013,0.076462,0.72859,0.246918,0.039718,0.024071

In [11]:
dft.rename (columns = {"CpG" : "Sentrix"}, inplace = True)
dft.head(2)

,Sentrix,cg19958696,cg05962325,cg15093662,cg04873221,cg05903298,cg19020436,cg14994056,cg05973813,cg18337422,...,cg19795267,cg16922840,cg19628277,cg26480988,cg01673347,cg12994818,cg09008531,cg16463148,cg04021430,cg04863888
1,200973410159_R03C01,0.010314,0.057597,0.020549,0.015659,0.011741,0.014318,0.035177,0.014771,0.013507,...,0.751058,0.901978,0.580283,0.548182,0.725312,0.092118,0.723395,0.129795,0.017529,0.026699
2,200991620021_R01C01,0.014601,0.068728,0.019329,0.021747,0.012923,0.017399,0.033939,0.020282,0.01716,...,0.630319,0.85156,0.52162,0.495925,0.830013,0.076462,0.72859,0.246918,0.039718,0.024071

In [12]:
df2 = pd.read_csv ("Apathy_PATNO_APPRDX_Age_in524Methyl.csv")
df3 = pd.merge (df2, dft, on= "Sentrix", how= "inner")
print(df3.shape)
df3.head(2)

(458, 3572)

,Sentrix,PATNO,Gender,APPRDX,HYS,Age,AgeCate,MDS_Apathy_Category,cg19958696,cg05962325,...,cg19795267,cg16922840,cg19628277,cg26480988,cg01673347,cg12994818,cg09008531,cg16463148,cg04021430,cg04863888
0,200973410159_R03C01,3000,2,2,0,69.1,4,0,0.010314,0.057597,...,0.751058,0.901978,0.580283,0.548182,0.725312,0.092118,0.723395,0.129795,0.017529,0.026699
1,200991620021_R01C01,3001,1,1,2,65.1,4,0,0.014601,0.068728,...,0.630319,0.85156,0.52162,0.495925,0.830013,0.076462,0.72859,0.246918,0.039718,0.024071

In [13]:
df3.to_csv ("Apathy_with_MethylomeDetails_Male.csv", index=False)

# Gastro

In [14]:
%cd Z:\PPMI_Data\Excels\NonMotors\Derived250\GeneCpG\Gastro
df1 = pd.read_csv ("CpG_Gastro_Gene.csv")
df1.head(2)

Z:\PPMI_Data\Excels\NonMotors\Derived250\GeneCpG\Gastro

   Gene         CpG
0  ABAT  cg03441945
1  ABAT  cg21094410

In [15]:
df = pd.merge (df1, Cpg_File, on = 'CpG', how = 'inner')
df.head(2)

,Gene,CpG,200973410159_R03C01,200991620021_R01C01,200991620021_R03C01,200989060105_R03C01,200989060135_R07C01,200989060162_R04C01,200973410167_R04C01,200973410143_R01C01,...,200989060089_R02C01,200989060089_R01C01,200989060089_R04C01,200973410143_R08C01,200973410143_R07C01,200989060089_R03C01,200989060150_R04C01,200989060150_R05C01,200989060150_R06C01,200991620049_R08C01
0,ABAT,cg03441945,0.892410,0.908813,0.922532,0.876056,0.813126,0.935165,0.866976,0.905115,...,0.896406,0.882445,0.888929,0.899099,0.884275,0.875572,0.878673,0.904825,0.895282,0.859994
1,ABAT,cg21094410,0.015756,0.011350,0.013309,0.011801,0.012203,0.008164,0.022294,0.010226,...,0.011297,0.009869,0.010037,0.009838,0.012505,0.009203,0.010027,0.011897,0.010000,0.012657

In [16]:
df = df.drop('Gene', axis=1)

In [17]:
dft = df.transpose()
dft.head(2)

,0,1,2,3,4,5,6,7,8,9,...,33994,33995,33996,33997,33998,33999,34000,34001,34002,34003
CpG,cg03441945,cg21094410,cg22926093,cg25025609,cg16704802,cg06228737,cg00220102,cg19016494,cg12247200,cg24658413,...,cg12522722,cg11255513,cg09615521,cg12658517,cg02150941,cg22992837,cg02699881,cg05225390,cg01481208,cg08634588
200973410159_R03C01,0.89241,0.015756,0.011101,0.018491,0.020476,0.962482,0.677222,0.02956,0.929821,0.899519,...,0.909955,0.043985,0.054816,0.904326,0.135138,0.742557,0.029678,0.079017,0.894593,0.902949

In [18]:
dft.rename(columns=dft.iloc[0], inplace = True)
dft.head(2)

,cg03441945,cg21094410,cg22926093,cg25025609,cg16704802,cg06228737,cg00220102,cg19016494,cg12247200,cg24658413,...,cg12522722,cg11255513,cg09615521,cg12658517,cg02150941,cg22992837,cg02699881,cg05225390,cg01481208,cg08634588
CpG,cg03441945,cg21094410,cg22926093,cg25025609,cg16704802,cg06228737,cg00220102,cg19016494,cg12247200,cg24658413,...,cg12522722,cg11255513,cg09615521,cg12658517,cg02150941,cg22992837,cg02699881,cg05225390,cg01481208,cg08634588
200973410159_R03C01,0.89241,0.015756,0.011101,0.018491,0.020476,0.962482,0.677222,0.02956,0.929821,0.899519,...,0.909955,0.043985,0.054816,0.904326,0.135138,0.742557,0.029678,0.079017,0.894593,0.902949

In [19]:
dft.index.name ='CpG'
dft.reset_index(inplace=True)
dft.head(2)

,CpG,cg03441945,cg21094410,cg22926093,cg25025609,cg16704802,cg06228737,cg00220102,cg19016494,cg12247200,...,cg12522722,cg11255513,cg09615521,cg12658517,cg02150941,cg22992837,cg02699881,cg05225390,cg01481208,cg08634588
0,CpG,cg03441945,cg21094410,cg22926093,cg25025609,cg16704802,cg06228737,cg00220102,cg19016494,cg12247200,...,cg12522722,cg11255513,cg09615521,cg12658517,cg02150941,cg22992837,cg02699881,cg05225390,cg01481208,cg08634588
1,200973410159_R03C01,0.89241,0.015756,0.011101,0.018491,0.020476,0.962482,0.677222,0.02956,0.929821,...,0.909955,0.043985,0.054816,0.904326,0.135138,0.742557,0.029678,0.079017,0.894593,0.902949

In [20]:
dft = dft.drop ([0], axis = 0)
dft.head(2)

,CpG,cg03441945,cg21094410,cg22926093,cg25025609,cg16704802,cg06228737,cg00220102,cg19016494,cg12247200,...,cg12522722,cg11255513,cg09615521,cg12658517,cg02150941,cg22992837,cg02699881,cg05225390,cg01481208,cg08634588
1,200973410159_R03C01,0.89241,0.015756,0.011101,0.018491,0.020476,0.962482,0.677222,0.02956,0.929821,...,0.909955,0.043985,0.054816,0.904326,0.135138,0.742557,0.029678,0.079017,0.894593,0.902949
2,200991620021_R01C01,0.908813,0.01135,0.012197,0.022372,0.018128,0.945195,0.730494,0.017911,0.921435,...,0.900398,0.043525,0.043829,0.899376,0.078902,0.754703,0.030224,0.075161,0.909315,0.903716

In [21]:
dft.rename (columns = {"CpG" : "Sentrix"}, inplace = True)
dft.head(2)

,Sentrix,cg03441945,cg21094410,cg22926093,cg25025609,cg16704802,cg06228737,cg00220102,cg19016494,cg12247200,...,cg12522722,cg11255513,cg09615521,cg12658517,cg02150941,cg22992837,cg02699881,cg05225390,cg01481208,cg08634588
1,200973410159_R03C01,0.89241,0.015756,0.011101,0.018491,0.020476,0.962482,0.677222,0.02956,0.929821,...,0.909955,0.043985,0.054816,0.904326,0.135138,0.742557,0.029678,0.079017,0.894593,0.902949
2,200991620021_R01C01,0.908813,0.01135,0.012197,0.022372,0.018128,0.945195,0.730494,0.017911,0.921435,...,0.900398,0.043525,0.043829,0.899376,0.078902,0.754703,0.030224,0.075161,0.909315,0.903716

In [22]:
df2 = pd.read_csv ("Gastro_PATNO_APPRDX_Age_in524Methyl.csv")
df3 = pd.merge (df2, dft, on= "Sentrix", how= "inner")
print(df3.shape)
df3.head(2)

(458, 34012)

,Sentrix,PATNO,Gender,APPRDX,HYS,Age,AgeCate,SCOPA_Gastro_Category,cg03441945,cg21094410,...,cg12522722,cg11255513,cg09615521,cg12658517,cg02150941,cg22992837,cg02699881,cg05225390,cg01481208,cg08634588
0,200973410159_R03C01,3000,2,2,0,69.1,4,0,0.89241,0.015756,...,0.909955,0.043985,0.054816,0.904326,0.135138,0.742557,0.029678,0.079017,0.894593,0.902949
1,200991620021_R01C01,3001,1,1,2,65.1,4,0,0.908813,0.01135,...,0.900398,0.043525,0.043829,0.899376,0.078902,0.754703,0.030224,0.075161,0.909315,0.903716

In [23]:
df3.to_csv ("Gastro_with_MethylomeDetails_Male.csv", index=False)

# Letter Number

In [24]:
%cd Z:\PPMI_Data\Excels\NonMotors\Derived250\GeneCpG\LetterNumber
df1 = pd.read_csv ("CpG_LetterNumber_Gene.csv")
df1.head(2)

Z:\PPMI_Data\Excels\NonMotors\Derived250\GeneCpG\LetterNumber

   Gene         CpG
0  A1CF  cg20815302
1  A1CF  cg25795414

In [25]:
df = pd.merge (df1, Cpg_File, on = 'CpG', how = 'inner')
df.head(2)

,Gene,CpG,200973410159_R03C01,200991620021_R01C01,200991620021_R03C01,200989060105_R03C01,200989060135_R07C01,200989060162_R04C01,200973410167_R04C01,200973410143_R01C01,...,200989060089_R02C01,200989060089_R01C01,200989060089_R04C01,200973410143_R08C01,200973410143_R07C01,200989060089_R03C01,200989060150_R04C01,200989060150_R05C01,200989060150_R06C01,200991620049_R08C01
0,A1CF,cg20815302,0.915790,0.907957,0.914788,0.932803,0.915434,0.928788,0.918626,0.934745,...,0.933088,0.906952,0.930866,0.910506,0.934667,0.921655,0.929808,0.926381,0.924018,0.904375
1,A1CF,cg25795414,0.899909,0.868910,0.898327,0.871871,0.883100,0.906718,0.865257,0.882964,...,0.847735,0.838449,0.857421,0.863857,0.894889,0.812623,0.902553,0.898325,0.884610,0.876406

In [26]:
df = df.drop('Gene', axis=1)

In [27]:
dft = df.transpose()
dft.head(2)

,0,1,2,3,4,5,6,7,8,9,...,73175,73176,73177,73178,73179,73180,73181,73182,73183,73184
CpG,cg20815302,cg25795414,cg00959375,cg07781847,cg05138383,cg27394794,cg12443990,cg19788329,cg22178513,cg04167299,...,cg27475074,cg02546039,cg25870071,cg26765773,cg22019496,cg02429154,cg05411695,cg13202877,cg17697230,cg05687264
200973410159_R03C01,0.91579,0.899909,0.804116,0.796131,0.740029,0.838002,0.822036,0.813254,0.745601,0.886094,...,0.028559,0.920549,0.469715,0.112805,0.892764,0.925107,0.070574,0.165807,0.918808,0.928897

In [28]:
dft.rename(columns=dft.iloc[0], inplace = True)
dft.head(2)

,cg20815302,cg25795414,cg00959375,cg07781847,cg05138383,cg27394794,cg12443990,cg19788329,cg22178513,cg04167299,...,cg27475074,cg02546039,cg25870071,cg26765773,cg22019496,cg02429154,cg05411695,cg13202877,cg17697230,cg05687264
CpG,cg20815302,cg25795414,cg00959375,cg07781847,cg05138383,cg27394794,cg12443990,cg19788329,cg22178513,cg04167299,...,cg27475074,cg02546039,cg25870071,cg26765773,cg22019496,cg02429154,cg05411695,cg13202877,cg17697230,cg05687264
200973410159_R03C01,0.91579,0.899909,0.804116,0.796131,0.740029,0.838002,0.822036,0.813254,0.745601,0.886094,...,0.028559,0.920549,0.469715,0.112805,0.892764,0.925107,0.070574,0.165807,0.918808,0.928897

In [29]:
dft.index.name ='CpG'
dft.reset_index(inplace=True)
dft.head(2)

,CpG,cg20815302,cg25795414,cg00959375,cg07781847,cg05138383,cg27394794,cg12443990,cg19788329,cg22178513,...,cg27475074,cg02546039,cg25870071,cg26765773,cg22019496,cg02429154,cg05411695,cg13202877,cg17697230,cg05687264
0,CpG,cg20815302,cg25795414,cg00959375,cg07781847,cg05138383,cg27394794,cg12443990,cg19788329,cg22178513,...,cg27475074,cg02546039,cg25870071,cg26765773,cg22019496,cg02429154,cg05411695,cg13202877,cg17697230,cg05687264
1,200973410159_R03C01,0.91579,0.899909,0.804116,0.796131,0.740029,0.838002,0.822036,0.813254,0.745601,...,0.028559,0.920549,0.469715,0.112805,0.892764,0.925107,0.070574,0.165807,0.918808,0.928897

In [30]:
dft = dft.drop ([0], axis = 0)
dft.head(2)

,CpG,cg20815302,cg25795414,cg00959375,cg07781847,cg05138383,cg27394794,cg12443990,cg19788329,cg22178513,...,cg27475074,cg02546039,cg25870071,cg26765773,cg22019496,cg02429154,cg05411695,cg13202877,cg17697230,cg05687264
1,200973410159_R03C01,0.91579,0.899909,0.804116,0.796131,0.740029,0.838002,0.822036,0.813254,0.745601,...,0.028559,0.920549,0.469715,0.112805,0.892764,0.925107,0.070574,0.165807,0.918808,0.928897
2,200991620021_R01C01,0.907957,0.86891,0.752844,0.827413,0.771393,0.766283,0.791932,0.785104,0.723989,...,0.049168,0.906285,0.458602,0.068597,0.859078,0.907987,0.036712,0.177144,0.92703,0.911733

In [31]:
dft.rename (columns = {"CpG" : "Sentrix"}, inplace = True)
dft.head(2)

,Sentrix,cg20815302,cg25795414,cg00959375,cg07781847,cg05138383,cg27394794,cg12443990,cg19788329,cg22178513,...,cg27475074,cg02546039,cg25870071,cg26765773,cg22019496,cg02429154,cg05411695,cg13202877,cg17697230,cg05687264
1,200973410159_R03C01,0.91579,0.899909,0.804116,0.796131,0.740029,0.838002,0.822036,0.813254,0.745601,...,0.028559,0.920549,0.469715,0.112805,0.892764,0.925107,0.070574,0.165807,0.918808,0.928897
2,200991620021_R01C01,0.907957,0.86891,0.752844,0.827413,0.771393,0.766283,0.791932,0.785104,0.723989,...,0.049168,0.906285,0.458602,0.068597,0.859078,0.907987,0.036712,0.177144,0.92703,0.911733

In [32]:
df2 = pd.read_csv ("LetterNumber_PATNO_APPRDX_Age_in524Methyl.csv")
df3 = pd.merge (df2, dft, on= "Sentrix", how= "inner")
print(df3.shape)
df3.head(2)

(458, 73193)

,Sentrix,PATNO,Gender,APPRDX,HYS,Age,AgeCate,LetterNumber_Category,cg20815302,cg25795414,...,cg27475074,cg02546039,cg25870071,cg26765773,cg22019496,cg02429154,cg05411695,cg13202877,cg17697230,cg05687264
0,200973410159_R03C01,3000,2,2,0,69.1,4,1,0.91579,0.899909,...,0.028559,0.920549,0.469715,0.112805,0.892764,0.925107,0.070574,0.165807,0.918808,0.928897
1,200991620021_R01C01,3001,1,1,2,65.1,4,0,0.907957,0.86891,...,0.049168,0.906285,0.458602,0.068597,0.859078,0.907987,0.036712,0.177144,0.92703,0.911733

In [33]:
df3.to_csv ("LetterNumber_with_MethylomeDetails_Male.csv", index=False)

# Lexical Fluency

In [34]:
%cd Z:\PPMI_Data\Excels\NonMotors\Derived250\GeneCpG\LexicalFluency
df1 = pd.read_csv ("CpG_LexicalFluency_Gene.csv")
df1.head(2)

Z:\PPMI_Data\Excels\NonMotors\Derived250\GeneCpG\LexicalFluency

   Gene         CpG
0  AASS  cg02315971
1  AASS  cg24133836

In [35]:
df = pd.merge (df1, Cpg_File, on = 'CpG', how = 'inner')
df.head(2)

,Gene,CpG,200973410159_R03C01,200991620021_R01C01,200991620021_R03C01,200989060105_R03C01,200989060135_R07C01,200989060162_R04C01,200973410167_R04C01,200973410143_R01C01,...,200989060089_R02C01,200989060089_R01C01,200989060089_R04C01,200973410143_R08C01,200973410143_R07C01,200989060089_R03C01,200989060150_R04C01,200989060150_R05C01,200989060150_R06C01,200991620049_R08C01
0,AASS,cg02315971,0.030109,0.028697,0.025308,0.023382,0.025681,0.023762,0.041330,0.024194,...,0.021098,0.023070,0.022708,0.022772,0.024211,0.026369,0.024624,0.022129,0.022931,0.023923
1,AASS,cg24133836,0.016106,0.017000,0.017806,0.019290,0.020248,0.013512,0.025846,0.018763,...,0.019309,0.018105,0.018496,0.014566,0.016133,0.029074,0.017474,0.017538,0.017052,0.017897

In [36]:
df = df.drop('Gene', axis=1)

In [37]:
dft = df.transpose()
dft.head(2)

,0,1,2,3,4,5,6,7,8,9,...,85905,85906,85907,85908,85909,85910,85911,85912,85913,85914
CpG,cg02315971,cg24133836,cg03286969,cg11738782,cg25741731,cg24629744,cg23836745,cg11685489,cg06081147,cg18057762,...,cg12092065,cg10388349,cg11918957,cg26583598,cg11023075,cg02097667,cg21616723,cg27335855,cg18259253,cg15404040
200973410159_R03C01,0.030109,0.016106,0.019371,0.884151,0.026326,0.868373,0.905809,0.825562,0.691096,0.045994,...,0.953091,0.392056,0.913402,0.913637,0.897198,0.871237,0.913624,0.65186,0.852542,0.909412

In [38]:
dft.rename(columns=dft.iloc[0], inplace = True)
dft.head(2)

,cg02315971,cg24133836,cg03286969,cg11738782,cg25741731,cg24629744,cg23836745,cg11685489,cg06081147,cg18057762,...,cg12092065,cg10388349,cg11918957,cg26583598,cg11023075,cg02097667,cg21616723,cg27335855,cg18259253,cg15404040
CpG,cg02315971,cg24133836,cg03286969,cg11738782,cg25741731,cg24629744,cg23836745,cg11685489,cg06081147,cg18057762,...,cg12092065,cg10388349,cg11918957,cg26583598,cg11023075,cg02097667,cg21616723,cg27335855,cg18259253,cg15404040
200973410159_R03C01,0.030109,0.016106,0.019371,0.884151,0.026326,0.868373,0.905809,0.825562,0.691096,0.045994,...,0.953091,0.392056,0.913402,0.913637,0.897198,0.871237,0.913624,0.65186,0.852542,0.909412

In [39]:
dft.index.name ='CpG'
dft.reset_index(inplace=True)
dft.head(2)

,CpG,cg02315971,cg24133836,cg03286969,cg11738782,cg25741731,cg24629744,cg23836745,cg11685489,cg06081147,...,cg12092065,cg10388349,cg11918957,cg26583598,cg11023075,cg02097667,cg21616723,cg27335855,cg18259253,cg15404040
0,CpG,cg02315971,cg24133836,cg03286969,cg11738782,cg25741731,cg24629744,cg23836745,cg11685489,cg06081147,...,cg12092065,cg10388349,cg11918957,cg26583598,cg11023075,cg02097667,cg21616723,cg27335855,cg18259253,cg15404040
1,200973410159_R03C01,0.030109,0.016106,0.019371,0.884151,0.026326,0.868373,0.905809,0.825562,0.691096,...,0.953091,0.392056,0.913402,0.913637,0.897198,0.871237,0.913624,0.65186,0.852542,0.909412

In [40]:
dft = dft.drop ([0], axis = 0)
dft.head(2)

,CpG,cg02315971,cg24133836,cg03286969,cg11738782,cg25741731,cg24629744,cg23836745,cg11685489,cg06081147,...,cg12092065,cg10388349,cg11918957,cg26583598,cg11023075,cg02097667,cg21616723,cg27335855,cg18259253,cg15404040
1,200973410159_R03C01,0.030109,0.016106,0.019371,0.884151,0.026326,0.868373,0.905809,0.825562,0.691096,...,0.953091,0.392056,0.913402,0.913637,0.897198,0.871237,0.913624,0.65186,0.852542,0.909412
2,200991620021_R01C01,0.028697,0.017,0.018631,0.871526,0.026148,0.866396,0.922285,0.881489,0.647436,...,0.924513,0.370289,0.90261,0.914253,0.881206,0.834363,0.91212,0.69253,0.839574,0.867794

In [41]:
dft.rename (columns = {"CpG" : "Sentrix"}, inplace = True)
dft.head(2)

,Sentrix,cg02315971,cg24133836,cg03286969,cg11738782,cg25741731,cg24629744,cg23836745,cg11685489,cg06081147,...,cg12092065,cg10388349,cg11918957,cg26583598,cg11023075,cg02097667,cg21616723,cg27335855,cg18259253,cg15404040
1,200973410159_R03C01,0.030109,0.016106,0.019371,0.884151,0.026326,0.868373,0.905809,0.825562,0.691096,...,0.953091,0.392056,0.913402,0.913637,0.897198,0.871237,0.913624,0.65186,0.852542,0.909412
2,200991620021_R01C01,0.028697,0.017,0.018631,0.871526,0.026148,0.866396,0.922285,0.881489,0.647436,...,0.924513,0.370289,0.90261,0.914253,0.881206,0.834363,0.91212,0.69253,0.839574,0.867794

In [42]:
df2 = pd.read_csv ("LexicalFluency_PATNO_APPRDX_Age_in524Methyl.csv")
df3 = pd.merge (df2, dft, on= "Sentrix", how= "inner")
print(df3.shape)
df3.head(2)

(233, 85923)

,Sentrix,PATNO,Gender,APPRDX,HYS,Age,AgeCate,Lexical_Fluency_Category,cg02315971,cg24133836,...,cg12092065,cg10388349,cg11918957,cg26583598,cg11023075,cg02097667,cg21616723,cg27335855,cg18259253,cg15404040
0,200973410159_R03C01,3000,2,2,0,69.1,4,1,0.030109,0.016106,...,0.953091,0.392056,0.913402,0.913637,0.897198,0.871237,0.913624,0.65186,0.852542,0.909412
1,200991620021_R01C01,3001,1,1,2,65.1,4,0,0.028697,0.017,...,0.924513,0.370289,0.90261,0.914253,0.881206,0.834363,0.91212,0.69253,0.839574,0.867794

In [43]:
df3.to_csv ("LexicalFluency_with_MethylomeDetails_Male.csv", index=False)

# Trail Making B

In [44]:
%cd Z:\PPMI_Data\Excels\NonMotors\Derived250\GeneCpG\TrailMakeB
df1 = pd.read_csv ("CpG_TrailMakingB_Gene.csv")
df1.head(2)

Z:\PPMI_Data\Excels\NonMotors\Derived250\GeneCpG\TrailMakeB

   Gene         CpG
0  AASS  cg02315971
1  AASS  cg24133836

In [45]:
df = pd.merge (df1, Cpg_File, on = 'CpG', how = 'inner')
df.head(2)

,Gene,CpG,200973410159_R03C01,200991620021_R01C01,200991620021_R03C01,200989060105_R03C01,200989060135_R07C01,200989060162_R04C01,200973410167_R04C01,200973410143_R01C01,...,200989060089_R02C01,200989060089_R01C01,200989060089_R04C01,200973410143_R08C01,200973410143_R07C01,200989060089_R03C01,200989060150_R04C01,200989060150_R05C01,200989060150_R06C01,200991620049_R08C01
0,AASS,cg02315971,0.030109,0.028697,0.025308,0.023382,0.025681,0.023762,0.041330,0.024194,...,0.021098,0.023070,0.022708,0.022772,0.024211,0.026369,0.024624,0.022129,0.022931,0.023923
1,AASS,cg24133836,0.016106,0.017000,0.017806,0.019290,0.020248,0.013512,0.025846,0.018763,...,0.019309,0.018105,0.018496,0.014566,0.016133,0.029074,0.017474,0.017538,0.017052,0.017897

In [46]:
df = df.drop('Gene', axis=1)

In [47]:
dft = df.transpose()
dft.head(2)

,0,1,2,3,4,5,6,7,8,9,...,61908,61909,61910,61911,61912,61913,61914,61915,61916,61917
CpG,cg02315971,cg24133836,cg03286969,cg11738782,cg25741731,cg24629744,cg23836745,cg11685489,cg06081147,cg18057762,...,cg00956423,cg14462343,cg07481734,cg22394535,cg13044444,cg23223756,cg16870358,cg04754776,cg00154746,cg06155771
200973410159_R03C01,0.030109,0.016106,0.019371,0.884151,0.026326,0.868373,0.905809,0.825562,0.691096,0.045994,...,0.148515,0.036822,0.053052,0.044051,0.040994,0.047501,0.04635,0.904242,0.021033,0.813738

In [48]:
dft.rename(columns=dft.iloc[0], inplace = True)
dft.head(2)

,cg02315971,cg24133836,cg03286969,cg11738782,cg25741731,cg24629744,cg23836745,cg11685489,cg06081147,cg18057762,...,cg00956423,cg14462343,cg07481734,cg22394535,cg13044444,cg23223756,cg16870358,cg04754776,cg00154746,cg06155771
CpG,cg02315971,cg24133836,cg03286969,cg11738782,cg25741731,cg24629744,cg23836745,cg11685489,cg06081147,cg18057762,...,cg00956423,cg14462343,cg07481734,cg22394535,cg13044444,cg23223756,cg16870358,cg04754776,cg00154746,cg06155771
200973410159_R03C01,0.030109,0.016106,0.019371,0.884151,0.026326,0.868373,0.905809,0.825562,0.691096,0.045994,...,0.148515,0.036822,0.053052,0.044051,0.040994,0.047501,0.04635,0.904242,0.021033,0.813738

In [49]:
dft.index.name ='CpG'
dft.reset_index(inplace=True)
dft.head(2)

,CpG,cg02315971,cg24133836,cg03286969,cg11738782,cg25741731,cg24629744,cg23836745,cg11685489,cg06081147,...,cg00956423,cg14462343,cg07481734,cg22394535,cg13044444,cg23223756,cg16870358,cg04754776,cg00154746,cg06155771
0,CpG,cg02315971,cg24133836,cg03286969,cg11738782,cg25741731,cg24629744,cg23836745,cg11685489,cg06081147,...,cg00956423,cg14462343,cg07481734,cg22394535,cg13044444,cg23223756,cg16870358,cg04754776,cg00154746,cg06155771
1,200973410159_R03C01,0.030109,0.016106,0.019371,0.884151,0.026326,0.868373,0.905809,0.825562,0.691096,...,0.148515,0.036822,0.053052,0.044051,0.040994,0.047501,0.04635,0.904242,0.021033,0.813738

In [50]:
dft = dft.drop ([0], axis = 0)
dft.head(2)

,CpG,cg02315971,cg24133836,cg03286969,cg11738782,cg25741731,cg24629744,cg23836745,cg11685489,cg06081147,...,cg00956423,cg14462343,cg07481734,cg22394535,cg13044444,cg23223756,cg16870358,cg04754776,cg00154746,cg06155771
1,200973410159_R03C01,0.030109,0.016106,0.019371,0.884151,0.026326,0.868373,0.905809,0.825562,0.691096,...,0.148515,0.036822,0.053052,0.044051,0.040994,0.047501,0.04635,0.904242,0.021033,0.813738
2,200991620021_R01C01,0.028697,0.017,0.018631,0.871526,0.026148,0.866396,0.922285,0.881489,0.647436,...,0.10987,0.056582,0.064137,0.053802,0.083556,0.042638,0.041733,0.896521,0.033285,0.753096

In [51]:
dft.rename (columns = {"CpG" : "Sentrix"}, inplace = True)
dft.head(2)

,Sentrix,cg02315971,cg24133836,cg03286969,cg11738782,cg25741731,cg24629744,cg23836745,cg11685489,cg06081147,...,cg00956423,cg14462343,cg07481734,cg22394535,cg13044444,cg23223756,cg16870358,cg04754776,cg00154746,cg06155771
1,200973410159_R03C01,0.030109,0.016106,0.019371,0.884151,0.026326,0.868373,0.905809,0.825562,0.691096,...,0.148515,0.036822,0.053052,0.044051,0.040994,0.047501,0.04635,0.904242,0.021033,0.813738
2,200991620021_R01C01,0.028697,0.017,0.018631,0.871526,0.026148,0.866396,0.922285,0.881489,0.647436,...,0.10987,0.056582,0.064137,0.053802,0.083556,0.042638,0.041733,0.896521,0.033285,0.753096

In [52]:
df2 = pd.read_csv ("TrailMakeB_PATNO_APPRDX_Age_in524Methyl.csv")
df3 = pd.merge (df2, dft, on= "Sentrix", how= "inner")
print(df3.shape)
df3.head(2)

(216, 61926)

,Sentrix,PATNO,Gender,APPRDX,HYS,Age,AgeCate,Trail_Making_B_Category,cg02315971,cg24133836,...,cg00956423,cg14462343,cg07481734,cg22394535,cg13044444,cg23223756,cg16870358,cg04754776,cg00154746,cg06155771
0,200973410159_R03C01,3000,2,2,0,69.1,4,0,0.030109,0.016106,...,0.148515,0.036822,0.053052,0.044051,0.040994,0.047501,0.04635,0.904242,0.021033,0.813738
1,200991620021_R01C01,3001,1,1,2,65.1,4,0,0.028697,0.017,...,0.10987,0.056582,0.064137,0.053802,0.083556,0.042638,0.041733,0.896521,0.033285,0.753096

In [53]:
df3.to_csv ("TrailMakeB_with_MethylomeDetails_Male.csv", index=False)