In [1]:
import pandas as pd
import numpy as np
%cd Z:\PPMI_Data\Excels\Raw_And_More

Z:\PPMI_Data\Excels\Raw_And_More

In [2]:
Cpg_File = pd.read_csv ("beta_post_Funnorm_PPMI_EPICn524final030618.csv")
Cpg_File.head(3)

,200973410159_R03C01,200991620021_R01C01,200991620021_R03C01,200989060105_R03C01,200989060135_R07C01,200989060162_R04C01,200973410167_R04C01,200973410143_R01C01,200973410143_R06C01,200973410167_R05C01,...,200989060089_R02C01,200989060089_R01C01,200989060089_R04C01,200973410143_R08C01,200973410143_R07C01,200989060089_R03C01,200989060150_R04C01,200989060150_R05C01,200989060150_R06C01,200991620049_R08C01
cg14817997,0.834027,0.849201,0.772995,0.885288,0.772547,0.756429,0.719766,0.775910,0.768914,0.759352,...,0.788239,0.838946,0.845263,0.770405,0.852917,0.783813,0.806930,0.875691,0.661276,0.737917
cg26928153,0.945589,0.948538,0.962199,0.944048,0.926306,0.956061,0.912988,0.955983,0.957120,0.897589,...,0.951206,0.958975,0.957062,0.954738,0.947765,0.958086,0.948044,0.942405,0.954990,0.946272
cg16269199,0.845186,0.911488,0.948206,0.913622,0.778551,0.903924,0.742258,0.934683,0.897787,0.741083,...,0.889774,0.899517,0.908055,0.946297,0.910522,0.895500,0.889243,0.825368,0.913328,0.898812

In [3]:
Cpg_File.index.name ='CpG'
Cpg_File.reset_index(inplace=True)
Cpg_File.head(3)

,CpG,200973410159_R03C01,200991620021_R01C01,200991620021_R03C01,200989060105_R03C01,200989060135_R07C01,200989060162_R04C01,200973410167_R04C01,200973410143_R01C01,200973410143_R06C01,...,200989060089_R02C01,200989060089_R01C01,200989060089_R04C01,200973410143_R08C01,200973410143_R07C01,200989060089_R03C01,200989060150_R04C01,200989060150_R05C01,200989060150_R06C01,200991620049_R08C01
0,cg14817997,0.834027,0.849201,0.772995,0.885288,0.772547,0.756429,0.719766,0.775910,0.768914,...,0.788239,0.838946,0.845263,0.770405,0.852917,0.783813,0.806930,0.875691,0.661276,0.737917
1,cg26928153,0.945589,0.948538,0.962199,0.944048,0.926306,0.956061,0.912988,0.955983,0.957120,...,0.951206,0.958975,0.957062,0.954738,0.947765,0.958086,0.948044,0.942405,0.954990,0.946272
2,cg16269199,0.845186,0.911488,0.948206,0.913622,0.778551,0.903924,0.742258,0.934683,0.897787,...,0.889774,0.899517,0.908055,0.946297,0.910522,0.895500,0.889243,0.825368,0.913328,0.898812

In [4]:
df1 = pd.read_csv ("CpG_List_HavingCorres_GeneChr.csv")
df3 = pd.merge (df1, Cpg_File, on= "CpG", how= "inner")
print(df3.shape)
df3.head(2)

(837962, 525)

,CpG,200973410159_R03C01,200991620021_R01C01,200991620021_R03C01,200989060105_R03C01,200989060135_R07C01,200989060162_R04C01,200973410167_R04C01,200973410143_R01C01,200973410143_R06C01,...,200989060089_R02C01,200989060089_R01C01,200989060089_R04C01,200973410143_R08C01,200973410143_R07C01,200989060089_R03C01,200989060150_R04C01,200989060150_R05C01,200989060150_R06C01,200991620049_R08C01
0,cg18478105,0.012578,0.014327,0.015461,0.010655,0.009996,0.009345,0.013387,0.010906,0.008541,...,0.010377,0.016028,0.009028,0.010601,0.011051,0.010528,0.011086,0.011627,0.012368,0.013576
1,cg09835024,0.022227,0.029524,0.027406,0.021273,0.022834,0.044152,0.038306,0.016127,0.015281,...,0.019746,0.025645,0.022651,0.022760,0.021201,0.021772,0.024651,0.017504,0.019783,0.023908

In [5]:
dft = df3.transpose()
dft.head(2)

,0,1,2,3,4,5,6,7,8,9,...,837952,837953,837954,837955,837956,837957,837958,837959,837960,837961
CpG,cg18478105,cg09835024,cg14361672,cg01763666,cg12950382,cg02115394,cg25813447,cg07779434,cg13417420,cg12480843,...,cg23659307,cg16040564,cg02455706,cg21822051,cg10615271,cg23079522,cg16818145,cg14585103,cg10633746,cg12623625
200973410159_R03C01,0.012578,0.022227,0.919272,0.886308,0.504573,0.035614,0.356011,0.360377,0.019089,0.016441,...,0.806559,0.469303,0.371767,0.838957,0.929768,0.887072,0.91134,0.864708,0.061452,0.695212

In [6]:
dft.rename(columns=dft.iloc[0], inplace = True)
dft.head(2)

,cg18478105,cg09835024,cg14361672,cg01763666,cg12950382,cg02115394,cg25813447,cg07779434,cg13417420,cg12480843,...,cg23659307,cg16040564,cg02455706,cg21822051,cg10615271,cg23079522,cg16818145,cg14585103,cg10633746,cg12623625
CpG,cg18478105,cg09835024,cg14361672,cg01763666,cg12950382,cg02115394,cg25813447,cg07779434,cg13417420,cg12480843,...,cg23659307,cg16040564,cg02455706,cg21822051,cg10615271,cg23079522,cg16818145,cg14585103,cg10633746,cg12623625
200973410159_R03C01,0.012578,0.022227,0.919272,0.886308,0.504573,0.035614,0.356011,0.360377,0.019089,0.016441,...,0.806559,0.469303,0.371767,0.838957,0.929768,0.887072,0.91134,0.864708,0.061452,0.695212

In [7]:
dft.index.name ='CpG'
dft.reset_index(inplace=True)
dft.head(2)

,CpG,cg18478105,cg09835024,cg14361672,cg01763666,cg12950382,cg02115394,cg25813447,cg07779434,cg13417420,...,cg23659307,cg16040564,cg02455706,cg21822051,cg10615271,cg23079522,cg16818145,cg14585103,cg10633746,cg12623625
0,CpG,cg18478105,cg09835024,cg14361672,cg01763666,cg12950382,cg02115394,cg25813447,cg07779434,cg13417420,...,cg23659307,cg16040564,cg02455706,cg21822051,cg10615271,cg23079522,cg16818145,cg14585103,cg10633746,cg12623625
1,200973410159_R03C01,0.012578,0.022227,0.919272,0.886308,0.504573,0.035614,0.356011,0.360377,0.019089,...,0.806559,0.469303,0.371767,0.838957,0.929768,0.887072,0.91134,0.864708,0.061452,0.695212

In [8]:
dft = dft.drop ([0], axis = 0)
dft.head(2)

,CpG,cg18478105,cg09835024,cg14361672,cg01763666,cg12950382,cg02115394,cg25813447,cg07779434,cg13417420,...,cg23659307,cg16040564,cg02455706,cg21822051,cg10615271,cg23079522,cg16818145,cg14585103,cg10633746,cg12623625
1,200973410159_R03C01,0.012578,0.022227,0.919272,0.886308,0.504573,0.035614,0.356011,0.360377,0.019089,...,0.806559,0.469303,0.371767,0.838957,0.929768,0.887072,0.91134,0.864708,0.061452,0.695212
2,200991620021_R01C01,0.014327,0.029524,0.902918,0.883315,0.592818,0.024543,0.032831,0.016275,0.024952,...,0.808755,0.460212,0.397015,0.810033,0.90079,0.890029,0.91342,0.820941,0.116707,0.61726

In [9]:
dft.rename (columns = {"CpG" : "Sentrix"}, inplace = True)
dft.head(2)

,Sentrix,cg18478105,cg09835024,cg14361672,cg01763666,cg12950382,cg02115394,cg25813447,cg07779434,cg13417420,...,cg23659307,cg16040564,cg02455706,cg21822051,cg10615271,cg23079522,cg16818145,cg14585103,cg10633746,cg12623625
1,200973410159_R03C01,0.012578,0.022227,0.919272,0.886308,0.504573,0.035614,0.356011,0.360377,0.019089,...,0.806559,0.469303,0.371767,0.838957,0.929768,0.887072,0.91134,0.864708,0.061452,0.695212
2,200991620021_R01C01,0.014327,0.029524,0.902918,0.883315,0.592818,0.024543,0.032831,0.016275,0.024952,...,0.808755,0.460212,0.397015,0.810033,0.90079,0.890029,0.91342,0.820941,0.116707,0.61726

In [10]:
%cd Z:\PPMI_Data\Excels\NonMotors\Derived250
df2 = pd.read_csv ("Sentrix_PATNO_APPRDX_HYS_Gender_Age_of524Methyl_APP1_2.csv")
df3 = pd.merge (df2, dft, on= "Sentrix", how= "inner")
print(df3.shape)
df3.head(2)

Z:\PPMI_Data\Excels\NonMotors\Derived250
(458, 837969)

,Sentrix,PATNO,Gender,APPRDX,HYS,Age,AgeCate,cg18478105,cg09835024,cg14361672,...,cg23659307,cg16040564,cg02455706,cg21822051,cg10615271,cg23079522,cg16818145,cg14585103,cg10633746,cg12623625
0,200973410159_R03C01,3000,2,2,0,69.1,4,0.012578,0.022227,0.919272,...,0.806559,0.469303,0.371767,0.838957,0.929768,0.887072,0.91134,0.864708,0.061452,0.695212
1,200991620021_R01C01,3001,1,1,2,65.1,4,0.014327,0.029524,0.902918,...,0.808755,0.460212,0.397015,0.810033,0.90079,0.890029,0.91342,0.820941,0.116707,0.61726

In [11]:
male = df3[df3.Gender == 1]
print(male.shape)
male.to_csv ("Methylome_Male.csv", index=False)

(308, 837969)

In [12]:
female = df3[df3.Gender == 2]
print(female.shape)
female.to_csv ("Methylome_Female.csv", index=False)

(150, 837969)

# Male RanFor

In [13]:
male = male.drop(['PATNO', 'Sentrix', 'HYS', 'Gender','Age','AgeCate'], axis=1)
print(male.shape)
male.head(2)

(308, 837963)

,APPRDX,cg18478105,cg09835024,cg14361672,cg01763666,cg12950382,cg02115394,cg25813447,cg07779434,cg13417420,...,cg23659307,cg16040564,cg02455706,cg21822051,cg10615271,cg23079522,cg16818145,cg14585103,cg10633746,cg12623625
1,1,0.014327,0.029524,0.902918,0.883315,0.592818,0.024543,0.032831,0.016275,0.024952,...,0.808755,0.460212,0.397015,0.810033,0.90079,0.890029,0.91342,0.820941,0.116707,0.61726
4,2,0.009996,0.022834,0.878833,0.825254,0.842256,0.034446,0.031099,0.019536,0.037505,...,0.829937,0.796395,0.252178,0.809514,0.910937,0.881612,0.873479,0.829998,0.078282,0.620123

In [16]:
import random
import numpy as np
import pandas as pd
import seaborn as sn
from numpy import std
from numpy import mean
import matplotlib.pyplot as plt
from sklearn.datasets import make_classification
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.model_selection import RepeatedStratifiedKFold
from sklearn.metrics import confusion_matrix, accuracy_score
%matplotlib inline

In [ ]:
np.random.seed (1)
dframe1 = pd.DataFrame(columns=['Accuracy', 'Std_Dev'])
for i in range (1,101) :
        print(i)
        dataset = male.groupby('APPRDX').apply(lambda x: x.sample(90))
        X = dataset.iloc[:, 1:].values
        y = dataset.iloc[:, 0].values
        classifier = RandomForestClassifier(n_estimators = 100, criterion = 'entropy', random_state = 1)
        cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=1, random_state=1)
        n_scores = cross_val_score(classifier, X, y, scoring='accuracy', cv=cv, n_jobs=-1, error_score='raise')
        dframe1 = dframe1.append({'Accuracy': mean(n_scores), 'Std_Dev': std(n_scores)}, ignore_index=True)

1

In [ ]:
print(dframe1.head(2))
dframe1.to_csv ("Male_AllCpG_Accuracy_100RF.csv", index=False)

In [ ]:
df2 = male.drop (['APPRDX'], axis=1)

In [ ]:
np.random.seed (1)
dframe1 = pd.DataFrame(columns=['Accuracy', 'Std_Dev'])
for i in range (1,101) :
        print(i)
        df3 = df2.sample(43, axis=1)
        df3 = df3.reindex(['APPRDX', *df3.columns], axis=1).assign(APPRDX=male['APPRDX'])
        dataset = df3.groupby('APPRDX').apply(lambda x: x.sample(90))
        X = dataset.iloc[:, 1:].values
        y = dataset.iloc[:, 0].values
        classifier = RandomForestClassifier(n_estimators = 100, criterion = 'entropy', random_state = 1)
        cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=1, random_state=1)
        n_scores = cross_val_score(classifier, X, y, scoring='accuracy', cv=cv, n_jobs=-1, error_score='raise')
        dframe1 = dframe1.append({'Accuracy': mean(n_scores), 'Std_Dev': std(n_scores)}, ignore_index=True)

In [ ]:
print(dframe1.head(2))
dframe1.to_csv ("Male_Rand43CpG_Accuracy_100RF.csv", index=False)

# Female RanFor

In [ ]:
female = female.drop(['PATNO', 'Sentrix', 'HYS', 'Gender','Age','AgeCate'], axis=1)
print(female.shape)
female.head(2)

In [ ]:
np.random.seed (1)
dframe1 = pd.DataFrame(columns=['Accuracy', 'Std_Dev'])
for i in range (1,101) :
        print(i)
        dataset = female.groupby('APPRDX').apply(lambda x: x.sample(50))
        X = dataset.iloc[:, 1:].values
        y = dataset.iloc[:, 0].values
        classifier = RandomForestClassifier(n_estimators = 100, criterion = 'entropy', random_state = 1)
        cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=1, random_state=1)
        n_scores = cross_val_score(classifier, X, y, scoring='accuracy', cv=cv, n_jobs=-1, error_score='raise')
        dframe1 = dframe1.append({'Accuracy': mean(n_scores), 'Std_Dev': std(n_scores)}, ignore_index=True)

In [ ]:
print(dframe1.head(2))
dframe1.to_csv ("Female_AllCpG_Accuracy_100RF.csv", index=False)

In [ ]:
df2 = female.drop (['APPRDX'], axis=1)

In [ ]:
np.random.seed (1)
dframe1 = pd.DataFrame(columns=['Accuracy', 'Std_Dev'])
for i in range (1,101) :
        print(i)
        df3 = df2.sample(61, axis=1)
        df3 = df3.reindex(['APPRDX', *df3.columns], axis=1).assign(APPRDX=female['APPRDX'])
        dataset = df3.groupby('APPRDX').apply(lambda x: x.sample(50))
        X = dataset.iloc[:, 1:].values
        y = dataset.iloc[:, 0].values
        classifier = RandomForestClassifier(n_estimators = 100, criterion = 'entropy', random_state = 1)
        cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=1, random_state=1)
        n_scores = cross_val_score(classifier, X, y, scoring='accuracy', cv=cv, n_jobs=-1, error_score='raise')
        dframe1 = dframe1.append({'Accuracy': mean(n_scores), 'Std_Dev': std(n_scores)}, ignore_index=True)

In [ ]:
print(dframe1.head(2))
dframe1.to_csv ("Male_Rand61CpG_Accuracy_100RF.csv", index=False)