# Random Forest Classification

In [1]:
import random
import numpy as np
import pandas as pd
import seaborn as sn
from numpy import std
from numpy import mean
import matplotlib.pyplot as plt
from sklearn.datasets import make_classification
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.model_selection import RepeatedStratifiedKFold
from sklearn.metrics import confusion_matrix, accuracy_score
%matplotlib inline

## NMI

In [2]:
%cd Z:\PPMI_Data\Excels\NonMotors\Derived250\Male\GeneCpG\SleepDay
df = pd.read_csv('Top50NMI_SleepDay_Data.csv')
print(df.shape)
df.head(3)

Z:\PPMI_Data\Excels\NonMotors\Derived250\Male\GeneCpG\SleepDay
(308, 52)

,PATNO,APPRDX,cg20003494,cg12653876,cg19559114,cg13795060,cg10131227,cg15272034,cg16004767,cg01408558,...,cg22241593,cg03508526,cg10714075,cg15218327,cg20411801,cg17228497,cg16517394,cg19811651,cg05519181,cg23140159
0,3001,1,0.025708,0.892774,0.823933,0.187463,0.929469,0.850724,0.882369,0.770711,...,0.017264,0.095867,0.897690,0.837743,0.895766,0.611259,0.092042,0.062875,0.828366,0.696181
1,3007,1,0.045513,0.859283,0.882641,0.095824,0.719363,0.837866,0.906843,0.796137,...,0.021060,0.141188,0.895978,0.916967,0.922310,0.609222,0.065297,0.094841,0.857273,0.708511
2,3010,1,0.044374,0.852632,0.848369,0.062519,0.745797,0.841361,0.911231,0.758337,...,0.022451,0.107678,0.909621,0.887360,0.920713,0.656509,0.044813,0.106636,0.872761,0.700434

In [3]:
df1 = df.drop(['PATNO'], axis=1)
df1.head(2)

,APPRDX,cg20003494,cg12653876,cg19559114,cg13795060,cg10131227,cg15272034,cg16004767,cg01408558,cg12869499,...,cg22241593,cg03508526,cg10714075,cg15218327,cg20411801,cg17228497,cg16517394,cg19811651,cg05519181,cg23140159
0,1,0.025708,0.892774,0.823933,0.187463,0.929469,0.850724,0.882369,0.770711,0.575865,...,0.017264,0.095867,0.897690,0.837743,0.895766,0.611259,0.092042,0.062875,0.828366,0.696181
1,1,0.045513,0.859283,0.882641,0.095824,0.719363,0.837866,0.906843,0.796137,0.628405,...,0.021060,0.141188,0.895978,0.916967,0.922310,0.609222,0.065297,0.094841,0.857273,0.708511

In [4]:
np.random.seed (1)
dframe1 = pd.DataFrame(columns=['Accuracy', 'Std_Dev'])
for i in range (1,101) :
        print(i)
        dataset = df1.groupby('APPRDX').apply(lambda x: x.sample(90))
        X = dataset.iloc[:, 1:].values
        y = dataset.iloc[:, 0].values
        classifier = RandomForestClassifier(n_estimators = 100, criterion = 'entropy', random_state = 1)
        cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=5, random_state=1)
        n_scores = cross_val_score(classifier, X, y, scoring='accuracy', cv=cv, n_jobs=-1, error_score='raise')
        dframe1 = dframe1.append({'Accuracy': mean(n_scores), 'Std_Dev': std(n_scores)}, ignore_index=True)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100

In [5]:
print(dframe1.head(2))
dframe1.to_csv ("SleepDay_NMICpG_100RF.csv")

   Accuracy   Std_Dev
0  0.713333  0.091192
1  0.703333  0.115261

## Boruta

In [6]:
df = pd.read_csv('Top50Boruta_SleepDay_Data.csv')
print(df.shape)
df.head(3)

(308, 52)

,PATNO,APPRDX,cg22505241,cg03389720,cg01480447,cg21426547,cg12004671,cg09582880,cg16004767,cg26250461,...,cg17184604,cg02152968,cg11865360,cg14311020,cg06301399,cg27427921,cg16636935,cg12282552,cg02847244,cg03552709
0,3001,1,0.914495,0.764712,0.899355,0.732635,0.906671,0.925190,0.882369,0.865737,...,0.009053,0.263403,0.279839,0.016512,0.799493,0.140804,0.431007,0.440017,0.926509,0.884891
1,3007,1,0.874121,0.820463,0.886978,0.802686,0.932671,0.919332,0.906843,0.856892,...,0.008577,0.231128,0.137535,0.024924,0.736076,0.121699,0.429671,0.492883,0.916526,0.913208
2,3010,1,0.856860,0.785917,0.902242,0.844700,0.925557,0.914905,0.911231,0.877341,...,0.008722,0.018493,0.129196,0.023967,0.698125,0.156907,0.425644,0.527331,0.925241,0.900736

In [7]:
df1 = df.drop(['PATNO'], axis=1)
df1.head(2)

,APPRDX,cg22505241,cg03389720,cg01480447,cg21426547,cg12004671,cg09582880,cg16004767,cg26250461,cg07537147,...,cg17184604,cg02152968,cg11865360,cg14311020,cg06301399,cg27427921,cg16636935,cg12282552,cg02847244,cg03552709
0,1,0.914495,0.764712,0.899355,0.732635,0.906671,0.925190,0.882369,0.865737,0.185815,...,0.009053,0.263403,0.279839,0.016512,0.799493,0.140804,0.431007,0.440017,0.926509,0.884891
1,1,0.874121,0.820463,0.886978,0.802686,0.932671,0.919332,0.906843,0.856892,0.164272,...,0.008577,0.231128,0.137535,0.024924,0.736076,0.121699,0.429671,0.492883,0.916526,0.913208

In [8]:
np.random.seed (1)
dframe1 = pd.DataFrame(columns=['Accuracy', 'Std_Dev'])
for i in range (1,101) :
        print(i)
        dataset = df1.groupby('APPRDX').apply(lambda x: x.sample(90))
        X = dataset.iloc[:, 1:].values
        y = dataset.iloc[:, 0].values
        classifier = RandomForestClassifier(n_estimators = 100, criterion = 'entropy', random_state = 1)
        cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=5, random_state=1)
        n_scores = cross_val_score(classifier, X, y, scoring='accuracy', cv=cv, n_jobs=-1, error_score='raise')
        dframe1 = dframe1.append({'Accuracy': mean(n_scores), 'Std_Dev': std(n_scores)}, ignore_index=True)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100

In [9]:
print(dframe1.head(2))
dframe1.to_csv ("SleepDay_BorutaCpG_100RF.csv")

   Accuracy   Std_Dev
0  0.646667  0.093466
1  0.677778  0.103040

## BorutaR

In [10]:
df = pd.read_csv('BorutaR_SleepDay_Male.csv')
print(df.shape)
df.head(3)

(308, 4)

   PATNO  APPRDX  cg10895922  cg21426547
0   3001       1    0.063407    0.732635
1   3007       1    0.067457    0.802686
2   3010       1    0.052772    0.844700

In [11]:
df1 = df.drop(['PATNO'], axis=1)
df1.head(2)

   APPRDX  cg10895922  cg21426547
0       1    0.063407    0.732635
1       1    0.067457    0.802686

In [12]:
np.random.seed (1)
dframe1 = pd.DataFrame(columns=['Accuracy', 'Std_Dev'])
for i in range (1,101) :
        print(i)
        dataset = df1.groupby('APPRDX').apply(lambda x: x.sample(90))
        X = dataset.iloc[:, 1:].values
        y = dataset.iloc[:, 0].values
        classifier = RandomForestClassifier(n_estimators = 100, criterion = 'entropy', random_state = 1)
        cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=5, random_state=1)
        n_scores = cross_val_score(classifier, X, y, scoring='accuracy', cv=cv, n_jobs=-1, error_score='raise')
        dframe1 = dframe1.append({'Accuracy': mean(n_scores), 'Std_Dev': std(n_scores)}, ignore_index=True)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100

In [13]:
print(dframe1.head(2))
dframe1.to_csv ("SleepDay_BorutaRCpG_100RF.csv")

   Accuracy   Std_Dev
0  0.543333  0.108463
1  0.491111  0.112415

## Common

In [15]:
df = pd.read_csv('Common7_Sleepday_Data_Male.csv')
print(df.shape)
df.head(3)

(308, 9)

,PATNO,APPRDX,cg22505241,cg16004767,cg05519181,cg12229394,cg12653876,cg10895922,cg21426547
0,3001,1,0.914495,0.882369,0.828366,0.025663,0.892774,0.063407,0.732635
1,3007,1,0.874121,0.906843,0.857273,0.031369,0.859283,0.067457,0.802686
2,3010,1,0.856860,0.911231,0.872761,0.039719,0.852632,0.052772,0.844700

In [16]:
df1 = df.drop(['PATNO'], axis=1)
df1.head(2)

,APPRDX,cg22505241,cg16004767,cg05519181,cg12229394,cg12653876,cg10895922,cg21426547
0,1,0.914495,0.882369,0.828366,0.025663,0.892774,0.063407,0.732635
1,1,0.874121,0.906843,0.857273,0.031369,0.859283,0.067457,0.802686

In [17]:
np.random.seed (1)
dframe1 = pd.DataFrame(columns=['Accuracy', 'Std_Dev'])
for i in range (1,101) :
        print(i)
        dataset = df1.groupby('APPRDX').apply(lambda x: x.sample(90))
        X = dataset.iloc[:, 1:].values
        y = dataset.iloc[:, 0].values
        classifier = RandomForestClassifier(n_estimators = 100, criterion = 'entropy', random_state = 1)
        cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=5, random_state=1)
        n_scores = cross_val_score(classifier, X, y, scoring='accuracy', cv=cv, n_jobs=-1, error_score='raise')
        dframe1 = dframe1.append({'Accuracy': mean(n_scores), 'Std_Dev': std(n_scores)}, ignore_index=True)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100

In [18]:
print(dframe1.head(2))
dframe1.to_csv ("Sleepday_Male_Common10CpG_100RF.csv")

   Accuracy   Std_Dev
0  0.678889  0.116688
1  0.605556  0.090438